/**
 * TechHub Products - B2B Electronics Catalog
 * 105 enterprise-grade products for business customers
 */

import { Product } from "./types.js";

export const products: Product[] = [
  // ==================== LAPTOPS (25) ====================
  // Business Laptops (15)
  {
    id: "th-001",
    name: "Dell Latitude 7430",
    brand: "Dell",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1499.99,
    original_price: 1699.99,
    rating: 4.6,
    review_count: 2847,
    in_stock: true,
    stock_quantity: 45,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "latitude", "business", "enterprise", "intel", "14-inch", "professional", "vpro"],
    specs: {
      processor: "Intel Core i7-1265U",
      memory: "16GB DDR4",
      storage: "512GB NVMe SSD",
      display: "14-inch FHD (1920x1080) IPS",
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.0, RJ45",
      weight: "1.37 kg",
      warranty: "3 years ProSupport",
    },
  },
  {
    id: "th-002",
    name: "Lenovo ThinkPad T14s Gen 4",
    brand: "Lenovo",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1699.99,
    rating: 4.7,
    review_count: 1923,
    in_stock: true,
    stock_quantity: 38,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkpad", "business", "enterprise", "amd", "14-inch", "professional", "ryzen"],
    specs: {
      processor: "AMD Ryzen 7 PRO 7840U",
      memory: "32GB LPDDR5",
      storage: "1TB NVMe SSD",
      display: "14-inch WUXGA (1920x1200) IPS 400 nits",
      os: "Windows 11 Pro",
      battery: "Up to 14 hours",
      ports: "2x USB-C USB4, 2x USB-A, HDMI 2.1, RJ45",
      weight: "1.29 kg",
      warranty: "3 years Premier Support",
    },
  },
  {
    id: "th-003",
    name: "HP EliteBook 840 G10",
    brand: "HP",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1599.99,
    original_price: 1799.99,
    rating: 4.5,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 52,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "elitebook", "business", "enterprise", "touchscreen", "14-inch", "professional"],
    specs: {
      processor: "Intel Core i7-1355U",
      memory: "16GB DDR5",
      storage: "512GB NVMe SSD",
      display: "14-inch FHD (1920x1080) Touch IPS",
      os: "Windows 11 Pro",
      battery: "Up to 11 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.1, RJ45",
      weight: "1.36 kg",
      warranty: "3 years HP Care Pack",
    },
  },
  {
    id: "th-004",
    name: "Dell Latitude 5540",
    brand: "Dell",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1799.99,
    rating: 4.4,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 28,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "latitude", "business", "enterprise", "15-inch", "large-screen", "professional"],
    specs: {
      processor: "Intel Core i7-1370P",
      memory: "32GB DDR4",
      storage: "1TB NVMe SSD",
      display: "15.6-inch FHD (1920x1080) IPS",
      os: "Windows 11 Pro",
      battery: "Up to 9 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.0, RJ45, SD reader",
      weight: "1.79 kg",
      warranty: "3 years ProSupport",
    },
  },
  {
    id: "th-005",
    name: "Lenovo ThinkPad E16 Gen 1",
    brand: "Lenovo",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1099.99,
    original_price: 1299.99,
    rating: 4.3,
    review_count: 892,
    in_stock: true,
    stock_quantity: 67,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkpad", "business", "value", "16-inch", "budget-friendly", "productivity"],
    specs: {
      processor: "Intel Core i5-1335U",
      memory: "16GB DDR4",
      storage: "512GB NVMe SSD",
      display: "16-inch WUXGA (1920x1200) IPS",
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "2x USB-C, 2x USB-A, HDMI 2.1, RJ45",
      weight: "1.77 kg",
      warranty: "1 year depot",
    },
  },
  {
    id: "th-006",
    name: "HP EliteBook 1040 G9",
    brand: "HP",
    category: "laptop",
    subcategory: "business_laptop",
    price: 2199.99,
    rating: 4.6,
    review_count: 756,
    in_stock: true,
    stock_quantity: 22,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "elitebook", "business", "premium", "lte", "14-inch", "executive"],
    specs: {
      processor: "Intel Core i7-1270P",
      memory: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      display: "14-inch WUXGA (1920x1200) IPS 1000 nits",
      os: "Windows 11 Pro",
      battery: "Up to 11 hours",
      ports: "2x USB-C Thunderbolt 4, 1x USB-A, HDMI 2.0",
      connectivity: "5G LTE, Wi-Fi 6E, Bluetooth 5.2",
      weight: "1.18 kg",
      warranty: "3 years HP Care Pack",
    },
  },
  {
    id: "th-007",
    name: "Dell Latitude 9440 2-in-1",
    brand: "Dell",
    category: "laptop",
    subcategory: "business_laptop",
    price: 2399.99,
    original_price: 2699.99,
    rating: 4.5,
    review_count: 634,
    in_stock: true,
    stock_quantity: 18,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "latitude", "business", "2-in-1", "convertible", "touchscreen", "premium"],
    specs: {
      processor: "Intel Core i7-1365U",
      memory: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      display: "14-inch QHD+ (2560x1600) Touch IPS",
      os: "Windows 11 Pro",
      battery: "Up to 11 hours",
      ports: "3x USB-C Thunderbolt 4, 1x USB-A",
      weight: "1.53 kg",
      warranty: "3 years ProSupport",
    },
  },
  {
    id: "th-008",
    name: "Lenovo ThinkPad L13 Yoga Gen 4",
    brand: "Lenovo",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1199.99,
    rating: 4.4,
    review_count: 1089,
    in_stock: true,
    stock_quantity: 41,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkpad", "business", "2-in-1", "convertible", "stylus", "compact"],
    specs: {
      processor: "Intel Core i5-1335U",
      memory: "16GB DDR4",
      storage: "256GB NVMe SSD",
      display: "13.3-inch FHD (1920x1080) Touch IPS",
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "2x USB-C, 2x USB-A, HDMI 2.0",
      features: "Garaged stylus included",
      weight: "1.43 kg",
      warranty: "1 year depot",
    },
  },
  {
    id: "th-009",
    name: "HP ProBook 450 G10",
    brand: "HP",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1299.99,
    original_price: 1499.99,
    rating: 4.2,
    review_count: 1456,
    in_stock: true,
    stock_quantity: 73,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "probook", "business", "mid-range", "15-inch", "productivity"],
    specs: {
      processor: "Intel Core i7-1355U",
      memory: "16GB DDR4",
      storage: "512GB NVMe SSD",
      display: "15.6-inch FHD (1920x1080) IPS",
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "2x USB-C, 2x USB-A, HDMI 1.4b, RJ45",
      weight: "1.74 kg",
      warranty: "1 year depot",
    },
  },
  {
    id: "th-010",
    name: "Dell Latitude 5340",
    brand: "Dell",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1199.99,
    rating: 4.3,
    review_count: 823,
    in_stock: false,
    stock_quantity: 0,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "latitude", "business", "compact", "13-inch", "portable"],
    specs: {
      processor: "Intel Core i5-1345U",
      memory: "16GB DDR4",
      storage: "256GB NVMe SSD",
      display: "13.3-inch FHD (1920x1080) IPS",
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "2x USB-C Thunderbolt 4, 1x USB-A, HDMI 2.0, RJ45",
      weight: "1.20 kg",
      warranty: "3 years ProSupport",
    },
  },
  {
    id: "th-011",
    name: "Lenovo ThinkPad X13 Gen 4",
    brand: "Lenovo",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1499.99,
    rating: 4.5,
    review_count: 967,
    in_stock: true,
    stock_quantity: 35,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkpad", "business", "compact", "13-inch", "amd", "portable"],
    specs: {
      processor: "AMD Ryzen 7 PRO 7840U",
      memory: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      display: "13.3-inch WUXGA (1920x1200) IPS 300 nits",
      os: "Windows 11 Pro",
      battery: "Up to 14 hours",
      ports: "2x USB-C USB4, 2x USB-A, HDMI 2.1",
      weight: "1.19 kg",
      warranty: "3 years Premier Support",
    },
  },
  {
    id: "th-012",
    name: "HP EliteBook 865 G10",
    brand: "HP",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1899.99,
    original_price: 2099.99,
    rating: 4.6,
    review_count: 534,
    in_stock: true,
    stock_quantity: 29,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "elitebook", "business", "enterprise", "16-inch", "amd", "large-screen"],
    specs: {
      processor: "AMD Ryzen 7 PRO 7840U",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "16-inch WUXGA (1920x1200) IPS 400 nits",
      os: "Windows 11 Pro",
      battery: "Up to 12 hours",
      ports: "2x USB-C USB4, 2x USB-A, HDMI 2.1, RJ45",
      weight: "1.63 kg",
      warranty: "3 years HP Care Pack",
    },
  },
  {
    id: "th-013",
    name: "Dell Latitude 7640",
    brand: "Dell",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1999.99,
    rating: 4.4,
    review_count: 445,
    in_stock: true,
    stock_quantity: 24,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "latitude", "business", "enterprise", "16-inch", "productivity"],
    specs: {
      processor: "Intel Core i7-1385U",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "16-inch FHD+ (1920x1200) IPS",
      os: "Windows 11 Pro",
      battery: "Up to 9 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.0, RJ45",
      weight: "1.87 kg",
      warranty: "3 years ProSupport",
    },
  },
  {
    id: "th-014",
    name: "Lenovo ThinkPad T16 Gen 2",
    brand: "Lenovo",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1899.99,
    rating: 4.5,
    review_count: 678,
    in_stock: true,
    stock_quantity: 31,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkpad", "business", "enterprise", "16-inch", "high-resolution"],
    specs: {
      processor: "Intel Core i7-1370P",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "16-inch WQUXGA (3840x2400) IPS 500 nits",
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.1, RJ45",
      weight: "1.83 kg",
      warranty: "3 years Premier Support",
    },
  },
  {
    id: "th-015",
    name: "HP EliteBook 830 G9",
    brand: "HP",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1399.99,
    original_price: 1599.99,
    rating: 4.3,
    review_count: 1123,
    in_stock: true,
    stock_quantity: 48,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "elitebook", "business", "compact", "13-inch", "portable"],
    specs: {
      processor: "Intel Core i5-1245U",
      memory: "16GB DDR5",
      storage: "512GB NVMe SSD",
      display: "13.3-inch FHD (1920x1080) IPS 1000 nits",
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "2x USB-C Thunderbolt 4, 1x USB-A, HDMI 2.0",
      weight: "1.12 kg",
      warranty: "3 years HP Care Pack",
    },
  },

  // Workstations (5)
  {
    id: "th-016",
    name: "Dell Precision 3571",
    brand: "Dell",
    category: "laptop",
    subcategory: "workstation",
    price: 2499.99,
    original_price: 2799.99,
    rating: 4.7,
    review_count: 892,
    in_stock: true,
    stock_quantity: 19,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "precision", "workstation", "cad", "nvidia", "15-inch", "professional"],
    specs: {
      processor: "Intel Core i7-12800H 14-core",
      graphics: "NVIDIA RTX A2000 8GB",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "15.6-inch FHD (1920x1080) IPS",
      os: "Windows 11 Pro for Workstations",
      battery: "Up to 7 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.0, RJ45, SD reader",
      weight: "1.79 kg",
      warranty: "3 years ProSupport",
    },
  },
  {
    id: "th-017",
    name: "HP ZBook Power G10",
    brand: "HP",
    category: "laptop",
    subcategory: "workstation",
    price: 3299.99,
    rating: 4.8,
    review_count: 567,
    in_stock: true,
    stock_quantity: 12,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "zbook", "workstation", "cad", "nvidia", "high-end", "15-inch"],
    specs: {
      processor: "Intel Core i9-13950HX 24-core",
      graphics: "NVIDIA RTX 3000 Ada 8GB",
      memory: "64GB DDR5",
      storage: "2TB NVMe SSD",
      display: "15.6-inch FHD (1920x1080) IPS",
      os: "Windows 11 Pro for Workstations",
      battery: "Up to 6 hours",
      ports: "2x USB-C Thunderbolt 4, 3x USB-A, HDMI 2.1, RJ45",
      weight: "2.13 kg",
      warranty: "3 years HP Care Pack",
    },
  },
  {
    id: "th-018",
    name: "Lenovo ThinkPad P16 Gen 2",
    brand: "Lenovo",
    category: "laptop",
    subcategory: "workstation",
    price: 3499.99,
    original_price: 3899.99,
    rating: 4.7,
    review_count: 423,
    in_stock: true,
    stock_quantity: 8,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkpad", "workstation", "cad", "nvidia", "high-end", "16-inch"],
    specs: {
      processor: "Intel Core i7-13850HX 20-core",
      graphics: "NVIDIA RTX 3500 Ada 12GB",
      memory: "64GB DDR5",
      storage: "2TB NVMe SSD",
      display: "16-inch WQUXGA (3840x2400) OLED 400 nits",
      os: "Windows 11 Pro for Workstations",
      battery: "Up to 6 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.1, RJ45, SD Express",
      weight: "2.95 kg",
      warranty: "3 years Premier Support",
    },
  },
  {
    id: "th-019",
    name: "Dell Precision 5570",
    brand: "Dell",
    category: "laptop",
    subcategory: "workstation",
    price: 2699.99,
    rating: 4.6,
    review_count: 734,
    in_stock: true,
    stock_quantity: 15,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "precision", "workstation", "cad", "nvidia", "15-inch", "mobile"],
    specs: {
      processor: "Intel Core i7-12700H 14-core",
      graphics: "NVIDIA RTX A2000 8GB",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "15.6-inch FHD+ (1920x1200) IPS",
      os: "Windows 11 Pro for Workstations",
      battery: "Up to 7 hours",
      ports: "2x USB-C Thunderbolt 4, 1x USB-A, SD reader, HDMI 2.0",
      weight: "1.84 kg",
      warranty: "3 years ProSupport",
    },
  },
  {
    id: "th-020",
    name: "HP ZBook Studio G10",
    brand: "HP",
    category: "laptop",
    subcategory: "workstation",
    price: 2899.99,
    rating: 4.8,
    review_count: 345,
    in_stock: false,
    stock_quantity: 0,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "zbook", "workstation", "cad", "nvidia", "creative", "16-inch"],
    specs: {
      processor: "Intel Core i7-13800H 14-core",
      graphics: "NVIDIA RTX 4000 Ada 12GB",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "16-inch WQUXGA (3840x2400) DreamColor OLED 500 nits",
      os: "Windows 11 Pro for Workstations",
      battery: "Up to 7 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.1",
      weight: "1.78 kg",
      warranty: "3 years HP Care Pack",
    },
  },

  // Ultrabooks (5)
  {
    id: "th-021",
    name: "Apple MacBook Pro 16-inch M3 Max",
    brand: "Apple",
    category: "laptop",
    subcategory: "ultrabook",
    price: 3999.99,
    rating: 4.9,
    review_count: 4523,
    in_stock: true,
    stock_quantity: 25,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["apple", "macbook", "ultrabook", "macos", "creative", "m3", "16-inch"],
    specs: {
      processor: "Apple M3 Max 14-core CPU, 30-core GPU",
      memory: "36GB unified memory",
      storage: "1TB SSD",
      display: "16.2-inch Liquid Retina XDR 3456x2234",
      os: "macOS Sonoma",
      battery: "Up to 22 hours",
      ports: "3x Thunderbolt 4, HDMI, SD card, MagSafe 3",
      weight: "2.14 kg",
      warranty: "1 year AppleCare",
    },
  },
  {
    id: "th-022",
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    brand: "Lenovo",
    category: "laptop",
    subcategory: "ultrabook",
    price: 2299.99,
    original_price: 2599.99,
    rating: 4.7,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 33,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkpad", "ultrabook", "premium", "lightweight", "14-inch", "executive"],
    specs: {
      processor: "Intel Core i7-1365U",
      memory: "32GB LPDDR5",
      storage: "1TB NVMe SSD",
      display: "14-inch WUXGA (1920x1200) IPS 400 nits anti-glare",
      os: "Windows 11 Pro",
      battery: "Up to 15 hours",
      ports: "2x USB-C Thunderbolt 4, 2x USB-A, HDMI 2.0",
      weight: "1.12 kg",
      warranty: "3 years Premier Support",
    },
  },
  {
    id: "th-023",
    name: "Dell XPS 15 9530",
    brand: "Dell",
    category: "laptop",
    subcategory: "ultrabook",
    price: 2599.99,
    rating: 4.6,
    review_count: 1876,
    in_stock: true,
    stock_quantity: 20,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "xps", "ultrabook", "premium", "oled", "15-inch", "creator"],
    specs: {
      processor: "Intel Core i7-13700H 14-core",
      graphics: "NVIDIA RTX 4050 6GB",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "15.6-inch 3.5K (3456x2160) OLED Touch",
      os: "Windows 11 Home",
      battery: "Up to 9 hours",
      ports: "2x Thunderbolt 4, 1x USB-C, SD card reader",
      weight: "1.86 kg",
      warranty: "1 year Premium Support",
    },
  },
  {
    id: "th-024",
    name: "Apple MacBook Air 15-inch M3",
    brand: "Apple",
    category: "laptop",
    subcategory: "ultrabook",
    price: 1699.99,
    rating: 4.8,
    review_count: 3892,
    in_stock: true,
    stock_quantity: 47,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["apple", "macbook", "ultrabook", "macos", "lightweight", "m3", "15-inch"],
    specs: {
      processor: "Apple M3 8-core CPU, 10-core GPU",
      memory: "16GB unified memory",
      storage: "512GB SSD",
      display: "15.3-inch Liquid Retina 2880x1864",
      os: "macOS Sonoma",
      battery: "Up to 18 hours",
      ports: "2x Thunderbolt 4, MagSafe 3, headphone jack",
      weight: "1.51 kg",
      warranty: "1 year AppleCare",
    },
  },
  {
    id: "th-025",
    name: "Lenovo ThinkPad X1 Nano Gen 3",
    brand: "Lenovo",
    category: "laptop",
    subcategory: "ultrabook",
    price: 1999.99,
    original_price: 2199.99,
    rating: 4.5,
    review_count: 823,
    in_stock: true,
    stock_quantity: 16,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkpad", "ultrabook", "premium", "ultra-light", "13-inch", "travel"],
    specs: {
      processor: "Intel Core i7-1360P",
      memory: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      display: "13-inch 2K (2160x1350) IPS 450 nits",
      os: "Windows 11 Pro",
      battery: "Up to 14 hours",
      ports: "2x Thunderbolt 4",
      weight: "0.97 kg",
      warranty: "3 years Premier Support",
    },
  },

  // ==================== MONITORS (20) ====================
  // 4K Displays (8)
  {
    id: "th-026",
    name: "Dell UltraSharp U3223QE",
    brand: "Dell",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 899.99,
    original_price: 999.99,
    rating: 4.7,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 42,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "ultrasharp", "4k", "usb-c", "ips-black", "32-inch", "hub-monitor"],
    specs: {
      size: "31.5-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS Black",
      brightness: "400 nits",
      contrast: "2000:1",
      color: "100% sRGB, 98% DCI-P3",
      ports: "1x USB-C 90W PD, 5x USB-A, RJ45, DP, 2x HDMI",
      ergonomic: "Height, pivot, swivel, tilt adjustable",
      warranty: "3 years",
    },
  },
  {
    id: "th-027",
    name: "Dell UltraSharp U2723QE",
    brand: "Dell",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 679.99,
    rating: 4.6,
    review_count: 3421,
    in_stock: true,
    stock_quantity: 58,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "ultrasharp", "4k", "usb-c", "ips-black", "27-inch", "hub-monitor"],
    specs: {
      size: "27-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS Black",
      brightness: "400 nits",
      contrast: "2000:1",
      color: "100% sRGB, 98% DCI-P3",
      ports: "1x USB-C 90W PD, 4x USB-A, RJ45, DP, HDMI",
      ergonomic: "Height, pivot, swivel, tilt adjustable",
      warranty: "3 years",
    },
  },
  {
    id: "th-028",
    name: "LG 32UN880-B UltraFine",
    brand: "LG",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 699.99,
    original_price: 799.99,
    rating: 4.5,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 35,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lg", "ultrafine", "4k", "usb-c", "ergo", "32-inch", "ergonomic"],
    specs: {
      size: "31.5-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS",
      brightness: "350 nits",
      color: "95% DCI-P3",
      ports: "1x USB-C 60W PD, 2x HDMI, 1x DP, 2x USB-A",
      ergonomic: "Ergo stand: extend, retract, swivel, pivot, tilt, height",
      features: "HDR10, AMD FreeSync",
      warranty: "3 years",
    },
  },
  {
    id: "th-029",
    name: "Samsung ViewFinity S80UA",
    brand: "Samsung",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 549.99,
    rating: 4.4,
    review_count: 1892,
    in_stock: true,
    stock_quantity: 67,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["samsung", "viewfinity", "4k", "usb-c", "hdr", "27-inch", "productivity"],
    specs: {
      size: "27-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS",
      brightness: "350 nits",
      color: "99% sRGB, 1 billion colors",
      ports: "1x USB-C 90W PD, HDMI, DP, 3x USB-A",
      features: "HDR10, AMD FreeSync, Eye Saver Mode",
      ergonomic: "Height, tilt, swivel, pivot",
      warranty: "3 years",
    },
  },
  {
    id: "th-030",
    name: "Dell UltraSharp U4323QE",
    brand: "Dell",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 1199.99,
    original_price: 1349.99,
    rating: 4.6,
    review_count: 823,
    in_stock: true,
    stock_quantity: 18,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "ultrasharp", "4k", "usb-c", "large", "43-inch", "quad-screen"],
    specs: {
      size: "42.5-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS",
      brightness: "350 nits",
      color: "100% sRGB, 98% DCI-P3",
      ports: "1x USB-C 90W PD, 5x USB-A, 2x DP, 2x HDMI, RJ45",
      features: "Quad screen split (4x 21.5\" equivalent)",
      ergonomic: "Height, tilt, swivel",
      warranty: "3 years",
    },
  },
  {
    id: "th-031",
    name: "LG 27UP850N-W",
    brand: "LG",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 499.99,
    rating: 4.5,
    review_count: 2456,
    in_stock: true,
    stock_quantity: 52,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lg", "4k", "usb-c", "hdr", "27-inch", "color-accurate"],
    specs: {
      size: "27-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS",
      brightness: "400 nits VESA DisplayHDR 400",
      color: "95% DCI-P3",
      ports: "1x USB-C 90W PD, 2x HDMI, 1x DP, 2x USB-A",
      features: "HDR10, AMD FreeSync, hardware calibration",
      ergonomic: "Height, tilt, pivot",
      warranty: "3 years",
    },
  },
  {
    id: "th-032",
    name: "Samsung ViewFinity S7 U32S70A",
    brand: "Samsung",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 449.99,
    original_price: 549.99,
    rating: 4.3,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 73,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["samsung", "viewfinity", "4k", "32-inch", "freesync", "value"],
    specs: {
      size: "32-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS",
      brightness: "300 nits",
      color: "99% sRGB",
      ports: "2x HDMI, 1x DP",
      features: "HDR10, AMD FreeSync",
      ergonomic: "Height, tilt",
      warranty: "3 years",
    },
  },
  {
    id: "th-033",
    name: "Dell UltraSharp U2520D",
    brand: "Dell",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 449.99,
    rating: 4.4,
    review_count: 2891,
    in_stock: false,
    stock_quantity: 0,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "ultrasharp", "qhd", "usb-c", "25-inch", "compact"],
    specs: {
      size: "25-inch",
      resolution: "2560x1440 QHD",
      panel: "IPS",
      brightness: "350 nits",
      color: "99% sRGB",
      ports: "1x USB-C 90W PD, 3x USB-A, DP, HDMI",
      ergonomic: "Height, pivot, swivel, tilt",
      warranty: "3 years",
    },
  },

  // Ultrawide 34"+ Curved (6)
  {
    id: "th-034",
    name: "LG 38WN95C-W",
    brand: "LG",
    category: "monitor",
    subcategory: "ultrawide_monitor",
    price: 1299.99,
    original_price: 1499.99,
    rating: 4.7,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 22,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lg", "ultrawide", "curved", "144hz", "thunderbolt", "38-inch", "premium"],
    specs: {
      size: "38-inch curved 2300R",
      resolution: "3840x1600 WQHD+",
      panel: "IPS Nano",
      refresh: "144Hz",
      brightness: "450 nits VESA DisplayHDR 600",
      color: "98% DCI-P3",
      ports: "1x Thunderbolt 3 94W PD, 1x DP, 2x HDMI, 2x USB-A",
      features: "HDR600, AMD FreeSync Premium, 1ms GTG",
      ergonomic: "Height, tilt",
      warranty: "3 years",
    },
  },
  {
    id: "th-035",
    name: "Dell UltraSharp U3423WE",
    brand: "Dell",
    category: "monitor",
    subcategory: "ultrawide_monitor",
    price: 1099.99,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 28,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "ultrasharp", "ultrawide", "curved", "usb-c", "ips-black", "productivity"],
    specs: {
      size: "34-inch curved 1900R",
      resolution: "3440x1440 WQHD",
      panel: "IPS Black",
      brightness: "300 nits",
      contrast: "2000:1",
      color: "100% sRGB, 98% DCI-P3",
      ports: "1x USB-C 100W PD, 5x USB-A, 2x DP, 2x HDMI, RJ45",
      features: "KVM, Picture-by-Picture",
      ergonomic: "Height, tilt, swivel",
      warranty: "3 years",
    },
  },
  {
    id: "th-036",
    name: "Samsung Odyssey OLED G8",
    brand: "Samsung",
    category: "monitor",
    subcategory: "ultrawide_monitor",
    price: 1199.99,
    original_price: 1399.99,
    rating: 4.8,
    review_count: 2890,
    in_stock: true,
    stock_quantity: 15,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["samsung", "odyssey", "ultrawide", "curved", "oled", "175hz", "gaming"],
    specs: {
      size: "34-inch curved 1800R",
      resolution: "3440x1440 WQHD",
      panel: "QD-OLED",
      refresh: "175Hz",
      response: "0.1ms GTG",
      brightness: "250 nits (400 peak) VESA DisplayHDR 400 True Black",
      color: "99% DCI-P3",
      ports: "1x Micro HDMI 2.1, 1x Mini DP, 2x USB-C",
      features: "Smart TV apps, Gaming Hub",
      warranty: "3 years",
    },
  },
  {
    id: "th-037",
    name: "LG 34WN80C-B",
    brand: "LG",
    category: "monitor",
    subcategory: "ultrawide_monitor",
    price: 549.99,
    rating: 4.4,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 41,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lg", "ultrawide", "curved", "usb-c", "budget", "34-inch", "productivity"],
    specs: {
      size: "34-inch curved 1800R",
      resolution: "3440x1440 WQHD",
      panel: "IPS",
      brightness: "300 nits",
      color: "99% sRGB",
      ports: "1x USB-C 60W PD, 2x HDMI, 1x DP",
      features: "HDR10, AMD FreeSync",
      ergonomic: "Height, tilt",
      warranty: "3 years",
    },
  },
  {
    id: "th-038",
    name: "Dell UltraSharp U4924DW",
    brand: "Dell",
    category: "monitor",
    subcategory: "ultrawide_monitor",
    price: 1799.99,
    rating: 4.7,
    review_count: 567,
    in_stock: true,
    stock_quantity: 12,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "ultrasharp", "super-ultrawide", "curved", "usb-c", "ips-black", "49-inch"],
    specs: {
      size: "49-inch curved 3800R",
      resolution: "5120x1440 DQHD",
      panel: "IPS Black",
      brightness: "350 nits",
      contrast: "2000:1",
      color: "100% sRGB, 98% DCI-P3",
      ports: "1x USB-C 90W PD, 5x USB-A, 2x DP, 2x HDMI, RJ45",
      features: "Dual 27\" equivalent, KVM, PbP",
      ergonomic: "Height, tilt, swivel",
      warranty: "3 years",
    },
  },
  {
    id: "th-039",
    name: "Samsung ViewFinity S65UA",
    brand: "Samsung",
    category: "monitor",
    subcategory: "ultrawide_monitor",
    price: 499.99,
    original_price: 599.99,
    rating: 4.3,
    review_count: 1456,
    in_stock: true,
    stock_quantity: 38,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["samsung", "viewfinity", "ultrawide", "curved", "usb-c", "100hz", "34-inch"],
    specs: {
      size: "34-inch curved 1000R",
      resolution: "3440x1440 WQHD",
      panel: "VA",
      refresh: "100Hz",
      brightness: "350 nits",
      color: "99% sRGB",
      ports: "1x USB-C 65W PD, HDMI, DP",
      features: "HDR10, AMD FreeSync",
      ergonomic: "Height, tilt, swivel",
      warranty: "3 years",
    },
  },

  // Business Standard 24-27" FHD (6)
  {
    id: "th-040",
    name: "Dell P2422H",
    brand: "Dell",
    category: "monitor",
    subcategory: "standard_monitor",
    price: 229.99,
    rating: 4.5,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 124,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "p-series", "fhd", "business", "24-inch", "ergonomic", "office"],
    specs: {
      size: "24-inch",
      resolution: "1920x1080 FHD",
      panel: "IPS",
      brightness: "250 nits",
      color: "99% sRGB",
      ports: "1x VGA, 1x DP, 1x HDMI, 3x USB-A",
      features: "ComfortView Plus (TUV), 3-sided bezel-less",
      ergonomic: "Height, pivot, swivel, tilt",
      warranty: "3 years",
    },
  },
  {
    id: "th-041",
    name: "HP E24 G5",
    brand: "HP",
    category: "monitor",
    subcategory: "standard_monitor",
    price: 299.99,
    original_price: 349.99,
    rating: 4.4,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 89,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "e-series", "fhd", "business", "usb-c", "24-inch", "ergonomic"],
    specs: {
      size: "24-inch",
      resolution: "1920x1080 FHD",
      panel: "IPS",
      brightness: "300 nits",
      color: "99% sRGB",
      ports: "1x USB-C 65W PD, 1x DP, 1x HDMI, 4x USB-A",
      features: "HP Eye Ease, TUV certified",
      ergonomic: "Height, pivot, swivel, tilt",
      warranty: "3 years",
    },
  },
  {
    id: "th-042",
    name: "Lenovo ThinkVision T24i-30",
    brand: "Lenovo",
    category: "monitor",
    subcategory: "standard_monitor",
    price: 249.99,
    rating: 4.3,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 76,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkvision", "fhd", "business", "usb-c", "24-inch", "ergonomic"],
    specs: {
      size: "24-inch",
      resolution: "1920x1080 FHD",
      panel: "IPS",
      refresh: "75Hz",
      brightness: "250 nits",
      color: "99% sRGB",
      ports: "1x USB-C, 1x DP, 1x HDMI, 4x USB-A",
      features: "Natural Low Blue Light, TUV",
      ergonomic: "Height, pivot, swivel, tilt",
      warranty: "3 years",
    },
  },
  {
    id: "th-043",
    name: "Dell P2722H",
    brand: "Dell",
    category: "monitor",
    subcategory: "standard_monitor",
    price: 299.99,
    rating: 4.5,
    review_count: 4234,
    in_stock: true,
    stock_quantity: 95,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "p-series", "fhd", "business", "27-inch", "ergonomic", "office"],
    specs: {
      size: "27-inch",
      resolution: "1920x1080 FHD",
      panel: "IPS",
      brightness: "300 nits",
      color: "99% sRGB",
      ports: "1x VGA, 1x DP, 1x HDMI, 3x USB-A",
      features: "ComfortView Plus (TUV), 3-sided bezel-less",
      ergonomic: "Height, pivot, swivel, tilt",
      warranty: "3 years",
    },
  },
  {
    id: "th-044",
    name: "HP E27q G5",
    brand: "HP",
    category: "monitor",
    subcategory: "standard_monitor",
    price: 399.99,
    original_price: 449.99,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 62,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "e-series", "qhd", "business", "usb-c", "27-inch", "ergonomic"],
    specs: {
      size: "27-inch",
      resolution: "2560x1440 QHD",
      panel: "IPS",
      brightness: "350 nits",
      color: "99% sRGB",
      ports: "1x USB-C 65W PD, 1x DP, 1x HDMI, 4x USB-A",
      features: "HP Eye Ease, TUV certified",
      ergonomic: "Height, pivot, swivel, tilt",
      warranty: "3 years",
    },
  },
  {
    id: "th-045",
    name: "Lenovo ThinkVision T27h-30",
    brand: "Lenovo",
    category: "monitor",
    subcategory: "standard_monitor",
    price: 449.99,
    rating: 4.4,
    review_count: 1892,
    in_stock: false,
    stock_quantity: 0,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["lenovo", "thinkvision", "qhd", "business", "usb-c", "27-inch", "ergonomic"],
    specs: {
      size: "27-inch",
      resolution: "2560x1440 QHD",
      panel: "IPS",
      brightness: "350 nits",
      color: "99% sRGB",
      ports: "1x USB-C 75W PD, 1x DP, 1x HDMI, 4x USB-A",
      features: "Natural Low Blue Light, Smart Power",
      ergonomic: "Height, pivot, swivel, tilt",
      warranty: "3 years",
    },
  },

  // ==================== TABLETS (15) ====================
  // iPad Pro/Air for Business (6)
  {
    id: "th-046",
    name: "Apple iPad Pro 11-inch M2",
    brand: "Apple",
    category: "tablet",
    subcategory: "professional_tablet",
    price: 999.99,
    rating: 4.8,
    review_count: 4521,
    in_stock: true,
    stock_quantity: 53,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["apple", "ipad", "m2", "cellular", "pro", "11-inch", "stylus", "business"],
    specs: {
      processor: "Apple M2 8-core CPU, 10-core GPU",
      storage: "256GB",
      display: "11-inch Liquid Retina 2388x1668 120Hz ProMotion",
      connectivity: "Wi-Fi 6E + 5G Cellular",
      battery: "Up to 10 hours",
      camera: "12MP Wide + 10MP Ultra Wide (rear), 12MP Center Stage (front)",
      features: "Apple Pencil 2 support, Magic Keyboard compatible",
      weight: "466g",
      warranty: "1 year AppleCare",
    },
  },
  {
    id: "th-047",
    name: "Apple iPad Pro 12.9-inch M2",
    brand: "Apple",
    category: "tablet",
    subcategory: "professional_tablet",
    price: 1499.99,
    original_price: 1699.99,
    rating: 4.9,
    review_count: 3892,
    in_stock: true,
    stock_quantity: 28,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["apple", "ipad", "m2", "cellular", "pro", "xdr", "12.9-inch", "premium"],
    specs: {
      processor: "Apple M2 8-core CPU, 10-core GPU",
      storage: "512GB",
      display: "12.9-inch Liquid Retina XDR 2732x2048 120Hz Mini-LED",
      connectivity: "Wi-Fi 6E + 5G Cellular",
      battery: "Up to 10 hours",
      camera: "12MP Wide + 10MP Ultra Wide + LiDAR (rear), 12MP Center Stage (front)",
      features: "Apple Pencil 2 support, Magic Keyboard compatible",
      weight: "682g",
      warranty: "1 year AppleCare",
    },
  },
  {
    id: "th-048",
    name: "Apple iPad Air M2",
    brand: "Apple",
    category: "tablet",
    subcategory: "professional_tablet",
    price: 749.99,
    rating: 4.7,
    review_count: 5234,
    in_stock: true,
    stock_quantity: 78,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["apple", "ipad", "m2", "air", "lightweight", "11-inch", "value"],
    specs: {
      processor: "Apple M2 8-core CPU, 9-core GPU",
      storage: "256GB",
      display: "11-inch Liquid Retina 2360x1640",
      connectivity: "Wi-Fi 6E",
      battery: "Up to 10 hours",
      camera: "12MP Wide (rear), 12MP Center Stage (front)",
      features: "Apple Pencil Pro support, Magic Keyboard compatible",
      weight: "462g",
      warranty: "1 year AppleCare",
    },
  },
  {
    id: "th-049",
    name: "Apple iPad Pro 11-inch M4",
    brand: "Apple",
    category: "tablet",
    subcategory: "professional_tablet",
    price: 1399.99,
    rating: 4.9,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 19,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["apple", "ipad", "m4", "cellular", "pro", "oled", "latest"],
    specs: {
      processor: "Apple M4 9-core CPU, 10-core GPU",
      storage: "512GB",
      display: "11-inch Ultra Retina XDR 2420x1668 Tandem OLED",
      connectivity: "Wi-Fi 6E + 5G Cellular",
      battery: "Up to 10 hours",
      camera: "12MP Wide (rear), 12MP TrueDepth landscape (front)",
      features: "Apple Pencil Pro support, Magic Keyboard compatible",
      weight: "444g",
      warranty: "1 year AppleCare",
    },
  },
  {
    id: "th-050",
    name: "Apple iPad 10th Generation",
    brand: "Apple",
    category: "tablet",
    subcategory: "professional_tablet",
    price: 649.99,
    original_price: 749.99,
    rating: 4.5,
    review_count: 8234,
    in_stock: true,
    stock_quantity: 112,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["apple", "ipad", "a14", "cellular", "budget", "10.9-inch", "entry-level"],
    specs: {
      processor: "Apple A14 Bionic 6-core CPU, 4-core GPU",
      storage: "256GB",
      display: "10.9-inch Liquid Retina 2360x1640",
      connectivity: "Wi-Fi 6 + 5G Cellular",
      battery: "Up to 10 hours",
      camera: "12MP Wide (rear), 12MP landscape (front)",
      features: "Magic Keyboard Folio support, USB-C",
      weight: "477g",
      warranty: "1 year AppleCare",
    },
  },
  {
    id: "th-051",
    name: "Apple iPad Air 13-inch M2",
    brand: "Apple",
    category: "tablet",
    subcategory: "professional_tablet",
    price: 999.99,
    rating: 4.7,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 34,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["apple", "ipad", "m2", "air", "13-inch", "large-screen"],
    specs: {
      processor: "Apple M2 8-core CPU, 10-core GPU",
      storage: "512GB",
      display: "13-inch Liquid Retina 2732x2048",
      connectivity: "Wi-Fi 6E",
      battery: "Up to 10 hours",
      camera: "12MP Wide (rear), 12MP Center Stage (front)",
      features: "Apple Pencil Pro support, Magic Keyboard compatible",
      weight: "617g",
      warranty: "1 year AppleCare",
    },
  },

  // Surface Pro/Go (5)
  {
    id: "th-052",
    name: "Microsoft Surface Pro 10",
    brand: "Microsoft",
    category: "tablet",
    subcategory: "windows_tablet",
    price: 1599.99,
    original_price: 1799.99,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 27,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["microsoft", "surface", "2-in-1", "windows", "pro", "13-inch", "business"],
    specs: {
      processor: "Intel Core Ultra 7 165U",
      memory: "16GB LPDDR5X",
      storage: "512GB SSD",
      display: "13-inch PixelSense Flow 2880x1920 120Hz",
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      camera: "10MP 4K rear, 12MP 4K front Windows Hello",
      features: "Surface Pen support, Type Cover compatible, NFC",
      weight: "879g",
      warranty: "1 year Microsoft",
    },
  },
  {
    id: "th-053",
    name: "Microsoft Surface Pro 9",
    brand: "Microsoft",
    category: "tablet",
    subcategory: "windows_tablet",
    price: 1299.99,
    rating: 4.5,
    review_count: 4567,
    in_stock: true,
    stock_quantity: 48,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["microsoft", "surface", "2-in-1", "windows", "pro", "13-inch", "value"],
    specs: {
      processor: "Intel Core i7-1255U",
      memory: "16GB LPDDR5",
      storage: "256GB SSD",
      display: "13-inch PixelSense 2880x1920 120Hz",
      os: "Windows 11 Pro",
      battery: "Up to 9 hours",
      camera: "10MP rear, 5MP front Windows Hello",
      features: "Surface Pen support, Type Cover compatible",
      weight: "879g",
      warranty: "1 year Microsoft",
    },
  },
  {
    id: "th-054",
    name: "Microsoft Surface Go 4",
    brand: "Microsoft",
    category: "tablet",
    subcategory: "windows_tablet",
    price: 579.99,
    rating: 4.2,
    review_count: 2341,
    in_stock: true,
    stock_quantity: 67,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["microsoft", "surface", "2-in-1", "windows", "compact", "10.5-inch", "portable"],
    specs: {
      processor: "Intel N200 4-core",
      memory: "8GB LPDDR5",
      storage: "128GB SSD",
      display: "10.5-inch PixelSense 1920x1280",
      os: "Windows 11 Pro",
      battery: "Up to 7.5 hours",
      camera: "8MP rear, 5MP front Windows Hello",
      features: "Surface Pen support, Type Cover compatible",
      weight: "522g",
      warranty: "1 year Microsoft",
    },
  },
  {
    id: "th-055",
    name: "Microsoft Surface Pro 10 5G",
    brand: "Microsoft",
    category: "tablet",
    subcategory: "windows_tablet",
    price: 1899.99,
    rating: 4.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 15,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["microsoft", "surface", "2-in-1", "5g", "arm", "snapdragon", "13-inch"],
    specs: {
      processor: "Snapdragon X Elite X1E-80-100 12-core",
      memory: "16GB LPDDR5X",
      storage: "512GB SSD",
      display: "13-inch PixelSense Flow 2880x1920 120Hz",
      os: "Windows 11 Pro on ARM",
      battery: "Up to 14 hours",
      camera: "10MP 4K rear, 12MP 4K front Windows Hello",
      features: "Surface Pen support, 5G connectivity, NPU AI",
      weight: "858g",
      warranty: "1 year Microsoft",
    },
  },
  {
    id: "th-056",
    name: "Microsoft Surface Pro 8",
    brand: "Microsoft",
    category: "tablet",
    subcategory: "windows_tablet",
    price: 899.99,
    original_price: 1099.99,
    rating: 4.3,
    review_count: 3892,
    in_stock: false,
    stock_quantity: 0,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["microsoft", "surface", "2-in-1", "windows", "value", "previous-gen", "13-inch"],
    specs: {
      processor: "Intel Core i5-1135G7",
      memory: "8GB LPDDR4X",
      storage: "256GB SSD",
      display: "13-inch PixelSense Flow 2880x1920 120Hz",
      os: "Windows 11 Pro",
      battery: "Up to 8 hours",
      camera: "10MP rear, 5MP front Windows Hello",
      features: "Surface Pen support, Type Cover compatible",
      weight: "891g",
      warranty: "1 year Microsoft",
    },
  },

  // Android Tablets - Samsung Galaxy Tab (4)
  {
    id: "th-057",
    name: "Samsung Galaxy Tab S9 Ultra",
    brand: "Samsung",
    category: "tablet",
    subcategory: "android_tablet",
    price: 1299.99,
    original_price: 1399.99,
    rating: 4.7,
    review_count: 1876,
    in_stock: true,
    stock_quantity: 23,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["samsung", "galaxy-tab", "android", "s-pen", "5g", "amoled", "14.6-inch"],
    specs: {
      processor: "Snapdragon 8 Gen 2 for Galaxy",
      memory: "12GB",
      storage: "512GB + microSD up to 1TB",
      display: "14.6-inch Dynamic AMOLED 2X 2960x1848 120Hz",
      battery: "11,200mAh, up to 10 hours",
      camera: "13MP + 8MP Ultra Wide (rear), 12MP + 12MP (front)",
      features: "S Pen included, IP68, DeX mode",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      weight: "732g",
      warranty: "1 year",
    },
  },
  {
    id: "th-058",
    name: "Samsung Galaxy Tab S9+",
    brand: "Samsung",
    category: "tablet",
    subcategory: "android_tablet",
    price: 999.99,
    rating: 4.6,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 41,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["samsung", "galaxy-tab", "android", "s-pen", "amoled", "12.4-inch"],
    specs: {
      processor: "Snapdragon 8 Gen 2 for Galaxy",
      memory: "12GB",
      storage: "256GB + microSD up to 1TB",
      display: "12.4-inch Dynamic AMOLED 2X 2800x1752 120Hz",
      battery: "10,090mAh, up to 10 hours",
      camera: "13MP + 8MP Ultra Wide (rear), 12MP Ultra Wide (front)",
      features: "S Pen included, IP68, DeX mode",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      weight: "586g",
      warranty: "1 year",
    },
  },
  {
    id: "th-059",
    name: "Samsung Galaxy Tab S9 FE+",
    brand: "Samsung",
    category: "tablet",
    subcategory: "android_tablet",
    price: 599.99,
    rating: 4.4,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 86,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["samsung", "galaxy-tab", "android", "s-pen", "value", "12.4-inch"],
    specs: {
      processor: "Exynos 1380",
      memory: "8GB",
      storage: "128GB + microSD up to 1TB",
      display: "12.4-inch LCD 2560x1600 90Hz",
      battery: "10,090mAh, up to 12 hours",
      camera: "8MP (rear), 12MP Ultra Wide (front)",
      features: "S Pen included, IP68, DeX mode",
      connectivity: "Wi-Fi 6, Bluetooth 5.3",
      weight: "627g",
      warranty: "1 year",
    },
  },
  {
    id: "th-060",
    name: "Samsung Galaxy Tab Active5 Pro",
    brand: "Samsung",
    category: "tablet",
    subcategory: "android_tablet",
    price: 749.99,
    rating: 4.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 32,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["samsung", "galaxy-tab", "android", "rugged", "5g", "enterprise", "10.1-inch"],
    specs: {
      processor: "Exynos 1380",
      memory: "6GB",
      storage: "128GB + microSD up to 1TB",
      display: "10.1-inch TFT 1920x1200",
      battery: "4,200mAh replaceable, up to 12 hours",
      camera: "13MP (rear), 5MP (front)",
      features: "IP68, MIL-STD-810H, S Pen included, replaceable battery",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      weight: "433g",
      warranty: "3 years Knox Suite",
    },
  },

  // ==================== ACCESSORIES (25) ====================
  // Mice - Logitech MX, Ergonomic (6)
  {
    id: "th-061",
    name: "Logitech MX Master 3S for Business",
    brand: "Logitech",
    category: "accessory",
    subcategory: "mouse",
    price: 109.99,
    rating: 4.8,
    review_count: 8234,
    in_stock: true,
    stock_quantity: 156,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "mx-master", "mouse", "wireless", "ergonomic", "productivity"],
    specs: {
      sensor: "8000 DPI optical",
      buttons: "7 programmable buttons",
      scroll: "MagSpeed electromagnetic scrolling",
      connectivity: "Logi Bolt USB receiver, Bluetooth Low Energy",
      battery: "Up to 70 days on single charge",
      charging: "USB-C quick charge (1 min = 3 hours)",
      compatibility: "Windows, macOS, Linux, Chrome OS, iPadOS",
      features: "Multi-device Flow, Quiet clicks, Gesture button",
      warranty: "1 year",
    },
  },
  {
    id: "th-062",
    name: "Logitech MX Anywhere 3S for Business",
    brand: "Logitech",
    category: "accessory",
    subcategory: "mouse",
    price: 89.99,
    original_price: 99.99,
    rating: 4.7,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 134,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "mx-anywhere", "mouse", "wireless", "portable", "travel"],
    specs: {
      sensor: "8000 DPI optical, works on any surface including glass",
      buttons: "6 programmable buttons",
      scroll: "MagSpeed electromagnetic scrolling",
      connectivity: "Logi Bolt USB receiver, Bluetooth Low Energy",
      battery: "Up to 70 days on single charge",
      charging: "USB-C quick charge",
      compatibility: "Windows, macOS, Linux, Chrome OS, iPadOS",
      features: "Multi-device, Compact design, Quiet clicks",
      weight: "95g",
      warranty: "1 year",
    },
  },
  {
    id: "th-063",
    name: "Logitech MX Vertical",
    brand: "Logitech",
    category: "accessory",
    subcategory: "mouse",
    price: 109.99,
    rating: 4.5,
    review_count: 4521,
    in_stock: true,
    stock_quantity: 89,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "mx-vertical", "mouse", "wireless", "vertical", "ergonomic"],
    specs: {
      sensor: "4000 DPI optical",
      angle: "57-degree vertical angle for reduced wrist pressure",
      buttons: "4 customizable buttons",
      scroll: "Precision wheel with tilt",
      connectivity: "Logi Bolt USB receiver, Bluetooth Low Energy",
      battery: "Up to 4 months on single charge",
      charging: "USB-C quick charge",
      compatibility: "Windows, macOS, Linux",
      features: "Cursor speed switch, Reduces muscular strain by 10%",
      warranty: "1 year",
    },
  },
  {
    id: "th-064",
    name: "Microsoft Sculpt Ergonomic Mouse",
    brand: "Microsoft",
    category: "accessory",
    subcategory: "mouse",
    price: 59.99,
    rating: 4.4,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 112,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["microsoft", "sculpt", "mouse", "wireless", "ergonomic", "windows"],
    specs: {
      design: "Thumb scoop design for natural wrist position",
      buttons: "4 buttons including Windows button",
      scroll: "4-way scroll wheel",
      connectivity: "2.4GHz wireless USB receiver",
      battery: "Up to 12 months",
      compatibility: "Windows, macOS",
      features: "BlueTrack Technology, Works on virtually any surface",
      warranty: "3 years",
    },
  },
  {
    id: "th-065",
    name: "Logitech M720 Triathlon Multi-Device Mouse",
    brand: "Logitech",
    category: "accessory",
    subcategory: "mouse",
    price: 49.99,
    original_price: 59.99,
    rating: 4.6,
    review_count: 7892,
    in_stock: true,
    stock_quantity: 198,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "m720", "mouse", "wireless", "multi-device", "value"],
    specs: {
      sensor: "1000 DPI optical",
      buttons: "8 customizable buttons",
      scroll: "Hyper-fast scrolling wheel",
      connectivity: "Logi Bolt USB receiver, Bluetooth",
      battery: "24 months on single AA battery",
      compatibility: "Windows, macOS, Linux, Chrome OS",
      features: "Multi-device pairing (3 devices), Easy-Switch",
      warranty: "1 year",
    },
  },
  {
    id: "th-066",
    name: "Razer Pro Click Mini",
    brand: "Razer",
    category: "accessory",
    subcategory: "mouse",
    price: 89.99,
    rating: 4.3,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 67,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["razer", "pro-click", "mouse", "wireless", "portable", "silent"],
    specs: {
      sensor: "16000 DPI 5G optical",
      switches: "Razer Silent Mechanical switches",
      buttons: "7 programmable buttons",
      scroll: "4-way tilt scroll wheel with free spin mode",
      connectivity: "Razer HyperSpeed Wireless, Bluetooth",
      battery: "Up to 725 hours (2.4GHz), 950 hours (BT)",
      compatibility: "Windows, macOS",
      features: "Multi-device connectivity, Productivity dongle",
      weight: "83g",
      warranty: "2 years",
    },
  },

  // Keyboards - Mechanical, Ergonomic, Wireless (6)
  {
    id: "th-067",
    name: "Keychron Q1 Pro",
    brand: "Keychron",
    category: "accessory",
    subcategory: "keyboard",
    price: 199.99,
    rating: 4.7,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 45,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["keychron", "q1-pro", "keyboard", "mechanical", "wireless", "75-percent"],
    specs: {
      layout: "75% (82 keys)",
      case: "Full aluminum CNC machined body",
      switches: "Gateron G Pro (Red/Blue/Brown)",
      hot_swappable: "Yes, 3-pin and 5-pin MX switches",
      connectivity: "Bluetooth 5.1 (up to 3 devices), USB-C wired",
      battery: "4000mAh, up to 200 hours (backlight off)",
      backlight: "RGB south-facing LEDs",
      keycaps: "Double-shot PBT",
      compatibility: "Windows, macOS, Linux (QMK/VIA support)",
      warranty: "1 year",
    },
  },
  {
    id: "th-068",
    name: "Logitech MX Keys S for Business",
    brand: "Logitech",
    category: "accessory",
    subcategory: "keyboard",
    price: 119.99,
    original_price: 139.99,
    rating: 4.6,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 123,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "mx-keys", "keyboard", "wireless", "backlit", "productivity"],
    specs: {
      layout: "Full-size with numpad",
      keys: "Perfect Stroke keys with spherically dished profile",
      smart_keys: "Smart Actions customizable via Logi Options+",
      backlight: "Smart illumination with proximity sensors",
      connectivity: "Logi Bolt USB receiver, Bluetooth Low Energy",
      battery: "Up to 5 months (backlight off), 10 days (on)",
      charging: "USB-C",
      compatibility: "Windows, macOS, Linux, Chrome OS",
      features: "Multi-device Flow, Easy-switch between 3 devices",
      warranty: "1 year",
    },
  },
  {
    id: "th-069",
    name: "Microsoft Sculpt Ergonomic Desktop",
    brand: "Microsoft",
    category: "accessory",
    subcategory: "keyboard",
    price: 129.99,
    rating: 4.5,
    review_count: 4567,
    in_stock: true,
    stock_quantity: 78,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["microsoft", "sculpt", "keyboard", "wireless", "ergonomic", "split"],
    specs: {
      layout: "Split keyset design with cushioned palm rest",
      dome: "Natural arc key layout mimics curved finger shape",
      numpad: "Separate number pad included",
      keys: "Low-profile chiclet keys",
      connectivity: "2.4GHz wireless USB receiver",
      battery: "Up to 36 months (keyboard), 24 months (numpad)",
      compatibility: "Windows, macOS",
      features: "Reverse tilt for neutral wrist position",
      warranty: "3 years",
    },
  },
  {
    id: "th-070",
    name: "Keychron K3 Pro",
    brand: "Keychron",
    category: "accessory",
    subcategory: "keyboard",
    price: 119.99,
    rating: 4.6,
    review_count: 1892,
    in_stock: true,
    stock_quantity: 56,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["keychron", "k3-pro", "keyboard", "mechanical", "wireless", "low-profile"],
    specs: {
      layout: "75% (84 keys)",
      profile: "Ultra-slim 22mm",
      switches: "Gateron low-profile (Red/Blue/Brown)",
      hot_swappable: "Yes, 3-pin MX low-profile switches",
      connectivity: "Bluetooth 5.1 (up to 3 devices), USB-C wired",
      battery: "1550mAh, up to 35 hours",
      backlight: "White backlight",
      keycaps: "Double-shot PBT",
      compatibility: "Windows, macOS, Linux (QMK/VIA support)",
      warranty: "1 year",
    },
  },
  {
    id: "th-071",
    name: "Logitech MX Mechanical",
    brand: "Logitech",
    category: "accessory",
    subcategory: "keyboard",
    price: 169.99,
    original_price: 189.99,
    rating: 4.5,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 89,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "mx-mechanical", "keyboard", "mechanical", "wireless", "tactile"],
    specs: {
      layout: "Full-size with numpad (also TKL available)",
      switches: "Tactile Quiet (Brown), Clicky (Blue), Linear (Red)",
      smart_keys: "Smart Actions customizable",
      backlight: "Smart illumination with proximity sensors",
      connectivity: "Logi Bolt USB receiver, Bluetooth Low Energy",
      battery: "Up to 15 days (backlight on), 10 months (off)",
      charging: "USB-C",
      compatibility: "Windows, macOS, Linux",
      features: "Multi-device, Easy-switch, Aluminum body",
      warranty: "1 year",
    },
  },
  {
    id: "th-072",
    name: "Kinesis Advantage360 Professional",
    brand: "Kinesis",
    category: "accessory",
    subcategory: "keyboard",
    price: 489.99,
    rating: 4.8,
    review_count: 892,
    in_stock: true,
    stock_quantity: 18,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["kinesis", "advantage360", "keyboard", "mechanical", "ergonomic", "split"],
    specs: {
      layout: "Split contoured design with thumb clusters",
      form_factor: "60% split ergonomic",
      switches: "Kailh Box Brown (tactile)",
      hot_swappable: "Yes",
      connectivity: "Bluetooth 5.0 (up to 5 devices), USB-C wired",
      battery: "Rechargeable Li-Po",
      keycaps: "PBT with Dvorak/Colemak legends available",
      compatibility: "Windows, macOS, Linux (QMK programmable)",
      features: "360-degree tenting, 20-degree rotation, Fully programmable",
      warranty: "2 years",
    },
  },

  // Webcams - 4K Business Cameras (4)
  {
    id: "th-073",
    name: "Logitech Brio 4K Pro Webcam",
    brand: "Logitech",
    category: "accessory",
    subcategory: "webcam",
    price: 199.99,
    original_price: 229.99,
    rating: 4.6,
    review_count: 8234,
    in_stock: true,
    stock_quantity: 87,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "brio", "webcam", "4k", "hdr", "windows-hello"],
    specs: {
      resolution: "4K Ultra HD (30fps), 1080p (60fps), 720p (90fps)",
      sensor: "8.3MP Sony STARVIS",
      hdr: "RightLight 3 with HDR for various lighting",
      fov: "Adjustable 65°, 78°, 90° diagonal",
      zoom: "5x digital zoom",
      audio: "Dual integrated omnidirectional mics with noise cancellation",
      connection: "USB-C, USB-A adapter included",
      features: "Windows Hello face authentication, Background replacement",
      warranty: "2 years",
    },
  },
  {
    id: "th-074",
    name: "Logitech MX Brio Ultra HD",
    brand: "Logitech",
    category: "accessory",
    subcategory: "webcam",
    price: 229.99,
    rating: 4.7,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 52,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "mx-brio", "webcam", "4k", "ai-enhanced", "mx-series"],
    specs: {
      resolution: "4K Ultra HD (30fps), 1080p (60fps)",
      sensor: "Sony STARVIS with AI face-based image enhancement",
      fov: "Adjustable 65°, 78°, 90° diagonal",
      show_mode: "Show Mode for desk view",
      audio: "Dual beamforming mics with noise reduction",
      connection: "USB-C",
      features: "Auto light correction, Background blur, Windows Hello",
      compatibility: "Works with Microsoft Teams, Zoom, Google Meet",
      warranty: "2 years",
    },
  },
  {
    id: "th-075",
    name: "Dell UltraSharp 4K Webcam",
    brand: "Dell",
    category: "accessory",
    subcategory: "webcam",
    price: 199.99,
    rating: 4.5,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 64,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "ultrasharp", "webcam", "4k", "ai-framing", "sony-sensor"],
    specs: {
      resolution: "4K Ultra HD (30fps), 1080p (60fps)",
      sensor: "Sony STARVIS 8.3MP CMOS",
      hdr: "Digital Overlap HDR (DOL-HDR)",
      ai_features: "AI auto-framing, Smart exposure",
      fov: "65°, 78°, 90° adjustable",
      audio: "Dual noise-reduction microphones",
      connection: "USB-C",
      features: "Windows Hello, 3D/2D noise reduction, Dell Peripheral Manager",
      mounting: "Monitor mount, tripod thread, magnetic mount",
      warranty: "3 years",
    },
  },
  {
    id: "th-076",
    name: "Poly Studio P5 Professional Webcam",
    brand: "Poly",
    category: "accessory",
    subcategory: "webcam",
    price: 129.99,
    original_price: 149.99,
    rating: 4.4,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 98,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["poly", "studio-p5", "webcam", "1080p", "privacy", "professional"],
    specs: {
      resolution: "1080p Full HD (30fps)",
      fov: "80° diagonal",
      zoom: "4x digital zoom, autofocus",
      audio: "Directional microphone with noise reduction",
      privacy: "Built-in privacy shutter",
      connection: "USB-A (adapter to USB-C included)",
      mounting: "Monitor clip, tripod ready",
      features: "Automatic low-light compensation, Compatible with all platforms",
      warranty: "2 years",
    },
  },

  // Docks - USB-C Hubs, Thunderbolt (5)
  {
    id: "th-077",
    name: "Anker 568 USB-C Docking Station",
    brand: "Anker",
    category: "accessory",
    subcategory: "dock",
    price: 349.99,
    rating: 4.5,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 43,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["anker", "568", "dock", "thunderbolt4", "hub", "multi-port"],
    specs: {
      upstream: "1x Thunderbolt 4 to host (100W PD)",
      video: "2x HDMI 4K@60Hz, 1x DisplayPort 4K@60Hz (triple 4K)",
      usb: "3x USB-A 3.0 5Gbps, 2x USB-C 10Gbps",
      ethernet: "2.5 Gigabit Ethernet",
      audio: "1x 3.5mm audio jack",
      card_reader: "SD 4.0 and microSD UHS-II",
      power_delivery: "100W to host device",
      compatibility: "Thunderbolt 4/3, USB4 laptops",
      warranty: "2 years",
    },
  },
  {
    id: "th-078",
    name: "Dell WD22TB4 Thunderbolt 4 Dock",
    brand: "Dell",
    category: "accessory",
    subcategory: "dock",
    price: 379.99,
    original_price: 429.99,
    rating: 4.6,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 56,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "wd22tb4", "dock", "thunderbolt4", "enterprise", "dell"],
    specs: {
      upstream: "1x Thunderbolt 4 to host",
      power_adapter: "180W (up to 130W to Dell laptop)",
      video: "2x DisplayPort 1.4, 1x HDMI 2.0 (dual 4K@60Hz)",
      usb: "3x USB-C 3.2 Gen 2, 3x USB-A 3.2 Gen 1",
      ethernet: "2.5 Gigabit Ethernet",
      audio: "1x 3.5mm combo audio",
      features: "MAC address pass-through, PXE boot, Wake-on-LAN",
      compatibility: "Thunderbolt 4/3, USB-C laptops",
      warranty: "3 years",
    },
  },
  {
    id: "th-079",
    name: "CalDigit TS4 Thunderbolt 4 Dock",
    brand: "CalDigit",
    category: "accessory",
    subcategory: "dock",
    price: 499.99,
    rating: 4.7,
    review_count: 1876,
    in_stock: true,
    stock_quantity: 31,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["caldigit", "ts4", "dock", "thunderbolt4", "18-port", "mac"],
    specs: {
      upstream: "1x Thunderbolt 4 to host (98W PD)",
      video: "1x DisplayPort 1.4 (8K@30Hz or dual 6K@60Hz via TB downstream)",
      usb: "5x USB-A 3.2, 3x USB-C (2x 10Gbps, 1x Thunderbolt 4)",
      ethernet: "2.5 Gigabit Ethernet",
      audio: "1x 3.5mm combo audio, 1x optical audio",
      card_reader: "SD 4.0 UHS-II",
      features: "Ejector button for safe disconnect, macOS optimized",
      compatibility: "Thunderbolt 4/3, USB4, USB-C laptops",
      warranty: "2 years",
    },
  },
  {
    id: "th-080",
    name: "HP USB-C Dock G5",
    brand: "HP",
    category: "accessory",
    subcategory: "dock",
    price: 249.99,
    rating: 4.4,
    review_count: 2890,
    in_stock: true,
    stock_quantity: 72,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["hp", "usb-c-dock", "dock", "usb-c", "enterprise", "hp"],
    specs: {
      upstream: "1x USB-C to host (100W PD)",
      video: "2x DisplayPort 1.4, 1x HDMI 2.0 (dual 4K@60Hz)",
      usb: "1x USB-C 3.2, 4x USB-A 3.2",
      ethernet: "1x Gigabit Ethernet",
      audio: "1x 3.5mm combo audio",
      features: "MAC address pass-through, PXE boot, Wake-on-LAN",
      compatibility: "USB-C DP Alt Mode laptops",
      warranty: "3 years",
    },
  },
  {
    id: "th-081",
    name: "Anker PowerExpand Elite 13-in-1",
    brand: "Anker",
    category: "accessory",
    subcategory: "dock",
    price: 249.99,
    original_price: 299.99,
    rating: 4.5,
    review_count: 4123,
    in_stock: false,
    stock_quantity: 0,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["anker", "powerexpand", "dock", "thunderbolt3", "hub", "value"],
    specs: {
      upstream: "1x Thunderbolt 3 to host (85W PD)",
      video: "2x HDMI 4K@60Hz (dual 4K)",
      usb: "1x USB-C 3.2, 4x USB-A 3.0",
      ethernet: "1x Gigabit Ethernet",
      audio: "1x 3.5mm combo audio",
      card_reader: "SD 4.0 UHS-II, microSD",
      compatibility: "Thunderbolt 3, USB-C laptops",
      warranty: "2 years",
    },
  },

  // Headsets - Business with Mic (4)
  {
    id: "th-082",
    name: "Sony WH-1000XM5 Business",
    brand: "Sony",
    category: "accessory",
    subcategory: "headset",
    price: 399.99,
    rating: 4.7,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 45,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["sony", "wh-1000xm5", "headset", "wireless", "anc", "calls"],
    specs: {
      type: "Over-ear wireless",
      drivers: "30mm with LDAC",
      anc: "8 microphones for industry-leading noise cancellation",
      battery: "30 hours with ANC, 3 min quick charge = 3 hours",
      charging: "USB-C",
      connectivity: "Bluetooth 5.2, NFC, 3.5mm wired",
      microphones: "8 microphones with AI noise reduction for calls",
      features: "Multipoint connection, Speak-to-Chat, Quick Attention",
      compatibility: "Certified for Google Meet, Microsoft Teams, Zoom",
      warranty: "1 year",
    },
  },
  {
    id: "th-083",
    name: "Jabra Evolve2 65 Flex",
    brand: "Jabra",
    category: "accessory",
    subcategory: "headset",
    price: 329.99,
    original_price: 379.99,
    rating: 4.6,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 67,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["jabra", "evolve2", "headset", "wireless", "anc", "teams-certified"],
    specs: {
      type: "On-ear wireless with folding design",
      drivers: "32mm",
      anc: "Hybrid Active Noise Cancellation (Jabra Advanced ANC)",
      battery: "20 hours talk time (ANC on), 32 hours (off)",
      charging: "USB-C, supports wireless charging",
      connectivity: "Bluetooth 5.2, USB-A/C Link 380 adapter",
      microphones: "6-mic call technology with 80% noise reduction",
      certifications: "Microsoft Teams, Zoom, Google Meet, Amazon Chime",
      features: "Integrated busy light, Fold-and-go design",
      warranty: "2 years",
    },
  },
  {
    id: "th-084",
    name: "Poly Voyager Focus 2 UC",
    brand: "Poly",
    category: "accessory",
    subcategory: "headset",
    price: 279.99,
    rating: 4.5,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 54,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["poly", "voyager", "headset", "wireless", "anc", "uc-certified"],
    specs: {
      type: "Over-ear wireless stereo",
      anc: "Hybrid Adaptive ANC with 3 levels",
      battery: "19 hours talk time (ANC on), 40 hours listen time",
      charging: "USB-C, charging stand included",
      connectivity: "Bluetooth 5.1, USB-A adapter included",
      microphones: "Poly Acoustic Fence technology (blocks background noise)",
      range: "Up to 50m/164ft with BT600 adapter",
      features: "Dynamic mute alert, Smart sensors (auto-answer/pause)",
      warranty: "2 years",
    },
  },
  {
    id: "th-085",
    name: "Logitech Zone Vibe 125",
    brand: "Logitech",
    category: "accessory",
    subcategory: "headset",
    price: 129.99,
    rating: 4.4,
    review_count: 1892,
    in_stock: true,
    stock_quantity: 89,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "zone", "headset", "wireless", "lightweight", "teams-certified"],
    specs: {
      type: "On-ear wireless",
      drivers: "40mm",
      battery: "18 hours talk time, 20 hours listen time",
      charging: "USB-C",
      connectivity: "Bluetooth 5.2, USB-A/C receiver included",
      microphones: "Dual noise-canceling mics with beamforming",
      weight: "125g (ultra-lightweight)",
      features: "Flip-to-mute, Teams certified, Works with all platforms",
      warranty: "2 years",
    },
  },

  // ==================== NETWORKING (15) ====================
  // Enterprise APs - Ubiquiti, Cisco (5)
  {
    id: "th-086",
    name: "Ubiquiti UniFi U6-Pro",
    brand: "Ubiquiti",
    category: "networking",
    subcategory: "access_point",
    price: 159.99,
    rating: 4.7,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 78,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["ubiquiti", "unifi", "access-point", "wifi6", "enterprise", "unifi"],
    specs: {
      wifi_standard: "Wi-Fi 6 (802.11ax)",
      bands: "Dual-band 2.4GHz + 5GHz",
      throughput: "5.3 Gbps aggregate",
      mimo: "4x4 MU-MIMO on both bands",
      clients: "Supports 300+ concurrent clients",
      coverage: "Up to 140m² (1,500 sq ft)",
      power: "PoE+ (802.3at)",
      mounting: "Ceiling/wall mount included",
      management: "UniFi Network Controller (cloud or local)",
      warranty: "1 year",
    },
  },
  {
    id: "th-087",
    name: "Ubiquiti UniFi U6-Enterprise",
    brand: "Ubiquiti",
    category: "networking",
    subcategory: "access_point",
    price: 379.99,
    original_price: 429.99,
    rating: 4.8,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 34,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["ubiquiti", "unifi", "access-point", "wifi6e", "enterprise", "tri-band"],
    specs: {
      wifi_standard: "Wi-Fi 6E (802.11ax)",
      bands: "Tri-band 2.4GHz + 5GHz + 6GHz",
      throughput: "10.8 Gbps aggregate",
      mimo: "4x4 MU-MIMO on all bands",
      clients: "Supports 600+ concurrent clients",
      coverage: "Up to 140m² (1,500 sq ft)",
      uplink: "2.5GbE",
      power: "PoE++ (802.3bt)",
      mounting: "Ceiling/wall mount included",
      warranty: "1 year",
    },
  },
  {
    id: "th-088",
    name: "Cisco Catalyst 9136",
    brand: "Cisco",
    category: "networking",
    subcategory: "access_point",
    price: 1495.00,
    rating: 4.6,
    review_count: 567,
    in_stock: true,
    stock_quantity: 15,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["cisco", "catalyst", "access-point", "wifi6e", "enterprise", "cisco"],
    specs: {
      wifi_standard: "Wi-Fi 6E (802.11ax)",
      bands: "Tri-band 2.4GHz + 5GHz + 6GHz",
      throughput: "10.8 Gbps aggregate",
      mimo: "4x4 MU-MIMO with 16 spatial streams",
      uplink: "2.5GbE/5GbE Multigigabit",
      features: "CleanAir Pro (interference detection), Cisco DNA support",
      management: "Cisco Catalyst Center, DNA Essentials",
      power: "PoE++ (802.3bt)",
      mounting: "Ceiling/wall mount included",
      warranty: "Limited lifetime",
    },
  },
  {
    id: "th-089",
    name: "Ubiquiti UniFi U7-Pro",
    brand: "Ubiquiti",
    category: "networking",
    subcategory: "access_point",
    price: 219.99,
    rating: 4.8,
    review_count: 892,
    in_stock: true,
    stock_quantity: 42,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["ubiquiti", "unifi", "access-point", "wifi7", "enterprise", "latest"],
    specs: {
      wifi_standard: "Wi-Fi 7 (802.11be)",
      bands: "Tri-band with 6GHz support",
      throughput: "9.3 Gbps aggregate",
      mimo: "4x4 MIMO on all bands",
      features: "320MHz channel width, 4K-QAM, MLO (Multi-Link Operation)",
      uplink: "2.5GbE",
      power: "PoE++ (802.3bt)",
      mounting: "Ceiling/wall mount included",
      management: "UniFi Network Controller",
      warranty: "1 year",
    },
  },
  {
    id: "th-090",
    name: "Cisco Catalyst 9117",
    brand: "Cisco",
    category: "networking",
    subcategory: "access_point",
    price: 895.00,
    rating: 4.5,
    review_count: 734,
    in_stock: true,
    stock_quantity: 23,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["cisco", "catalyst", "access-point", "wifi6", "enterprise", "cisco"],
    specs: {
      wifi_standard: "Wi-Fi 6 (802.11ax)",
      bands: "Dual-band 2.4GHz + 5GHz",
      throughput: "5.9 Gbps aggregate",
      mimo: "4x4 MU-MIMO with 8 spatial streams",
      uplink: "2.5GbE Multigigabit",
      features: "OFDMA, MU-MIMO, Cisco DNA support",
      management: "Cisco Catalyst Center, DNA Essentials",
      power: "PoE+ (802.3at) or PoE++ (802.3bt)",
      mounting: "Ceiling/wall mount included",
      warranty: "Limited lifetime",
    },
  },

  // Switches - Managed 8-48 port (5)
  {
    id: "th-091",
    name: "Cisco Catalyst 9300-24P",
    brand: "Cisco",
    category: "networking",
    subcategory: "switch",
    price: 4295.00,
    original_price: 4795.00,
    rating: 4.7,
    review_count: 456,
    in_stock: true,
    stock_quantity: 12,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["cisco", "catalyst", "switch", "managed", "24-port", "poe", "layer3"],
    specs: {
      ports: "24x Gigabit Ethernet RJ45",
      poe: "PoE+ with 445W power budget",
      uplink: "4x 1/10/25GbE SFP28 fixed uplinks",
      switching_capacity: "448 Gbps",
      layer: "Layer 3 with advanced routing",
      stacking: "StackWise-480 (up to 8 switches)",
      management: "Cisco DNA Essentials or Advantage",
      features: "VXLAN, EVPN, mDNS gateway, flexible netflow",
      warranty: "Limited lifetime with EFA",
    },
  },
  {
    id: "th-092",
    name: "Ubiquiti UniFi Switch Pro 48 PoE",
    brand: "Ubiquiti",
    category: "networking",
    subcategory: "switch",
    price: 1199.99,
    rating: 4.6,
    review_count: 1892,
    in_stock: true,
    stock_quantity: 28,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["ubiquiti", "unifi", "switch", "managed", "48-port", "poe", "10gbe"],
    specs: {
      ports: "48x Gigabit Ethernet RJ45",
      poe: "PoE+ with 600W power budget",
      sfp: "4x 10GbE SFP+ uplinks",
      switching_capacity: "140 Gbps",
      layer: "Layer 3 features",
      fans: "1x hot-swappable fan",
      power: "Internal 650W PSU, RPS support",
      management: "UniFi Network Controller",
      features: "VLAN, RSTP, IGMP Snooping, QoS",
      warranty: "1 year",
    },
  },
  {
    id: "th-093",
    name: "Netgear M4300-8X8F",
    brand: "Netgear",
    category: "networking",
    subcategory: "switch",
    price: 1499.99,
    rating: 4.4,
    review_count: 567,
    in_stock: true,
    stock_quantity: 19,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["netgear", "m4300", "switch", "managed", "10gbe", "layer3"],
    specs: {
      ports: "8x 10GBASE-T RJ45 + 8x SFP+",
      switching_capacity: "320 Gbps",
      layer: "Layer 3 with static and dynamic routing",
      stacking: "Yes, up to 8 switches",
      management: "Web GUI, CLI, SNMP, NETGEAR Insight",
      features: "VLAN, ACL, QoS, IPv6 support",
      power: "Dual hot-swappable PSU",
      noise: "Whisper-quiet design",
      warranty: "Lifetime",
    },
  },
  {
    id: "th-094",
    name: "Ubiquiti UniFi Switch Lite 8 PoE",
    brand: "Ubiquiti",
    category: "networking",
    subcategory: "switch",
    price: 109.99,
    rating: 4.5,
    review_count: 4234,
    in_stock: true,
    stock_quantity: 87,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["ubiquiti", "unifi", "switch", "managed", "8-port", "poe", "fanless"],
    specs: {
      ports: "8x Gigabit Ethernet RJ45",
      poe: "PoE+ with 52W budget (ports 1-4)",
      sfp: "1x SFP uplink",
      switching_capacity: "16 Gbps",
      fans: "Fanless (silent operation)",
      management: "UniFi Network Controller",
      features: "VLAN, RSTP, IGMP Snooping, QoS",
      warranty: "1 year",
    },
  },
  {
    id: "th-095",
    name: "Cisco Catalyst 9200L-48P-4X",
    brand: "Cisco",
    category: "networking",
    subcategory: "switch",
    price: 5295.00,
    rating: 4.6,
    review_count: 345,
    in_stock: true,
    stock_quantity: 8,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["cisco", "catalyst", "switch", "managed", "48-port", "poe", "10gbe"],
    specs: {
      ports: "48x Gigabit Ethernet RJ45",
      poe: "PoE+ with 370W power budget",
      uplink: "4x 10GbE SFP+ fixed uplinks",
      switching_capacity: "176 Gbps",
      layer: "Layer 3 with OSPF, EIGRP stub, RIP",
      stacking: "StackWise-80 (up to 8 switches)",
      management: "Cisco DNA Essentials or Advantage",
      features: "VXLAN, Flexible NetFlow, ETA",
      warranty: "Limited lifetime with EFA",
    },
  },

  // Routers - Business Firewall (5)
  {
    id: "th-096",
    name: "TP-Link Omada ER605",
    brand: "TP-Link",
    category: "networking",
    subcategory: "router",
    price: 59.99,
    rating: 4.4,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 134,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["tp-link", "omada", "router", "vpn", "sdwan", "smb"],
    specs: {
      wan_ports: "1x Gigabit WAN + 2x Gigabit WAN/LAN (load balance)",
      lan_ports: "1x Gigabit LAN",
      vpn: "IPsec, PPTP, L2TP, OpenVPN",
      ipsec_throughput: "41.5 Mbps",
      sessions: "16,000 concurrent sessions",
      management: "Omada SDN Controller, Web GUI, App",
      features: "Load balance, failover, policy routing, firewall",
      power: "12V DC adapter",
      warranty: "3 years",
    },
  },
  {
    id: "th-097",
    name: "Ubiquiti UniFi Dream Machine Pro",
    brand: "Ubiquiti",
    category: "networking",
    subcategory: "router",
    price: 379.99,
    original_price: 429.99,
    rating: 4.6,
    review_count: 2890,
    in_stock: true,
    stock_quantity: 52,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["ubiquiti", "unifi", "router", "security-gateway", "10gbe", "all-in-one"],
    specs: {
      wan: "1x 10GbE RJ45 WAN",
      lan: "8x Gigabit RJ45 LAN ports",
      sfp: "1x 10GbE SFP+",
      ids_ips: "3.5 Gbps IDS/IPS throughput",
      vpn: "Site-to-site and client VPN",
      unifi_apps: "Network, Protect, Access, Talk",
      storage: "3.5\" HDD bay for NVR (Protect)",
      management: "UniFi Network Controller (built-in)",
      power: "Internal PSU, optional RPS",
      warranty: "1 year",
    },
  },
  {
    id: "th-098",
    name: "Cisco Meraki MX68CW",
    brand: "Cisco",
    category: "networking",
    subcategory: "router",
    price: 1295.00,
    rating: 4.7,
    review_count: 892,
    in_stock: true,
    stock_quantity: 21,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["cisco", "meraki", "router", "firewall", "cloud-managed", "lte"],
    specs: {
      wan: "2x Gigabit Ethernet (failover/load balance)",
      lan: "8x Gigabit Ethernet (PoE available)",
      cellular: "Integrated CAT6 LTE modem",
      wifi: "Wi-Fi 6 (802.11ax) built-in",
      firewall_throughput: "450 Mbps stateful",
      vpn: "Auto VPN (site-to-site), Client VPN",
      management: "Meraki cloud dashboard",
      features: "Layer 7 application filtering, content filtering, SD-WAN",
      licensing: "Requires Meraki license",
      warranty: "Limited lifetime with EFA",
    },
  },
  {
    id: "th-099",
    name: "Fortinet FortiGate 60F",
    brand: "Fortinet",
    category: "networking",
    subcategory: "router",
    price: 595.00,
    rating: 4.5,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 38,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["fortinet", "fortigate", "firewall", "ngfw", "sdwan", "enterprise"],
    specs: {
      ports: "5x GE RJ45 (including 1x WAN)",
      firewall_throughput: "10 Gbps",
      ips_throughput: "1.4 Gbps",
      ngfw_throughput: "1 Gbps",
      threat_protection: "700 Mbps",
      vpn: "IPsec/SSL VPN with 200+ tunnels",
      sessions: "700,000 concurrent sessions",
      management: "FortiOS, FortiCloud, FortiManager",
      features: "UTM, SD-WAN, Zero Trust Network Access",
      support: "1 year FortiCare 24x7 included",
      warranty: "1 year",
    },
  },
  {
    id: "th-100",
    name: "Palo Alto PA-440",
    brand: "Palo Alto",
    category: "networking",
    subcategory: "router",
    price: 2995.00,
    rating: 4.8,
    review_count: 423,
    in_stock: true,
    stock_quantity: 14,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["palo-alto", "pa-series", "firewall", "ngfw", "enterprise", "ml-security"],
    specs: {
      ports: "5x GE RJ45 (including 1x PoE), 1x console",
      firewall_throughput: "3.2 Gbps",
      threat_prevention: "3 Gbps",
      sessions: "100,000 concurrent sessions",
      new_sessions: "7,200 per second",
      vpn: "IPsec/SSL VPN",
      management: "PAN-OS, Panorama, Cloud NGFW",
      features: "ML-powered threat detection, URL filtering, DNS security",
      power: "PoE capable on port 1",
      warranty: "1 year hardware",
    },
  },

  // ==================== BONUS: 5 ADDITIONAL PRODUCTS ====================
  {
    id: "th-101",
    name: "Dell Precision 5480",
    brand: "Dell",
    category: "laptop",
    subcategory: "workstation",
    price: 2799.99,
    rating: 4.6,
    review_count: 312,
    in_stock: true,
    stock_quantity: 17,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["dell", "precision", "workstation", "compact", "nvidia", "mobile", "14-inch"],
    specs: {
      processor: "Intel Core i7-13800H 14-core",
      graphics: "NVIDIA RTX A1000 6GB",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "14-inch FHD+ (1920x1200) IPS 500 nits",
      os: "Windows 11 Pro for Workstations",
      battery: "Up to 8 hours",
      ports: "2x Thunderbolt 4, 1x USB-A, SD reader, HDMI 2.1",
      weight: "1.59 kg",
      warranty: "3 years ProSupport",
    },
  },
  {
    id: "th-102",
    name: "Logitech MK850 Performance Wireless Combo",
    brand: "Logitech",
    category: "accessory",
    subcategory: "keyboard",
    price: 99.99,
    original_price: 119.99,
    rating: 4.5,
    review_count: 9234,
    in_stock: true,
    stock_quantity: 156,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["logitech", "mk850", "keyboard", "mouse", "combo", "wireless"],
    specs: {
      keyboard_layout: "Full-size with cushioned palm rest",
      keyboard_keys: "Logitech PerfectStroke with curved keyframe",
      mouse_sensor: "1000 DPI optical",
      mouse_buttons: "8 buttons including hyper-fast scroll",
      connectivity: "Logi Bolt USB receiver, Bluetooth",
      battery: "24 months (keyboard), 12 months (mouse)",
      compatibility: "Windows, macOS, Chrome OS",
      features: "Multi-device (3 devices), Easy-switch, FN swap",
      warranty: "1 year",
    },
  },
  {
    id: "th-103",
    name: "BenQ PD3220U DesignVue",
    brand: "BenQ",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 899.99,
    rating: 4.6,
    review_count: 876,
    in_stock: true,
    stock_quantity: 24,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["benq", "designvue", "4k", "thunderbolt3", "design", "kvm", "creator"],
    specs: {
      size: "31.5-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS",
      brightness: "350 nits",
      color: "100% sRGB, 100% Rec.709, 95% DCI-P3",
      hdr: "HDR10 support",
      ports: "2x Thunderbolt 3 (85W PD), 2x HDMI 2.0, 1x DP 1.4, 3x USB-A",
      features: "KVM switch, Hotkey Puck G2, CAD/CAM mode, Animation mode",
      ergonomic: "Height, tilt, swivel, pivot",
      warranty: "3 years",
    },
  },
  {
    id: "th-104",
    name: "Aruba Instant On AP25",
    brand: "Aruba",
    category: "networking",
    subcategory: "access_point",
    price: 299.99,
    rating: 4.5,
    review_count: 678,
    in_stock: true,
    stock_quantity: 45,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["aruba", "instant-on", "access-point", "wifi6", "smb", "hpe"],
    specs: {
      wifi_standard: "Wi-Fi 6 (802.11ax)",
      bands: "Dual-band 2.4GHz + 5GHz",
      throughput: "5.4 Gbps aggregate",
      mimo: "2x2 MU-MIMO on both bands",
      clients: "Supports 256+ concurrent clients",
      coverage: "Medium density environments",
      power: "PoE (802.3af) or DC adapter",
      mounting: "Ceiling/wall/table mount included",
      management: "Aruba Instant On mobile app/cloud",
      warranty: "Limited lifetime",
    },
  },
  {
    id: "th-105",
    name: "Asus ProArt PA279CRV",
    brand: "Asus",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 549.99,
    original_price: 599.99,
    rating: 4.7,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 31,
    trust_level: "trusted",
    retailer: "TechHub",
    tags: ["asus", "proart", "4k", "usb-c", "creator", "color-accurate", "calman"],
    specs: {
      size: "27-inch",
      resolution: "3840x2160 UHD",
      panel: "IPS",
      brightness: "400 nits VESA DisplayHDR 400",
      color: "99% DCI-P3, 99% Adobe RGB, Calman Verified",
      ports: "1x USB-C 96W PD, 2x HDMI 2.0, 1x DP 1.4, 4x USB-A",
      features: "ProArt Preset, ProArt Palette, QuickFit Plus",
      ergonomic: "Height, tilt, swivel, pivot",
      warranty: "3 years",
    },
  },
];

export function getAllProducts(): Product[] {
  return products;
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter((p) => p.brand.toLowerCase() === brand.toLowerCase());
}

export function getProductsByTrustLevel(level: string): Product[] {
  return products.filter((p) => p.trust_level === level);
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.tags.some((tag) => tag.toLowerCase().includes(lowercaseQuery))
  );
}

export function getInStockProducts(): Product[] {
  return products.filter((p) => p.in_stock);
}

export function getOnSaleProducts(): Product[] {
  return products.filter((p) => p.original_price !== undefined);
}

export const productCount = products.length;
