/**
 * TechHub Products - B2B Electronics Catalog
 * 
 * THIS IS A SAMPLE FILE WITH 10 PRODUCTS.
 * 
 * TO GENERATE 100+ PRODUCTS:
 * 1. Copy the generation prompt from: ./product-generation-prompt.md
 * 2. Use an LLM (Claude, GPT, etc.) to generate products
 * 3. Replace this file contents with the generated products
 */

import { Product } from "./types.js";

export const products: Product[] = [
  {
    id: "th-001",
    name: "MacBook Pro 14\" M3 Pro",
    brand: "Apple",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1999,
    original_price: 2199,
    rating: 4.8,
    review_count: 1247,
    in_stock: true,
    stock_quantity: 45,
    tags: ["apple", "macbook", "laptop", "m3", "business", "professional", "14-inch"],
    specs: {
      processor: "Apple M3 Pro 11-core CPU",
      memory: "18GB unified memory",
      storage: "512GB SSD",
      display: "14.2-inch Liquid Retina XDR",
      battery: "Up to 18 hours",
      ports: "3x Thunderbolt 4, HDMI, SD card",
      weight: "1.61 kg",
      warranty: "1 year",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-002",
    name: "Dell Latitude 5540",
    brand: "Dell",
    category: "laptop",
    subcategory: "business_laptop",
    price: 1299,
    rating: 4.5,
    review_count: 892,
    in_stock: true,
    stock_quantity: 67,
    tags: ["dell", "latitude", "laptop", "business", "15-inch", "intel", "vpro"],
    specs: {
      processor: "Intel Core i7-1365U",
      memory: "16GB DDR4",
      storage: "512GB NVMe SSD",
      display: "15.6-inch FHD (1920x1080)",
      battery: "Up to 10 hours",
      ports: "2x USB-C, 2x USB-A, HDMI, RJ45",
      weight: "1.79 kg",
      warranty: "3 years ProSupport",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-003",
    name: "iPad Pro 12.9\" M2",
    brand: "Apple",
    category: "tablet",
    subcategory: "professional_tablet",
    price: 1099,
    rating: 4.7,
    review_count: 2156,
    in_stock: true,
    stock_quantity: 32,
    tags: ["apple", "ipad", "tablet", "m2", "12.9-inch", "professional", "stylus"],
    specs: {
      processor: "Apple M2 chip",
      memory: "8GB RAM",
      storage: "128GB",
      display: "12.9-inch Liquid Retina XDR",
      battery: "Up to 10 hours",
      camera: "12MP Wide + 10MP Ultra Wide",
      connectivity: "Wi-Fi 6E, 5G optional",
      weight: "682g",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-004",
    name: "Samsung Galaxy Tab S9 Ultra",
    brand: "Samsung",
    category: "tablet",
    subcategory: "android_tablet",
    price: 1199,
    rating: 4.5,
    review_count: 734,
    in_stock: true,
    stock_quantity: 28,
    tags: ["samsung", "galaxy", "tab", "tablet", "android", "14.6-inch", "oled", "s-pen"],
    specs: {
      processor: "Snapdragon 8 Gen 2",
      memory: "12GB RAM",
      storage: "256GB + microSD",
      display: "14.6-inch Dynamic AMOLED 2X",
      battery: "11,200mAh",
      camera: "13MP + 8MP dual rear",
      connectivity: "Wi-Fi 7, 5G optional",
      weight: "732g",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-005",
    name: "Dell UltraSharp U2723QE",
    brand: "Dell",
    category: "monitor",
    subcategory: "4k_monitor",
    price: 579,
    original_price: 649,
    rating: 4.6,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 89,
    tags: ["dell", "ultrasharp", "monitor", "4k", "27-inch", "usb-c", "ips"],
    specs: {
      display: "27-inch 4K UHD (3840x2160)",
      panel: "IPS Black technology",
      brightness: "400 nits",
      contrast: "2000:1",
      color: "100% sRGB, 98% DCI-P3",
      ports: "1x USB-C 90W, 5x USB-A, RJ45, DP, HDMI",
      ergonomic: "Height, pivot, swivel, tilt adjustable",
      warranty: "3 years",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-006",
    name: "LG 34WN80C-B UltraWide",
    brand: "LG",
    category: "monitor",
    subcategory: "ultrawide_monitor",
    price: 449,
    rating: 4.4,
    review_count: 2234,
    in_stock: true,
    stock_quantity: 54,
    tags: ["lg", "monitor", "ultrawide", "34-inch", "curved", "usb-c", "productivity"],
    specs: {
      display: "34-inch UltraWide QHD (3440x1440)",
      panel: "IPS",
      curvature: "1800R",
      brightness: "300 nits",
      color: "99% sRGB",
      ports: "1x USB-C 60W, 2x HDMI, 1x DisplayPort",
      features: "HDR10, AMD FreeSync",
      ergonomic: "Height, tilt adjustable",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-007",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "accessory",
    subcategory: "mouse",
    price: 99,
    rating: 4.8,
    review_count: 8934,
    in_stock: true,
    stock_quantity: 156,
    tags: ["logitech", "mx-master", "mouse", "wireless", "ergonomic", "productivity"],
    specs: {
      sensor: "8000 DPI optical sensor",
      buttons: "7 programmable buttons",
      scroll: "MagSpeed electromagnetic scrolling",
      connectivity: "Bluetooth, USB receiver",
      battery: "70 days on single charge",
      charging: "USB-C quick charge",
      compatibility: "Windows, macOS, Linux, iPadOS",
      warranty: "1 year",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-008",
    name: "Keychron K2 Pro Mechanical Keyboard",
    brand: "Keychron",
    category: "accessory",
    subcategory: "keyboard",
    price: 109,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 78,
    tags: ["keychron", "keyboard", "mechanical", "wireless", "75-percent", "hot-swappable"],
    specs: {
      layout: "75% compact (84 keys)",
      switches: "Gateron G Pro (Red/Blue/Brown)",
      hot_swappable: "Yes, 3-pin and 5-pin",
      connectivity: "Bluetooth 5.1, USB-C wired",
      battery: "4000mAh, up to 200 hours",
      backlight: "RGB south-facing LEDs",
      compatibility: "Windows, macOS, Linux",
      keycaps: "Double-shot PBT",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-009",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "accessory",
    subcategory: "headphones",
    price: 348,
    original_price: 399,
    rating: 4.6,
    review_count: 5621,
    in_stock: true,
    stock_quantity: 92,
    tags: ["sony", "wh-1000xm5", "headphones", "noise-cancelling", "wireless", "premium"],
    specs: {
      type: "Over-ear wireless headphones",
      drivers: "30mm dynamic drivers",
      anc: "Industry-leading noise cancellation",
      battery: "30 hours with ANC on",
      charging: "USB-C, 3 min = 3 hours",
      connectivity: "Bluetooth 5.2, NFC, 3.5mm",
      microphones: "8 microphones for calls",
      features: "Multipoint connection, LDAC, DSEE Extreme",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
  {
    id: "th-010",
    name: "Anker 575 USB-C Docking Station",
    brand: "Anker",
    category: "accessory",
    subcategory: "dock",
    price: 249,
    rating: 4.5,
    review_count: 1876,
    in_stock: true,
    stock_quantity: 43,
    tags: ["anker", "dock", "usb-c", "docking-station", "13-in-1", "triple-display"],
    specs: {
      upstream: "1x USB-C to host (85W PD)",
      video: "2x HDMI 4K@60Hz, 1x DisplayPort 4K@60Hz",
      usb: "3x USB-A 3.0, 2x USB-C 3.0",
      ethernet: "1x Gigabit Ethernet",
      audio: "1x 3.5mm audio jack",
      card_reader: "SD and microSD UHS-II",
      power_delivery: "85W to host device",
      compatibility: "USB-C laptops, Thunderbolt 3/4",
    },
    retailer: "TechHub",
    trust_level: "trusted",
  },
];

// Export count for logging
export const productCount = products.length;
