/**
 * IoTMarket Products - IoT and Maker Electronics (Untrusted)
 * AliExpress/eBay-style marketplace with generic brands, clones, and varied availability
 * 105 products across 6 categories
 */

import { Product } from "./types.js";

export const products: Product[] = [
  // ========== MICROCONTROLLERS (20 products) ==========

  // Raspberry Pi Variants (6)
  {
    id: "iot-001",
    name: "Raspberry Pi 5 8GB Bulk Pack (OEM Packaging)",
    brand: "Generic",
    category: "microcontroller",
    subcategory: "single_board_computer",
    price: 89,
    original_price: 129,
    rating: 3.8,
    review_count: 234,
    in_stock: true,
    stock_quantity: 45,
    tags: ["raspberry-pi", "rpi5", "8gb", "clone", "bulk", "sbc", "pi-clone"],
    specs: {
      processor: "BCM2712-compatible 2.4GHz quad-core",
      memory: "8GB LPDDR4X",
      storage: "MicroSD card slot",
      connectivity: "Dual-band Wi-Fi 6, Bluetooth 5.0, Gigabit Ethernet",
      ports: "2x HDMI 4K60, 2x USB 3.0, 2x USB 2.0",
      power: "USB-C 5V 5A",
      gpio: "40-pin GPIO header",
      notes: "Compatible case available separately",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-002",
    name: "Raspberry Pi 4 Model B 4GB (Compatible Board)",
    brand: "DAOKI",
    category: "microcontroller",
    subcategory: "single_board_computer",
    price: 45,
    original_price: 65,
    rating: 3.6,
    review_count: 567,
    in_stock: true,
    stock_quantity: 78,
    tags: ["raspberry-pi", "rpi4", "4gb", "daoki", "compatible", "sbc"],
    specs: {
      processor: "BCM2711 1.5GHz quad-core Cortex-A72",
      memory: "4GB LPDDR4",
      storage: "MicroSD card slot",
      connectivity: "Dual-band Wi-Fi, Bluetooth 5.0, Gigabit Ethernet",
      ports: "2x HDMI, 4x USB, GPIO header",
      power: "USB-C 5V 3A",
      features: "4K video decode, H.265",
      notes: "Third-party compatible board",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-003",
    name: "Raspberry Pi Zero 2 W Clone (5-Pack)",
    brand: "KeeYees",
    category: "microcontroller",
    subcategory: "compact_sbc",
    price: 35,
    rating: 3.4,
    review_count: 89,
    in_stock: false,
    stock_quantity: 0,
    tags: ["raspberry-pi", "pi-zero", "clone", "5-pack", "compact", "bulk"],
    specs: {
      processor: "1GHz quad-core (RP3A0-compatible)",
      memory: "512MB RAM",
      connectivity: "2.4GHz Wi-Fi, Bluetooth 4.2",
      ports: "Mini HDMI, Micro USB OTG, Micro USB power",
      storage: "MicroSD slot",
      gpio: "40-pin HAT-compatible",
      power: "5V 2.5A",
      package: "5 boards per pack",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-004",
    name: "Raspberry Pi 3 Model B+ Compatible (3-Pack)",
    brand: "HiLetgo",
    category: "microcontroller",
    subcategory: "single_board_computer",
    price: 55,
    original_price: 75,
    rating: 3.7,
    review_count: 312,
    in_stock: true,
    stock_quantity: 23,
    tags: ["raspberry-pi", "rpi3", "hiletgo", "3-pack", "legacy", "compatible"],
    specs: {
      processor: "BCM2837B0 1.4GHz quad-core",
      memory: "1GB LPDDR2",
      connectivity: "2.4/5GHz Wi-Fi, Bluetooth 4.2, Gigabit Ethernet",
      ports: "4x USB 2.0, HDMI, GPIO",
      storage: "MicroSD slot",
      power: "5V 2.5A micro USB",
      gpio: "40-pin header",
      package: "3 boards per pack",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-005",
    name: "Raspberry Pi Compute Module 4 Compatible 8GB",
    brand: "Generic",
    category: "microcontroller",
    subcategory: "compute_module",
    price: 65,
    rating: 3.2,
    review_count: 45,
    in_stock: true,
    stock_quantity: 12,
    tags: ["raspberry-pi", "cm4", "compute-module", "8gb", "industrial", "oem"],
    specs: {
      processor: "BCM2711 1.5GHz quad-core",
      memory: "8GB LPDDR4",
      storage: "eMMC 32GB onboard",
      connectivity: "Wi-Fi 6, Bluetooth 5.0",
      interface: "200-pin DDR2 SODIMM",
      video: "Dual HDMI 4K",
      pcie: "PCIe 2.0 x1 lane",
      form_factor: "55mm x 40mm",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-006",
    name: "Raspberry Pi 5 4GB Budget Version (No Accessories)",
    brand: "DAOKI",
    category: "microcontroller",
    subcategory: "single_board_computer",
    price: 52,
    original_price: 79,
    rating: 3.5,
    review_count: 178,
    in_stock: true,
    stock_quantity: 34,
    tags: ["raspberry-pi", "rpi5", "4gb", "budget", "bare-board", "daoki"],
    specs: {
      processor: "BCM2712-compatible 2.4GHz quad-core",
      memory: "4GB LPDDR4X",
      storage: "MicroSD slot only",
      connectivity: "Wi-Fi 6, Bluetooth 5.0, Gigabit Ethernet",
      ports: "2x HDMI 4K, 2x USB 3.0, 2x USB 2.0",
      power: "USB-C 5V 5A",
      gpio: "40-pin GPIO",
      package: "Board only, no cables",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Arduino Clones (5)
  {
    id: "iot-007",
    name: "Arduino Uno R3 Compatible Board CH340 Chip (3-Pack)",
    brand: "HiLetgo",
    category: "microcontroller",
    subcategory: "development_board",
    price: 18,
    rating: 4.0,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 156,
    tags: ["arduino", "uno", "r3", "clone", "ch340", "3-pack", "compatible"],
    specs: {
      microcontroller: "ATmega328P",
      clock: "16MHz",
      io: "14 digital, 6 analog, 6 PWM",
      memory: "32KB Flash, 2KB SRAM, 1KB EEPROM",
      voltage: "5V operating, 7-12V input",
      usb: "USB-B with CH340 driver",
      compatibility: "Arduino IDE, shields compatible",
      package: "3 boards with USB cables",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-008",
    name: "Arduino Nano V3.0 ATmega328P CH340 (5-Pack)",
    brand: "KeeYees",
    category: "microcontroller",
    subcategory: "development_board",
    price: 16,
    rating: 3.9,
    review_count: 892,
    in_stock: true,
    stock_quantity: 234,
    tags: ["arduino", "nano", "atmega328p", "ch340", "5-pack", "compact"],
    specs: {
      microcontroller: "ATmega328P",
      clock: "16MHz",
      io: "22 digital, 8 analog",
      memory: "32KB Flash, 2KB SRAM, 1KB EEPROM",
      voltage: "5V logic, 7-12V input",
      usb: "Mini USB with CH340",
      size: "45mm x 18mm",
      package: "5 boards with cables",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-009",
    name: "Arduino Mega 2560 R3 Compatible CH340",
    brand: "HiLetgo",
    category: "microcontroller",
    subcategory: "development_board",
    price: 15,
    original_price: 22,
    rating: 3.8,
    review_count: 567,
    in_stock: true,
    stock_quantity: 89,
    tags: ["arduino", "mega", "2560", "ch340", "clone", "many-pins"],
    specs: {
      microcontroller: "ATmega2560",
      clock: "16MHz",
      io: "54 digital, 16 analog, 15 PWM",
      memory: "256KB Flash, 8KB SRAM, 4KB EEPROM",
      voltage: "5V operating, 7-12V input",
      usb: "USB-B with CH340",
      features: "4x UART, more memory than Uno",
      compatibility: "Mega shields supported",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-010",
    name: "Arduino Pro Mini ATmega328P 5V/16MHz (10-Pack)",
    brand: "DAOKI",
    category: "microcontroller",
    subcategory: "development_board",
    price: 22,
    rating: 4.1,
    review_count: 445,
    in_stock: false,
    stock_quantity: 0,
    tags: ["arduino", "pro-mini", "atmega328p", "10-pack", "minimal", "embedded"],
    specs: {
      microcontroller: "ATmega328P",
      clock: "16MHz",
      voltage: "5V (also 3.3V version available)",
      io: "14 digital, 8 analog",
      memory: "32KB Flash, 2KB SRAM, 1KB EEPROM",
      programming: "FTDI or USB-TTL required",
      size: "33mm x 18mm",
      package: "10 boards per pack",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-011",
    name: "LilyPad Arduino Compatible ATmega328P (5-Pack)",
    brand: "Generic",
    category: "microcontroller",
    subcategory: "wearable",
    price: 19,
    rating: 3.5,
    review_count: 123,
    in_stock: true,
    stock_quantity: 67,
    tags: ["arduino", "lilypad", "wearable", "etextile", "5-pack", "round"],
    specs: {
      microcontroller: "ATmega328P",
      clock: "8MHz",
      voltage: "2.7-5.5V",
      io: "14 sewable pins",
      memory: "32KB Flash, 2KB SRAM",
      programming: "FTDI breakout required",
      washability: "Remove before washing",
      diameter: "50mm circular",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // ESP32 Variants (5)
  {
    id: "iot-012",
    name: "ESP32 DevKit V1 WROOM-32 30-pin (Generic)",
    brand: "Generic",
    category: "microcontroller",
    subcategory: "wifi_module",
    price: 7,
    rating: 4.2,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 445,
    tags: ["esp32", "wroom", "devkit", "wifi", "bluetooth", "cheap", "iot"],
    specs: {
      processor: "ESP32-D0WDQ6 dual-core",
      clock: "Up to 240MHz",
      memory: "520KB SRAM, 4MB Flash",
      connectivity: "802.11 b/g/n Wi-Fi, Bluetooth 4.2",
      io: "30 GPIO pins",
      interfaces: "SPI, I2C, UART, I2S, PWM",
      voltage: "3.3V logic",
      programming: "Arduino, MicroPython, ESP-IDF",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-013",
    name: "ESP32-S3-DevKitC-1 N8R8 WiFi+Bluetooth 5.0",
    brand: "HiLetgo",
    category: "microcontroller",
    subcategory: "wifi_module",
    price: 12,
    original_price: 18,
    rating: 4.0,
    review_count: 334,
    in_stock: true,
    stock_quantity: 78,
    tags: ["esp32", "esp32-s3", "devkitc", "wifi6", "ble-5", "ai", "hiletgo"],
    specs: {
      processor: "ESP32-S3 dual-core Xtensa LX7",
      clock: "240MHz",
      memory: "512KB SRAM, 8MB PSRAM, 8MB Flash",
      connectivity: "Wi-Fi 6, Bluetooth 5.0 LE",
      ai: "Vector instructions for AI/ML",
      usb: "USB-OTG native",
      io: "45 programmable GPIO",
      security: "Secure boot, digital signature",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-014",
    name: "ESP32-C3-DevKitM-1 RISC-V Board (5-Pack)",
    brand: "DAOKI",
    category: "microcontroller",
    subcategory: "wifi_module",
    price: 25,
    rating: 3.8,
    review_count: 156,
    in_stock: true,
    stock_quantity: 45,
    tags: ["esp32", "esp32-c3", "risc-v", "5-pack", "low-power", "cheap"],
    specs: {
      processor: "ESP32-C3 single-core RISC-V",
      clock: "160MHz",
      memory: "400KB SRAM, 4MB Flash",
      connectivity: "Wi-Fi 6, Bluetooth 5.0 LE",
      io: "22 GPIO pins",
      usb: "USB-C onboard",
      security: "Secure boot support",
      package: "5 boards per pack",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-015",
    name: "ESP32-CAM WiFi Camera Module with OV2640 (2-Pack)",
    brand: "KeeYees",
    category: "microcontroller",
    subcategory: "camera_module",
    price: 15,
    rating: 3.7,
    review_count: 678,
    in_stock: false,
    stock_quantity: 0,
    tags: ["esp32-cam", "camera", "ov2640", "wifi", "2-pack", "surveillance"],
    specs: {
      processor: "ESP32-S dual-core",
      camera: "OV2640 2MP included",
      resolution: "1600x1200 max",
      connectivity: "Wi-Fi, Bluetooth",
      storage: "MicroSD slot up to 4GB",
      io: "9 GPIO available",
      programming: "USB-TTL adapter required",
      package: "2 modules with cameras",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-016",
    name: "ESP32-WROOM-32U External Antenna Module (10-Pack)",
    brand: "Generic",
    category: "microcontroller",
    subcategory: "wifi_module",
    price: 35,
    rating: 3.9,
    review_count: 234,
    in_stock: true,
    stock_quantity: 56,
    tags: ["esp32", "wroom", "external-antenna", "u-fl", "10-pack", "module"],
    specs: {
      processor: "ESP32-D0WD",
      memory: "520KB SRAM, 4MB Flash",
      connectivity: "Wi-Fi, Bluetooth, U.FL connector",
      antenna: "External via U.FL/IPEX",
      range: "Improved with external antenna",
      certification: "FCC/CE certified module",
      io: "38 GPIO via castellations",
      package: "10 modules per pack",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // STM32 (2)
  {
    id: "iot-017",
    name: "STM32F103C8T6 Blue Pill Board (5-Pack with ST-Link)",
    brand: "Generic",
    category: "microcontroller",
    subcategory: "arm_dev_board",
    price: 22,
    original_price: 32,
    rating: 4.1,
    review_count: 567,
    in_stock: true,
    stock_quantity: 123,
    tags: ["stm32", "blue-pill", "f103", "arm", "cortex-m3", "5-pack", "st-link"],
    specs: {
      processor: "STM32F103C8T6 ARM Cortex-M3",
      clock: "72MHz",
      memory: "64KB Flash, 20KB SRAM",
      io: "37 GPIO, 10 analog",
      voltage: "3.3V logic, 5V tolerant inputs",
      programming: "ST-Link V2 included",
      interfaces: "USB, CAN, SPI, I2C, UART",
      package: "5 boards + 1 ST-Link",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-018",
    name: "STM32F407VGT6 Black Pill Development Board",
    brand: "DAOKI",
    category: "microcontroller",
    subcategory: "arm_dev_board",
    price: 18,
    rating: 3.9,
    review_count: 289,
    in_stock: true,
    stock_quantity: 34,
    tags: ["stm32", "black-pill", "f407", "cortex-m4", "high-performance", "usb-c"],
    specs: {
      processor: "STM32F407VGT6 ARM Cortex-M4F",
      clock: "168MHz",
      memory: "1MB Flash, 192KB SRAM",
      fpu: "Hardware floating point",
      io: "82 GPIO, 16 analog",
      usb: "USB-C OTG",
      features: "DSP instructions, Crypto",
      programming: "ST-Link or DFU bootloader",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // RP2040 (2)
  {
    id: "iot-019",
    name: "Raspberry Pi Pico RP2040 Compatible (10-Pack)",
    brand: "HiLetgo",
    category: "microcontroller",
    subcategory: "rp2040_board",
    price: 28,
    rating: 4.3,
    review_count: 445,
    in_stock: true,
    stock_quantity: 89,
    tags: ["rp2040", "pico", "raspberry-pi", "10-pack", "dual-core", "micropython"],
    specs: {
      processor: "RP2040 dual-core Cortex-M0+",
      clock: "133MHz",
      memory: "264KB SRAM, 2MB Flash",
      io: "26 GPIO, 3 analog",
      interfaces: "2x UART, 2x I2C, 2x SPI, 16x PWM",
      usb: "USB 1.1 device/host",
      programming: "MicroPython, C/C++, Arduino",
      package: "10 boards, no headers",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-020",
    name: "Waveshare RP2040-Zero Mini Board (5-Pack)",
    brand: "KeeYees",
    category: "microcontroller",
    subcategory: "rp2040_board",
    price: 20,
    rating: 4.0,
    review_count: 178,
    in_stock: false,
    stock_quantity: 0,
    tags: ["rp2040", "zero", "waveshare-compatible", "5-pack", "tiny", "rgb-led"],
    specs: {
      processor: "RP2040 dual-core Cortex-M0+",
      clock: "133MHz",
      memory: "264KB SRAM, 2MB Flash",
      io: "20 GPIO via castellations",
      usb: "USB-C onboard",
      led: "WS2812 RGB LED onboard",
      size: "23mm x 18mm",
      package: "5 mini boards",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // ========== SENSORS (25 products) ==========

  // Temperature/Humidity (5)
  {
    id: "iot-021",
    name: "DHT22 AM2302 Digital Temp Humidity Sensor (10-Pack)",
    brand: "Generic",
    category: "sensor",
    subcategory: "environmental_sensor",
    price: 18,
    rating: 3.8,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 312,
    tags: ["dht22", "am2302", "temperature", "humidity", "10-pack", "cheap"],
    specs: {
      temperature_range: "-40°C to 80°C",
      temperature_accuracy: "±0.5°C",
      humidity_range: "0-100% RH",
      humidity_accuracy: "±2-5%",
      sampling: "0.5Hz max",
      voltage: "3.3V-6V",
      current: "2.5mA max",
      package: "10 sensors with cables",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-022",
    name: "DHT11 Temperature Humidity Sensor Module (5-Pack)",
    brand: "HiLetgo",
    category: "sensor",
    subcategory: "environmental_sensor",
    price: 8,
    rating: 3.5,
    review_count: 892,
    in_stock: true,
    stock_quantity: 445,
    tags: ["dht11", "temperature", "humidity", "5-pack", "beginner", "cheap"],
    specs: {
      temperature_range: "0°C to 50°C",
      temperature_accuracy: "±2°C",
      humidity_range: "20-90% RH",
      humidity_accuracy: "±5%",
      sampling: "1Hz max",
      voltage: "3.3V-5V",
      library: "Arduino DHT library compatible",
      package: "5 modules with PCBs",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-023",
    name: "BME280 Pressure Temperature Humidity Sensor I2C/SPI",
    brand: "Generic",
    category: "sensor",
    subcategory: "environmental_sensor",
    price: 5,
    original_price: 9,
    rating: 4.0,
    review_count: 678,
    in_stock: true,
    stock_quantity: 234,
    tags: ["bme280", "pressure", "temperature", "humidity", "i2c", "spi", "altitude"],
    specs: {
      temperature: "-40°C to 85°C, ±1°C",
      humidity: "0-100% RH, ±3%",
      pressure: "300-1100 hPa, ±1 hPa",
      altitude: "Calculated from pressure",
      interfaces: "I2C (0x76/0x77) or SPI",
      voltage: "1.8V-5V with level shifter",
      current: "3.6µA @ 1Hz",
      size: "11mm x 15mm breakout",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-024",
    name: "SHT30 Temperature Humidity Sensor Module I2C",
    brand: "DAOKI",
    category: "sensor",
    subcategory: "environmental_sensor",
    price: 7,
    rating: 3.9,
    review_count: 234,
    in_stock: true,
    stock_quantity: 156,
    tags: ["sht30", "sensirion-compatible", "temperature", "humidity", "i2c", "accurate"],
    specs: {
      temperature_range: "-40°C to 125°C",
      temperature_accuracy: "±0.3°C",
      humidity_range: "0-100% RH",
      humidity_accuracy: "±2%",
      interface: "I2C address 0x44/0x45",
      voltage: "2.4V-5.5V",
      features: "Alert mode, heater function",
      response: "8 seconds typical",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-025",
    name: "DS18B20 Waterproof Temperature Sensor 3m Cable (5-Pack)",
    brand: "KeeYees",
    category: "sensor",
    subcategory: "temperature_sensor",
    price: 14,
    rating: 4.1,
    review_count: 567,
    in_stock: false,
    stock_quantity: 0,
    tags: ["ds18b20", "waterproof", "temperature", "1-wire", "5-pack", "probe"],
    specs: {
      temperature_range: "-55°C to 125°C",
      accuracy: "±0.5°C (-10°C to 85°C)",
      resolution: "9-12 bit programmable",
      interface: "1-Wire protocol",
      cable: "3 meters, stainless probe",
      voltage: "3.0V-5.5V",
      waterproof: "IP68 probe rating",
      package: "5 probes with resistor",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Motion/PIR (4)
  {
    id: "iot-026",
    name: "HC-SR501 PIR Motion Sensor Module (5-Pack)",
    brand: "Generic",
    category: "sensor",
    subcategory: "motion_sensor",
    price: 12,
    rating: 3.9,
    review_count: 1456,
    in_stock: true,
    stock_quantity: 289,
    tags: ["pir", "motion", "hc-sr501", "infrared", "5-pack", "security"],
    specs: {
      sensor_type: "Pyroelectric IR",
      detection_range: "3-7 meters",
      detection_angle: "110 degrees",
      delay_time: "5-200s adjustable",
      sensitivity: "3-7m adjustable",
      voltage: "4.5V-20V DC",
      output: "3.3V TTL high on detection",
      quiescent_current: "<50µA",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-027",
    name: "HC-SR04 Ultrasonic Distance Sensor (10-Pack)",
    brand: "HiLetgo",
    category: "sensor",
    subcategory: "proximity_sensor",
    price: 18,
    original_price: 28,
    rating: 4.0,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 445,
    tags: ["hc-sr04", "ultrasonic", "distance", "10-pack", "robotics", "cheap"],
    specs: {
      range: "2cm to 400cm",
      accuracy: "±3mm",
      angle: "15 degree cone",
      trigger: "10µs TTL pulse",
      echo: "TTL pulse proportional",
      voltage: "5V DC",
      current: "15mA",
      frequency: "40kHz",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-028",
    name: "RCWL-0516 Microwave Radar Motion Sensor",
    brand: "DAOKI",
    category: "sensor",
    subcategory: "motion_sensor",
    price: 4,
    rating: 3.6,
    review_count: 334,
    in_stock: true,
    stock_quantity: 178,
    tags: ["rcwl-0516", "radar", "microwave", "motion", "through-wall", "doppler"],
    specs: {
      sensor_type: "Doppler radar",
      frequency: "3.2GHz",
      detection_range: "5-9 meters",
      detection_angle: "360 degrees",
      through_walls: "Detects through thin walls",
      voltage: "4V-28V DC",
      output: "High 3.3V on detection",
      cd_s_pin: "Light sensor disable",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-029",
    name: "MPU6050 6-Axis Accelerometer Gyroscope Module (5-Pack)",
    brand: "KeeYees",
    category: "sensor",
    subcategory: "imu_sensor",
    price: 16,
    rating: 4.1,
    review_count: 567,
    in_stock: true,
    stock_quantity: 234,
    tags: ["mpu6050", "accelerometer", "gyroscope", "6-axis", "imu", "5-pack", "motion"],
    specs: {
      accelerometer: "±2g, ±4g, ±8g, ±16g ranges",
      gyroscope: "±250, ±500, ±1000, ±2000 °/s",
      interface: "I2C 400kHz",
      address: "0x68 (AD0=GND) or 0x69",
      voltage: "3.3V-5V",
      dmp: "Digital Motion Processor onboard",
      package: "5 modules with pins",
      library: "i2cdevlib compatible",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Distance (4)
  {
    id: "iot-030",
    name: "VL53L0X Time-of-Flight Laser Distance Sensor",
    brand: "Generic",
    category: "sensor",
    subcategory: "laser_distance",
    price: 6,
    rating: 3.7,
    review_count: 445,
    in_stock: true,
    stock_quantity: 123,
    tags: ["vl53l0x", "tof", "laser", "distance", "i2c", "accurate", "st-compatible"],
    specs: {
      range: "5cm to 200cm",
      accuracy: "±3% typical",
      technology: "940nm VCSEL Time-of-Flight",
      interface: "I2C 400kHz",
      address: "0x29 (changeable)",
      voltage: "2.6V-3.5V",
      update_rate: "Up to 50Hz",
      immunity: "Not affected by color",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-031",
    name: "Sharp GP2Y0A21YK0F IR Distance Sensor 10-80cm",
    brand: "Generic",
    category: "sensor",
    subcategory: "ir_distance",
    price: 8,
    rating: 3.8,
    review_count: 289,
    in_stock: false,
    stock_quantity: 0,
    tags: ["sharp", "gp2y0a21", "ir", "distance", "analog", "proximity"],
    specs: {
      range: "10cm to 80cm",
      output: "Analog voltage 0.4V-2.4V",
      technology: "Infrared triangulation",
      voltage: "4.5V-5.5V",
      current: "30mA average",
      refresh: "25ms cycle time",
      connector: "JST 3-pin",
      note: "Non-linear output curve",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-032",
    name: "TF-Luna LiDAR Range Sensor UART/I2C 8m",
    brand: "HiLetgo",
    category: "sensor",
    subcategory: "lidar",
    price: 25,
    original_price: 35,
    rating: 3.9,
    review_count: 123,
    in_stock: true,
    stock_quantity: 45,
    tags: ["tf-luna", "lidar", "tof", "8m", "uart", "i2c", "robotics"],
    specs: {
      range: "0.2m to 8m",
      accuracy: "±6cm @ 6m",
      resolution: "1cm",
      frame_rate: "100Hz default, up to 250Hz",
      interfaces: "UART or I2C",
      voltage: "5V",
      current: "<100mA",
      size: "35mm x 21.25mm",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-033",
    name: "JSN-SR04T Waterproof Ultrasonic Sensor",
    brand: "DAOKI",
    category: "sensor",
    subcategory: "ultrasonic_waterproof",
    price: 9,
    rating: 3.5,
    review_count: 234,
    in_stock: true,
    stock_quantity: 89,
    tags: ["jsn-sr04t", "ultrasonic", "waterproof", "outdoor", "tank", "level"],
    specs: {
      range: "25cm to 600cm",
      blind_zone: "25cm minimum",
      accuracy: "±1cm",
      probe: "IP65 waterproof separate sensor",
      cable: "2.5m probe cable",
      voltage: "3.3V-5.5V",
      modes: "Mode 0 serial, Mode 1 trigger/echo",
      applications: "Water tank, outdoor use",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Environmental/Gas (5)
  {
    id: "iot-034",
    name: "MQ-2 Gas Sensor Module Smoke LPG Butane (3-Pack)",
    brand: "KeeYees",
    category: "sensor",
    subcategory: "gas_sensor",
    price: 12,
    rating: 3.6,
    review_count: 678,
    in_stock: true,
    stock_quantity: 267,
    tags: ["mq-2", "gas", "smoke", "lpg", "butane", "3-pack", "safety"],
    specs: {
      detects: "Smoke, LPG, Butane, Propane, Methane, Alcohol",
      sensor_type: "SnO2 semiconductor",
      sensitivity: "Adjustable via pot",
      heatup_time: "20 seconds preheat",
      output: "Analog + Digital",
      voltage: "5V DC",
      load_resistor: "Adjustable",
      package: "3 modules with cables",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-035",
    name: "MQ-135 Air Quality Sensor CO2 NH3 Benzene (3-Pack)",
    brand: "Generic",
    category: "sensor",
    subcategory: "gas_sensor",
    price: 11,
    rating: 3.4,
    review_count: 445,
    in_stock: true,
    stock_quantity: 189,
    tags: ["mq-135", "air-quality", "co2", "nh3", "benzene", "pollution", "3-pack"],
    specs: {
      detects: "CO2, NH3, Benzene, NOx, Alcohol, Smoke",
      sensor_type: "SnO2 semiconductor",
      sensitivity: "Analog output",
      range: "10-1000ppm NH3, 10-300ppm Benzene",
      heatup_time: "48 hours burn-in recommended",
      voltage: "5V DC",
      note: "Cross-sensitive to multiple gases",
      package: "3 modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-036",
    name: "CCS811 CO2 eCO2 TVOC Air Quality Sensor I2C",
    brand: "HiLetgo",
    category: "sensor",
    subcategory: "air_quality",
    price: 8,
    rating: 3.3,
    review_count: 312,
    in_stock: false,
    stock_quantity: 0,
    tags: ["ccs811", "co2", "eco2", "tvoc", "air-quality", "i2c", "low-power"],
    specs: {
      eco2_range: "400ppm to 8192ppm",
      tvoc_range: "0ppb to 1187ppb",
      interface: "I2C 100kHz",
      address: "0x5A or 0x5B",
      voltage: "1.8V-3.3V",
      current: "26mA peak, 0.6mA avg",
      warm_up: "20 minutes for accuracy",
      note: "Requires baseline calibration",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-037",
    name: "PMS5003 PM2.5 Air Quality Sensor UART",
    brand: "DAOKI",
    category: "sensor",
    subcategory: "particulate_sensor",
    price: 22,
    rating: 3.7,
    review_count: 156,
    in_stock: true,
    stock_quantity: 34,
    tags: ["pms5003", "pm2.5", "pm10", "air-quality", "particulate", "dust", "plantower-compatible"],
    specs: {
      measures: "PM1.0, PM2.5, PM10",
      range: "0-500 µg/m³",
      accuracy: "±15% @ 100µg/m³",
      interface: "UART 9600 baud",
      response: "<10 seconds",
      voltage: "5V",
      current: "<100mA",
      fan: "Built-in for airflow",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-038",
    name: "BMP280 Pressure Temperature Sensor I2C/SPI (5-Pack)",
    brand: "Generic",
    category: "sensor",
    subcategory: "pressure_sensor",
    price: 12,
    rating: 4.0,
    review_count: 567,
    in_stock: true,
    stock_quantity: 234,
    tags: ["bmp280", "pressure", "temperature", "barometer", "altitude", "i2c", "spi", "5-pack"],
    specs: {
      pressure_range: "300-1100 hPa",
      pressure_accuracy: "±1 hPa",
      temperature: "-40°C to 85°C",
      altitude_resolution: "±1 meter",
      interface: "I2C or SPI",
      i2c_address: "0x76 or 0x77",
      voltage: "1.8V-3.6V",
      package: "5 breakouts",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Light/Color (3)
  {
    id: "iot-039",
    name: "BH1750 Light Sensor Module I2C (5-Pack)",
    brand: "KeeYees",
    category: "sensor",
    subcategory: "light_sensor",
    price: 10,
    rating: 4.1,
    review_count: 445,
    in_stock: true,
    stock_quantity: 312,
    tags: ["bh1750", "light", "lux", "i2c", "ambient", "5-pack", "low-power"],
    specs: {
      range: "1-65535 lux",
      accuracy: "±20%",
      resolution: "1-4 lux selectable",
      interface: "I2C",
      address: "0x23 or 0x5C",
      voltage: "3.3V-5V",
      current: "<0.5mA",
      modes: "Continuous or one-shot",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-040",
    name: "TCS3200 Color Recognition Sensor Module",
    brand: "Generic",
    category: "sensor",
    subcategory: "color_sensor",
    price: 5,
    rating: 3.5,
    review_count: 289,
    in_stock: true,
    stock_quantity: 178,
    tags: ["tcs3200", "color", "rgb", "recognition", "frequency", "sorting"],
    specs: {
      detection: "Red, Green, Blue, Clear",
      output: "Frequency proportional",
      interface: "Digital frequency output",
      filters: "Selectable via S2/S3 pins",
      scaling: "Selectable frequency scaling",
      voltage: "3V-5V",
      led: "White LEDs onboard",
      application: "Color sorting, detection",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-041",
    name: "TSL2561 Luminosity Sensor IR+Visible I2C",
    brand: "HiLetgo",
    category: "sensor",
    subcategory: "light_sensor",
    price: 4,
    rating: 3.8,
    review_count: 234,
    in_stock: false,
    stock_quantity: 0,
    tags: ["tsl2561", "luminosity", "lux", "ir", "visible", "i2c", "ams-compatible"],
    specs: {
      sensors: "IR + Visible light photodiodes",
      range: "0.1-40,000 lux",
      interface: "I2C",
      address: "0x39 (floating), 0x29 (GND), 0x49 (VCC)",
      voltage: "2.7V-3.6V",
      features: "Programmable gain, integration",
      interrupt: "Programmable threshold",
      library: "Adafruit TSL2561 compatible",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Current/Voltage (4)
  {
    id: "iot-042",
    name: "ACS712 Hall Current Sensor Module 5A/20A/30A (3-Pack)",
    brand: "DAOKI",
    category: "sensor",
    subcategory: "current_sensor",
    price: 11,
    rating: 3.7,
    review_count: 567,
    in_stock: true,
    stock_quantity: 145,
    tags: ["acs712", "current", "hall-effect", "5a", "20a", "30a", "3-pack"],
    specs: {
      variants: "5A, 20A, or 30A range",
      sensitivity: "185mV/A (5A), 100mV/A (20A), 66mV/A (30A)",
      technology: "Hall effect isolation",
      isolation: "2.1kV RMS",
      bandwidth: "80kHz",
      voltage: "5V DC",
      output: "Analog voltage",
      package: "3 assorted modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-043",
    name: "INA219 Current Voltage Sensor I2C 26V 3.2A",
    brand: "KeeYees",
    category: "sensor",
    subcategory: "power_monitor",
    price: 6,
    rating: 4.2,
    review_count: 445,
    in_stock: true,
    stock_quantity: 234,
    tags: ["ina219", "current", "voltage", "power", "i2c", "high-side", "monitor"],
    specs: {
      voltage_range: "0-26V bus voltage",
      current_range: "±3.2A with 0.1Ω shunt",
      resolution: "12-bit ADC, 0.8mA LSB",
      interface: "I2C 1MHz",
      address: "0x40-0x4F via jumpers",
      voltage: "3V-5.5V logic",
      calibration: "Internal calibration",
      accuracy: "±1% max error",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-044",
    name: "ZMPT101B Voltage Sensor Module AC 250V",
    brand: "Generic",
    category: "sensor",
    subcategory: "voltage_sensor",
    price: 5,
    rating: 3.4,
    review_count: 178,
    in_stock: true,
    stock_quantity: 89,
    tags: ["zmpt101b", "voltage", "ac", "isolation", "transformer", "mains"],
    specs: {
      input_range: "AC 0-250V",
      output: "Analog voltage 0-5V",
      isolation: "Optical isolation via transformer",
      transformer: "Precision voltage transformer",
      frequency: "50Hz/60Hz compatible",
      voltage: "5V DC",
      calibration: "Potentiometer adjustable",
      safety: "Isolated from mains",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-045",
    name: "SCT-013-030 Non-invasive Current Sensor 30A",
    brand: "HiLetgo",
    category: "sensor",
    subcategory: "current_clamp",
    price: 9,
    rating: 3.9,
    review_count: 312,
    in_stock: true,
    stock_quantity: 67,
    tags: ["sct-013", "current", "clamp", "non-invasive", "30a", "energy", "monitor"],
    specs: {
      range: "0-30A AC",
      output: "0-1V voltage output",
      ratio: "30A:1V",
      opening: "13mm clamp diameter",
      non_invasive: "No electrical contact needed",
      accuracy: "±1%",
      isolation: "Fully isolated",
      application: "Energy monitoring, smart home",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // ========== SINGLE BOARD COMPUTERS (10 products) ==========

  // Orange Pi (3)
  {
    id: "iot-046",
    name: "Orange Pi 5 8GB Rockchip RK3588S",
    brand: "Orange Pi",
    category: "single_board_computer",
    subcategory: "arm_sbc",
    price: 89,
    original_price: 119,
    rating: 4.0,
    review_count: 234,
    in_stock: true,
    stock_quantity: 45,
    tags: ["orange-pi", "opi5", "rk3588", "8gb", "arm", "sbc", "8k"],
    specs: {
      processor: "Rockchip RK3588S 8-core",
      cpu: "4x Cortex-A76 + 4x Cortex-A55",
      gpu: "Mali-G610 MP4",
      npu: "6 TOPS AI accelerator",
      memory: "8GB LPDDR4",
      storage: "eMMC socket, M.2 NVMe, MicroSD",
      video: "8K@60fps decode, 4K encode",
      ports: "HDMI 2.1, USB 3.0, 2.5GbE",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-047",
    name: "Orange Pi Zero 2 1GB Allwinner H616",
    brand: "Orange Pi",
    category: "single_board_computer",
    subcategory: "compact_sbc",
    price: 25,
    rating: 3.8,
    review_count: 445,
    in_stock: true,
    stock_quantity: 78,
    tags: ["orange-pi", "zero2", "h616", "compact", "cheap", "arm"],
    specs: {
      processor: "Allwinner H616 quad-core Cortex-A53",
      memory: "1GB DDR3",
      connectivity: "Wi-Fi 5, Bluetooth 5.0",
      ports: "USB 2.0 OTG, MicroSD",
      video: "4K@60fps decode",
      gpio: "26-pin header",
      power: "USB-C 5V/3A",
      size: "48mm x 46mm",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-048",
    name: "Orange Pi 3 LTS 2GB Allwinner H6",
    brand: "Orange Pi",
    category: "single_board_computer",
    subcategory: "arm_sbc",
    price: 35,
    original_price: 49,
    rating: 3.6,
    review_count: 189,
    in_stock: false,
    stock_quantity: 0,
    tags: ["orange-pi", "opi3", "lts", "h6", "2gb", "sbc", "wifi"],
    specs: {
      processor: "Allwinner H6 quad-core Cortex-A53",
      memory: "2GB DDR3",
      storage: "8GB eMMC onboard, MicroSD",
      connectivity: "Wi-Fi 5, Bluetooth 5.0, Gigabit Ethernet",
      video: "4K@60fps decode",
      ports: "HDMI 2.0, 3x USB 3.0",
      gpio: "26-pin header",
      power: "USB-C or DC jack",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Banana Pi (2)
  {
    id: "iot-049",
    name: "Banana Pi BPI-M5 Amlogic S905X3 4GB",
    brand: "Banana Pi",
    category: "single_board_computer",
    subcategory: "arm_sbc",
    price: 58,
    rating: 3.7,
    review_count: 123,
    in_stock: true,
    stock_quantity: 34,
    tags: ["banana-pi", "bpi-m5", "s905x3", "amlogic", "4gb", "sbc"],
    specs: {
      processor: "Amlogic S905X3 quad-core Cortex-A55",
      memory: "4GB LPDDR4",
      storage: "16GB eMMC onboard, MicroSD",
      video: "4K@75fps, HDR10, H.265 decode",
      ports: "HDMI 2.0, 4x USB 3.0, Gigabit Ethernet",
      gpio: "40-pin Raspberry Pi compatible",
      m2_slot: "M.2 Key E for Wi-Fi/BT",
      power: "USB-C 5V/3A",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-050",
    name: "Banana Pi BPI-M64 Allwinner A64 2GB",
    brand: "Banana Pi",
    category: "single_board_computer",
    subcategory: "arm_sbc",
    price: 42,
    rating: 3.5,
    review_count: 89,
    in_stock: true,
    stock_quantity: 23,
    tags: ["banana-pi", "bpi-m64", "a64", "64-bit", "2gb", "sbc"],
    specs: {
      processor: "Allwinner A64 quad-core Cortex-A53",
      memory: "2GB DDR3",
      storage: "MicroSD, eMMC socket",
      connectivity: "Wi-Fi, Bluetooth onboard",
      video: "1080p60 via HDMI",
      ports: "HDMI, 2x USB 2.0, Gigabit Ethernet",
      gpio: "40-pin header",
      power: "Micro USB or DC jack",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Radxa (2)
  {
    id: "iot-051",
    name: "Radxa Zero 3W RK3566 2GB WiFi 6",
    brand: "Radxa",
    category: "single_board_computer",
    subcategory: "compact_sbc",
    price: 35,
    rating: 3.9,
    review_count: 67,
    in_stock: true,
    stock_quantity: 56,
    tags: ["radxa", "zero-3w", "rk3566", "2gb", "compact", "wifi6"],
    specs: {
      processor: "Rockchip RK3566 quad-core Cortex-A55",
      gpu: "Mali-G52",
      memory: "2GB LPDDR4",
      connectivity: "Wi-Fi 6, Bluetooth 5.4",
      storage: "eMMC onboard options, MicroSD",
      video: "4K@60fps decode",
      ports: "USB 3.0, USB-C OTG, HDMI",
      size: "65mm x 30mm",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-052",
    name: "Radxa ROCK 5B RK3588 8GB",
    brand: "Radxa",
    category: "single_board_computer",
    subcategory: "arm_sbc",
    price: 129,
    original_price: 159,
    rating: 4.1,
    review_count: 89,
    in_stock: true,
    stock_quantity: 23,
    tags: ["radxa", "rock5b", "rk3588", "8gb", "high-performance", "8k"],
    specs: {
      processor: "Rockchip RK3588 octa-core",
      cpu: "4x Cortex-A76 + 4x Cortex-A55",
      gpu: "Mali-G610 MC4",
      npu: "6 TOPS AI",
      memory: "8GB LPDDR4X",
      storage: "eMMC, M.2 NVMe, MicroSD",
      video: "8K@60fps output, 4K encode",
      ports: "HDMI 2.1, 2.5GbE, USB 3.0",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Jetson (1)
  {
    id: "iot-053",
    name: "NVIDIA Jetson Nano 4GB Developer Kit (Clone/Compatible)",
    brand: "Generic",
    category: "single_board_computer",
    subcategory: "ai_sbc",
    price: 149,
    rating: 3.4,
    review_count: 45,
    in_stock: false,
    stock_quantity: 0,
    tags: ["jetson", "nano", "nvidia-compatible", "ai", "cuda", "4gb", "deep-learning"],
    specs: {
      processor: "Compatible quad-core ARM Cortex-A57",
      gpu: "128 CUDA cores equivalent",
      memory: "4GB 64-bit LPDDR4",
      ai_performance: "Not genuine Jetson AI",
      storage: "MicroSD slot",
      video: "4K@30fps support",
      ports: "HDMI, 4x USB 3.0, Gigabit Ethernet",
      note: "Third-party compatible board",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Khadas (2)
  {
    id: "iot-054",
    name: "Khadas VIM3 Amlogic A311D 4GB",
    brand: "Khadas",
    category: "single_board_computer",
    subcategory: "arm_sbc",
    price: 119,
    rating: 4.0,
    review_count: 123,
    in_stock: true,
    stock_quantity: 34,
    tags: ["khadas", "vim3", "a311d", "4gb", "npu", "m2", "high-end"],
    specs: {
      processor: "Amlogic A311D hexa-core",
      cpu: "4x Cortex-A73 + 2x Cortex-A53",
      npu: "5 TOPS AI accelerator",
      memory: "4GB LPDDR4",
      storage: "32GB eMMC, MicroSD, M.2 slot",
      video: "4K@75fps, HDR10+",
      ports: "HDMI 2.1, USB-C, USB 3.0",
      features: "Active cooling, RTC, GPIO",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-055",
    name: "Khadas Edge-V RK3399 4GB M.2 Form Factor",
    brand: "Khadas",
    category: "single_board_computer",
    subcategory: "compact_sbc",
    price: 99,
    original_price: 139,
    rating: 3.8,
    review_count: 67,
    in_stock: true,
    stock_quantity: 23,
    tags: ["khadas", "edge-v", "rk3399", "4gb", "m2", "compact", "hexa-core"],
    specs: {
      processor: "Rockchip RK3399 hexa-core",
      cpu: "2x Cortex-A72 + 4x Cortex-A53",
      gpu: "Mali-T860 MP4",
      memory: "4GB LPDDR4",
      storage: "eMMC, M.2 NVMe, MicroSD",
      video: "4K@60fps, dual display",
      form_factor: "M.2 2280 compatible",
      ports: "USB-C, HDMI via dock",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // ========== SMART HOME / AUTOMATION (15 products) ==========

  // Relays (4)
  {
    id: "iot-056",
    name: "SONOFF BASICR2 WiFi Smart Switch Module (4-Pack)",
    brand: "SONOFF",
    category: "smart_home",
    subcategory: "smart_switch",
    price: 28,
    rating: 4.1,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 234,
    tags: ["sonoff", "basic", "wifi", "relay", "smart-switch", "4-pack", "home-automation"],
    specs: {
      voltage_input: "100-240V AC",
      current_rating: "10A max",
      power_rating: "2200W",
      connectivity: "Wi-Fi 2.4GHz",
      app: "eWeLink app compatible",
      voice: "Alexa, Google Assistant",
      flashing: "Tasmota/ESPHome capable",
      package: "4 switch modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-057",
    name: "5V 8-Channel Relay Module Opto-isolated for Arduino",
    brand: "HiLetgo",
    category: "smart_home",
    subcategory: "relay_module",
    price: 12,
    rating: 4.0,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 445,
    tags: ["relay", "8-channel", "5v", "opto-isolated", "arduino", "automation"],
    specs: {
      channels: "8 SPDT relays",
      relay_rating: "10A 250V AC, 10A 30V DC",
      isolation: "Optocoupler isolated",
      indicator: "LED per channel",
      voltage: "5V logic, relay supply",
      protection: "Freewheeling diodes",
      interface: "GPIO or jumper wires",
      applications: "Home automation, control",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-058",
    name: "5V 1-Channel Relay Module (10-Pack) Low Level Trigger",
    brand: "Generic",
    category: "smart_home",
    subcategory: "relay_module",
    price: 8,
    rating: 3.8,
    review_count: 567,
    in_stock: true,
    stock_quantity: 312,
    tags: ["relay", "1-channel", "5v", "10-pack", "low-level", "cheap"],
    specs: {
      channels: "1 SPDT relay",
      relay_rating: "10A 250V AC",
      trigger: "Low level active",
      led: "Power and status LEDs",
      isolation: "Optocoupler",
      voltage: "5V DC",
      screw_terminals: "NC, COM, NO",
      package: "10 relay modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-059",
    name: "SONOFF 4CH PRO R3 Multi-channel WiFi Switch",
    brand: "SONOFF",
    category: "smart_home",
    subcategory: "relay_module",
    price: 32,
    rating: 4.0,
    review_count: 890,
    in_stock: false,
    stock_quantity: 0,
    tags: ["sonoff", "4ch-pro", "4-channel", "wifi", "rf", "inching", "relay"],
    specs: {
      channels: "4 independent channels",
      voltage: "90-250V AC or 5-24V DC",
      current: "10A per channel",
      connectivity: "Wi-Fi + 433MHz RF",
      modes: "Inching/Interlock/Self-locking",
      app: "eWeLink with timers",
      flashing: "Tasmota compatible",
      rf_remote: "Optional remote control",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Smart Switches (4)
  {
    id: "iot-060",
    name: "SONOFF MINIR2 WiFi Mini Smart Switch (4-Pack)",
    brand: "SONOFF",
    category: "smart_home",
    subcategory: "smart_switch",
    price: 35,
    rating: 4.2,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 178,
    tags: ["sonoff", "mini", "r2", "wifi", "small", "4-pack", "hidden"],
    specs: {
      size: "42mm x 42mm x 20mm",
      voltage: "100-240V AC",
      current: "10A max",
      connectivity: "Wi-Fi 2.4GHz",
      features: "Fits in wall box",
      app: "eWeLink with scenes",
      voice: "Alexa, Google Home",
      package: "4 mini switches",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-061",
    name: "MOES WiFi Smart Light Switch 3-Gang Touch Panel",
    brand: "MOES",
    category: "smart_home",
    subcategory: "smart_switch",
    price: 28,
    original_price: 38,
    rating: 3.9,
    review_count: 445,
    in_stock: true,
    stock_quantity: 89,
    tags: ["moes", "wifi", "light-switch", "3-gang", "touch", "panel", "tuya"],
    specs: {
      gangs: "3-gang touch control",
      voltage: "110-240V AC",
      neutral_wire: "Required",
      connectivity: "Wi-Fi 2.4GHz",
      app: "Smart Life / Tuya",
      voice: "Alexa, Google Assistant",
      features: "Timer, schedule, scenes",
      glass_panel: "Tempered glass face",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-062",
    name: "SONOFF T1 EU 2-Gang WiFi RF Smart Wall Switch",
    brand: "SONOFF",
    category: "smart_home",
    subcategory: "smart_switch",
    price: 22,
    rating: 3.8,
    review_count: 567,
    in_stock: true,
    stock_quantity: 67,
    tags: ["sonoff", "t1", "2-gang", "wall-switch", "rf", "eu", "touch"],
    specs: {
      gangs: "2-gang touch panel",
      voltage: "90-250V AC",
      current: "2A per gang",
      connectivity: "Wi-Fi + 433MHz RF",
      app: "eWeLink with grouping",
      voice: "Alexa, Google Home",
      led: "Blue backlight",
      neutral: "Required for operation",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-063",
    name: "Shelly 1L WiFi Relay Switch No Neutral Required",
    brand: "Shelly",
    category: "smart_home",
    subcategory: "smart_switch",
    price: 16,
    rating: 4.3,
    review_count: 890,
    in_stock: true,
    stock_quantity: 156,
    tags: ["shelly", "1l", "wifi", "no-neutral", "relay", "small", "bulb"],
    specs: {
      special: "Works without neutral wire",
      voltage: "110-240V AC",
      current: "4.1A max",
      size: "39mm x 36mm x 17mm",
      connectivity: "Wi-Fi",
      app: "Shelly Cloud or local",
      dry_contact: "Supports dry contacts",
      temperature: "Overheat protection",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Smart Plugs (3)
  {
    id: "iot-064",
    name: "SONOFF S26 WiFi Smart Plug 10A (4-Pack) EU Type",
    brand: "SONOFF",
    category: "smart_home",
    subcategory: "smart_plug",
    price: 42,
    rating: 4.0,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 234,
    tags: ["sonoff", "s26", "smart-plug", "wifi", "4-pack", "eu", "outlet"],
    specs: {
      type: "EU Type F plug",
      voltage: "90-250V AC",
      current: "10A max",
      power: "2200W max",
      connectivity: "Wi-Fi 2.4GHz",
      app: "eWeLink remote control",
      voice: "Alexa, Google Assistant",
      features: "Timer, schedule, countdown",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-065",
    name: "Gosund EP2 WiFi Smart Plug with Power Monitoring (4-Pack)",
    brand: "Gosund",
    category: "smart_home",
    subcategory: "smart_plug",
    price: 38,
    original_price: 52,
    rating: 3.7,
    review_count: 567,
    in_stock: true,
    stock_quantity: 89,
    tags: ["gosund", "ep2", "smart-plug", "power-monitor", "wifi", "4-pack", "energy"],
    specs: {
      monitoring: "Real-time power consumption",
      voltage: "220-240V AC",
      current: "16A max",
      power: "3680W max",
      connectivity: "Wi-Fi",
      app: "Gosund / Tuya Smart",
      history: "Energy usage history",
      compact: "Doesn't block adjacent outlets",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-066",
    name: "BlitzWolf BW-SHP6 Pro Smart Plug 15A Power Monitor",
    brand: "BlitzWolf",
    category: "smart_home",
    subcategory: "smart_plug",
    price: 14,
    rating: 3.9,
    review_count: 445,
    in_stock: false,
    stock_quantity: 0,
    tags: ["blitzwolf", "shp6", "smart-plug", "power-monitor", "15a", "tasmota"],
    specs: {
      monitoring: "Voltage, current, power, energy",
      voltage: "110-240V AC",
      current: "15A max",
      power: "3300W max",
      connectivity: "Wi-Fi",
      app: "BlitzWolf / Tuya",
      flashing: "Tasmota compatible",
      accuracy: "±1% measurement",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Cameras (2)
  {
    id: "iot-067",
    name: "ESP32-CAM OV2640 2MP Camera Module with FTDI (3-Pack)",
    brand: "Generic",
    category: "smart_home",
    subcategory: "camera_module",
    price: 25,
    rating: 3.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 312,
    tags: ["esp32-cam", "camera", "ov2640", "3-pack", "ftdi", "diy", "surveillance"],
    specs: {
      processor: "ESP32-S dual-core",
      camera: "OV2640 2MP included",
      resolution: "1600x1200 max",
      connectivity: "Wi-Fi, Bluetooth",
      storage: "MicroSD slot up to 4GB",
      programming: "FTDI adapter included",
      features: "Face detection, streaming",
      package: "3 cameras + 1 FTDI",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-068",
    name: "Xiaomi Yi Home Camera 1080p Night Vision (Refurbished)",
    brand: "Xiaomi",
    category: "smart_home",
    subcategory: "ip_camera",
    price: 25,
    original_price: 45,
    rating: 3.4,
    review_count: 890,
    in_stock: true,
    stock_quantity: 45,
    tags: ["xiaomi", "yi", "camera", "1080p", "refurbished", "night-vision", "wifi"],
    specs: {
      resolution: "1080p Full HD",
      lens: "130-degree wide angle",
      night_vision: "940nm IR LEDs",
      two_way: "Built-in mic and speaker",
      motion: "Motion detection alerts",
      storage: "MicroSD or cloud",
      app: "Yi Home App",
      note: "Refurbished/refurb unit",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Locks (2)
  {
    id: "iot-069",
    name: "TTLock WiFi Smart Door Lock Gateway G2",
    brand: "TTLock",
    category: "smart_home",
    subcategory: "smart_lock",
    price: 45,
    rating: 3.5,
    review_count: 123,
    in_stock: true,
    stock_quantity: 34,
    tags: ["ttlock", "gateway", "wifi", "smart-lock", "remote", "bluetooth-bridge"],
    specs: {
      function: "Wi-Fi to Bluetooth bridge",
      connectivity: "Wi-Fi 2.4GHz",
      protocol: "Bluetooth 4.0 to locks",
      power: "USB 5V or battery",
      app: "TTLock app required",
      range: "10m to lock via Bluetooth",
      features: "Remote unlock, logs",
      compatibility: "TTLock ecosystem",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-070",
    name: "Electric Cabinet Lock 12V Solenoid with RFID (2-Pack)",
    brand: "Generic",
    category: "smart_home",
    subcategory: "electromagnetic_lock",
    price: 22,
    rating: 3.7,
    review_count: 234,
    in_stock: true,
    stock_quantity: 78,
    tags: ["electric-lock", "solenoid", "12v", "rfid", "cabinet", "2-pack", "access"],
    specs: {
      type: "Fail-secure solenoid lock",
      voltage: "12V DC",
      current: "0.5A at 12V",
      force: "Holding force 50kg",
      unlock: "RFID card or button",
      cards: "2 RFID cards included",
      mounting: "Surface mount",
      applications: "Cabinets, drawers, small doors",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // ========== DEVELOPMENT KITS (10 products) ==========

  // Sensor Kits (3)
  {
    id: "iot-071",
    name: "37-in-1 Sensor Kit for Arduino Raspberry Pi",
    brand: "HiLetgo",
    category: "development_kit",
    subcategory: "sensor_kit",
    price: 22,
    rating: 4.0,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 234,
    tags: ["sensor-kit", "37-in-1", "arduino", "raspberry-pi", "starter", "hiletgo"],
    specs: {
      sensors: "37 different sensors",
      includes: "Temp, humidity, motion, sound, light",
      compatibility: "Arduino, ESP32, Raspberry Pi",
      packaging: "Plastic organizer box",
      cables: "Dupont wires included",
      documentation: "Basic example code",
      value: "Good for learning IoT",
      skill_level: "Beginner friendly",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-072",
    name: "45-in-1 Advanced Sensor Module Kit with Tutorial",
    brand: "DAOKI",
    category: "development_kit",
    subcategory: "sensor_kit",
    price: 32,
    original_price: 45,
    rating: 3.8,
    review_count: 567,
    in_stock: true,
    stock_quantity: 67,
    tags: ["sensor-kit", "45-in-1", "advanced", "tutorial", "daoki", "learning"],
    specs: {
      sensors: "45 sensors and modules",
      includes: "LCD, RFID, relays, motors, sensors",
      tutorial: "CD with 30+ projects",
      compatibility: "Arduino Uno, Mega",
      packaging: "Organizer box with labels",
      cables: "65+ jumper wires",
      beginner: "Step-by-step tutorials",
      language: "English tutorial PDF",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-073",
    name: "ESP32 30 Sensors Starter Kit with OLED Display",
    brand: "KeeYees",
    category: "development_kit",
    subcategory: "sensor_kit",
    price: 38,
    rating: 3.9,
    review_count: 334,
    in_stock: false,
    stock_quantity: 0,
    tags: ["esp32", "sensor-kit", "30-sensors", "oled", "iot", "wifi", "keeyees"],
    specs: {
      board: "ESP32 DevKit included",
      sensors: "30 sensors + 0.96\" OLED",
      includes: "DHT22, motion, ultrasonic, relay",
      connectivity: "Wi-Fi, Bluetooth",
      tutorials: "Arduino sketches included",
      expansion: "Breadboard included",
      storage: "Plastic case",
      power: "USB cable included",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Starter Kits (4)
  {
    id: "iot-074",
    name: "Elegoo UNO Project Super Starter Kit",
    brand: "Elegoo",
    category: "development_kit",
    subcategory: "starter_kit",
    price: 45,
    rating: 4.3,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 189,
    tags: ["elegoo", "uno", "starter-kit", "arduino-compatible", "super", "learning"],
    specs: {
      board: "Elegoo Uno R3 compatible",
      components: "200+ pieces",
      includes: "LCD, motors, sensors, relay, RFID",
      tutorial: "PDF with 22 lessons",
      packaging: "Plastic organizer box",
      power: "9V battery + cable",
      beginner: "Complete starter kit",
      support: "Online community",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-075",
    name: "LAFVIN Arduino Starter Kit with Uno R3 Board",
    brand: "LAFVIN",
    category: "development_kit",
    subcategory: "starter_kit",
    price: 28,
    original_price: 42,
    rating: 3.9,
    review_count: 445,
    in_stock: true,
    stock_quantity: 123,
    tags: ["lafvin", "arduino", "starter-kit", "uno-r3", "ch340", "budget"],
    specs: {
      board: "Uno R3 CH340 compatible",
      components: "100+ pieces",
      includes: "Breadboard, LEDs, sensors, motor",
      tutorial: "Basic project guide",
      packaging: "Cardboard box",
      power: "USB cable included",
      beginner: "Good for basics",
      value: "Budget friendly option",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-076",
    name: "Raspberry Pi 4 4GB Complete Starter Kit",
    brand: "Generic",
    category: "development_kit",
    subcategory: "starter_kit",
    price: 95,
    rating: 3.6,
    review_count: 234,
    in_stock: true,
    stock_quantity: 45,
    tags: ["raspberry-pi", "rpi4", "4gb", "complete-kit", "starter", "case"],
    specs: {
      board: "Pi 4 4GB compatible",
      case: "ABS case with fan",
      storage: "32GB MicroSD with OS",
      power: "5V 3A USB-C supply",
      cooling: "Heatsinks + active fan",
      cables: "HDMI, Ethernet included",
      accessories: "GPIO reference card",
      note: "Third-party compatible board",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-077",
    name: "Smraza ESP32 Starter Kit with 20 Projects",
    brand: "Smraza",
    category: "development_kit",
    subcategory: "starter_kit",
    price: 35,
    rating: 3.7,
    review_count: 289,
    in_stock: true,
    stock_quantity: 78,
    tags: ["smraza", "esp32", "starter-kit", "20-projects", "wifi", "iot-kit"],
    specs: {
      board: "ESP32 DevKit V1",
      components: "150+ pieces",
      projects: "20 IoT projects",
      includes: "OLED, DHT11, relay, servo",
      connectivity: "Wi-Fi, Bluetooth examples",
      tutorial: "PDF guide with code",
      app: "Blynk app examples",
      storage: "Plastic organizer",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Robotics (3)
  {
    id: "iot-078",
    name: "L298N Dual H-Bridge Motor Driver Module (5-Pack)",
    brand: "HiLetgo",
    category: "development_kit",
    subcategory: "motor_driver",
    price: 14,
    rating: 4.1,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 445,
    tags: ["l298n", "motor-driver", "h-bridge", "dual", "5-pack", "stepper", "dc-motor"],
    specs: {
      channels: "Dual H-bridge",
      voltage: "5-35V DC",
      current: "2A per channel, 4A peak",
      motors: "2 DC motors or 1 stepper",
      control: "TTL logic 5V/3.3V",
      protection: "Diode protection, heatsink",
      pwm: "Speed control support",
      package: "5 modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-079",
    name: "4WD Smart Robot Car Kit with Arduino Uno",
    brand: "DAOKI",
    category: "development_kit",
    subcategory: "robot_kit",
    price: 38,
    rating: 3.8,
    review_count: 445,
    in_stock: true,
    stock_quantity: 56,
    tags: ["robot-car", "4wd", "arduino", "smart-car", "obstacle-avoidance", "daoki"],
    specs: {
      drive: "4WD with 4x TT motors",
      chassis: "Acrylic platform",
      controller: "Uno R3 compatible included",
      sensors: "Ultrasonic + servo mount",
      power: "18650 battery holder",
      features: "Obstacle avoidance, line follow",
      assembly: "DIY construction",
      expansion: "Sensor mounting points",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-080",
    name: "6-DOF Robotic Arm Kit with Servos for Arduino",
    brand: "KeeYees",
    category: "development_kit",
    subcategory: "robot_arm",
    price: 48,
    original_price: 65,
    rating: 3.5,
    review_count: 178,
    in_stock: false,
    stock_quantity: 0,
    tags: ["robotic-arm", "6-dof", "servo", "arduino", "manipulator", "diy"],
    specs: {
      dof: "6 degrees of freedom",
      servos: "6x MG996R servos included",
      material: "ABS plastic parts",
      controller: "Arduino compatible",
      gripper: "Claw gripper included",
      power: "5V 4A power supply needed",
      control: "Joystick or serial control",
      assembly: "Screw-together assembly",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // ========== COMPONENTS / MODULES (20 products) ==========

  // Displays (5)
  {
    id: "iot-081",
    name: "0.96\" I2C IIC OLED Display 128x64 SSD1306 (5-Pack)",
    brand: "Generic",
    category: "component",
    subcategory: "display",
    price: 16,
    rating: 4.2,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 445,
    tags: ["oled", "0.96-inch", "128x64", "ssd1306", "i2c", "5-pack", "display"],
    specs: {
      size: "0.96 inch diagonal",
      resolution: "128x64 pixels",
      driver: "SSD1306",
      interface: "I2C (4-pin)",
      address: "0x3C or 0x3D",
      voltage: "3.3V-5V",
      color: "White or blue/yellow",
      library: "Adafruit SSD1306, u8g2",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-082",
    name: "1.3\" I2C OLED Display 128x64 SH1106 White",
    brand: "DAOKI",
    category: "component",
    subcategory: "display",
    price: 8,
    rating: 4.0,
    review_count: 567,
    in_stock: true,
    stock_quantity: 234,
    tags: ["oled", "1.3-inch", "128x64", "sh1106", "i2c", "white", "larger"],
    specs: {
      size: "1.3 inch diagonal",
      resolution: "128x64 pixels",
      driver: "SH1106",
      interface: "I2C",
      address: "0x3C",
      voltage: "3.3V-5V",
      color: "White",
      viewing_angle: "160 degrees",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-083",
    name: "2.4\" TFT LCD Touch Screen 240x320 with SD Card",
    brand: "HiLetgo",
    category: "component",
    subcategory: "display",
    price: 12,
    rating: 3.7,
    review_count: 678,
    in_stock: true,
    stock_quantity: 123,
    tags: ["tft", "2.4-inch", "touch", "240x320", "ili9341", "uno-shield", "display"],
    specs: {
      size: "2.4 inch diagonal",
      resolution: "240x320 pixels",
      driver: "ILI9341",
      touch: "Resistive touchscreen",
      interface: "8-bit parallel",
      sd_card: "MicroSD slot onboard",
      form_factor: "Arduino Uno shield",
      voltage: "5V compatible",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-084",
    name: "LCD1602 I2C Blue Backlight Display Module (3-Pack)",
    brand: "KeeYees",
    category: "component",
    subcategory: "display",
    price: 13,
    rating: 4.1,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 312,
    tags: ["lcd", "1602", "16x2", "i2c", "blue", "backlight", "3-pack", "character"],
    specs: {
      display: "16 characters x 2 lines",
      interface: "I2C with PCF8574",
      address: "0x27 or 0x3F",
      backlight: "Blue LED",
      voltage: "5V",
      library: "LiquidCrystal_I2C",
      package: "3 displays",
      pins: "4-pin connection",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-085",
    name: "WS2812B 5050 RGB LED Strip 5m 300 LEDs IP65 Waterproof",
    brand: "Generic",
    category: "component",
    subcategory: "led_strip",
    price: 18,
    original_price: 28,
    rating: 3.9,
    review_count: 890,
    in_stock: true,
    stock_quantity: 156,
    tags: ["ws2812b", "neopixel-compatible", "rgb", "led-strip", "5m", "300-leds", "ip65"],
    specs: {
      leds: "300 WS2812B 5050 RGB LEDs",
      length: "5 meters",
      density: "60 LEDs/meter",
      waterproof: "IP65 silicone coating",
      voltage: "5V DC required",
      power: "90W max at full white",
      control: "3-pin, individually addressable",
      library: "Adafruit NeoPixel, FastLED",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Motors/Drivers (4)
  {
    id: "iot-086",
    name: "SG90 9g Micro Servo Motor (10-Pack)",
    brand: "Generic",
    category: "component",
    subcategory: "servo",
    price: 14,
    rating: 3.9,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 567,
    tags: ["sg90", "9g", "micro-servo", "10-pack", "tower-pro-compatible", "cheap"],
    specs: {
      weight: "9 grams",
      torque: "1.8 kg/cm at 4.8V",
      speed: "0.12s/60° at 4.8V",
      rotation: "180 degrees",
      voltage: "4.8V-6V",
      connector: "3-pin JR style",
      gear_material: "Nylon",
      package: "10 servos with horns",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-087",
    name: "MG996R High Torque Metal Gear Servo (5-Pack)",
    brand: "HiLetgo",
    category: "component",
    subcategory: "servo",
    price: 28,
    rating: 4.0,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 234,
    tags: ["mg996r", "high-torque", "metal-gear", "servo", "5-pack", "robotics"],
    specs: {
      weight: "55 grams",
      torque: "10 kg/cm at 6V",
      speed: "0.17s/60° at 6V",
      rotation: "180 degrees",
      voltage: "4.8V-7.2V",
      gears: "Metal gear train",
      connector: "3-pin JR style",
      package: "5 servos with horns",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-088",
    name: "28BYJ-48 5V Stepper Motor with ULN2003 Driver (5-Pack)",
    brand: "DAOKI",
    category: "component",
    subcategory: "stepper_motor",
    price: 16,
    rating: 4.1,
    review_count: 1456,
    in_stock: true,
    stock_quantity: 312,
    tags: ["28byj-48", "stepper", "5v", "uln2003", "5-pack", "arduino", "precise"],
    specs: {
      type: "4-phase unipolar stepper",
      voltage: "5V DC",
      steps_per_rev: "2048 steps (with gearbox)",
      gear_ratio: "64:1",
      torque: "34 mN/m",
      driver: "ULN2003 board included",
      interface: "4-pin to driver board",
      package: "5 motors + 5 drivers",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-089",
    name: "A4988 Stepper Motor Driver Module with Heatsink (5-Pack)",
    brand: "KeeYees",
    category: "component",
    subcategory: "stepper_driver",
    price: 9,
    rating: 3.8,
    review_count: 890,
    in_stock: false,
    stock_quantity: 0,
    tags: ["a4988", "stepper-driver", "pololu-compatible", "heatsink", "5-pack", "cnc"],
    specs: {
      chip: "A4988 DMOS microstepping",
      current: "1A per phase, 2A with cooling",
      microstepping: "Full, 1/2, 1/4, 1/8, 1/16",
      voltage: "8V-35V motor supply",
      logic: "3.3V or 5V",
      protection: "Over-temperature, short-circuit",
      heatsink: "Included per module",
      package: "5 drivers with heatsinks",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Wireless Modules (4)
  {
    id: "iot-090",
    name: "NRF24L01+ 2.4GHz Wireless Transceiver Module (10-Pack)",
    brand: "Generic",
    category: "component",
    subcategory: "wireless_module",
    price: 14,
    rating: 4.1,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 445,
    tags: ["nrf24l01", "2.4ghz", "wireless", "transceiver", "10-pack", "spi", "low-cost"],
    specs: {
      frequency: "2.4GHz ISM band",
      data_rate: "250kbps, 1Mbps, 2Mbps",
      range: "100m line of sight",
      channels: "125 selectable channels",
      interface: "SPI",
      voltage: "3.3V logic required",
      features: "Enhanced ShockBurst",
      package: "10 modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-091",
    name: "NRF24L01+ with PA+LNA External Antenna 2.4GHz (5-Pack)",
    brand: "HiLetgo",
    category: "component",
    subcategory: "wireless_module",
    price: 22,
    rating: 4.0,
    review_count: 890,
    in_stock: true,
    stock_quantity: 156,
    tags: ["nrf24l01", "pa-lna", "2.4ghz", "long-range", "external-antenna", "5-pack"],
    specs: {
      frequency: "2.4GHz with PA+LNA",
      range: "1000m+ line of sight",
      power_amplifier: "Built-in PA",
      low_noise_amp: "Built-in LNA",
      antenna: "2dBi external included",
      interface: "SPI",
      voltage: "3.3V",
      package: "5 long-range modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-092",
    name: "HC-05 Bluetooth Serial Module Master/Slave (5-Pack)",
    brand: "DAOKI",
    category: "component",
    subcategory: "bluetooth_module",
    price: 18,
    rating: 3.9,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 289,
    tags: ["hc-05", "bluetooth", "serial", "master-slave", "5-pack", "wireless", "uart"],
    specs: {
      version: "Bluetooth 2.0+EDR",
      modes: "Master or Slave configurable",
      range: "10 meters class 2",
      interface: "UART TTL",
      baud: "9600 default, up to 1.3Mbps",
      voltage: "3.3V-6V",
      pairing: "AT command configurable",
      package: "5 modules with breakout",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-093",
    name: "SIM800L GSM GPRS Module with Antenna (3-Pack)",
    brand: "KeeYees",
    category: "component",
    subcategory: "gsm_module",
    price: 18,
    original_price: 28,
    rating: 3.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 67,
    tags: ["sim800l", "gsm", "gprs", "2g", "sms", "sim", "3-pack", "cellular"],
    specs: {
      network: "Quad-band GSM/GPRS",
      bands: "850/900/1800/1900 MHz",
      data: "GPRS multi-slot class 10",
      features: "SMS, MMS, HTTP, TCP/IP",
      interface: "UART TTL",
      voltage: "3.4V-4.4V (needs stable 4V)",
      sim: "Micro SIM slot",
      package: "3 modules with antennas",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Power Modules (4)
  {
    id: "iot-094",
    name: "LM2596 DC-DC Buck Converter Adjustable 3A (10-Pack)",
    brand: "Generic",
    category: "component",
    subcategory: "power_module",
    price: 14,
    rating: 4.2,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 567,
    tags: ["lm2596", "buck-converter", "dc-dc", "step-down", "3a", "10-pack", "adjustable"],
    specs: {
      input: "4V-40V DC",
      output: "1.23V-37V adjustable",
      current: "3A max, 2A continuous",
      efficiency: "Up to 92%",
      switching: "150kHz fixed",
      display: "Some with voltmeter",
      protection: "Overheat, short-circuit",
      package: "10 converters",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-095",
    name: "MP1584EN Mini DC-DC Buck Converter 3A (10-Pack)",
    brand: "HiLetgo",
    category: "component",
    subcategory: "power_module",
    price: 12,
    rating: 4.0,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 445,
    tags: ["mp1584", "buck-converter", "mini", "dc-dc", "3a", "10-pack", "compact"],
    specs: {
      input: "4.5V-28V DC",
      output: "0.8V-20V adjustable",
      current: "3A max",
      efficiency: "Up to 96%",
      switching: "1.5MHz",
      size: "22mm x 17mm",
      features: "Synchronous rectification",
      package: "10 mini converters",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-096",
    name: "MT3608 Boost Converter 2A Step-Up Module (10-Pack)",
    brand: "DAOKI",
    category: "component",
    subcategory: "power_module",
    price: 10,
    rating: 3.9,
    review_count: 890,
    in_stock: true,
    stock_quantity: 312,
    tags: ["mt3608", "boost", "step-up", "converter", "2a", "10-pack", "lithium"],
    specs: {
      input: "2V-24V DC",
      output: "5V-28V adjustable",
      current: "2A max switch",
      efficiency: "Up to 93%",
      switching: "1.2MHz",
      application: "Li-ion boost, LED driver",
      protection: "Thermal shutdown",
      package: "10 boost converters",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-097",
    name: "TP4056 Li-ion Battery Charger Module USB-C (10-Pack)",
    brand: "KeeYees",
    category: "component",
    subcategory: "battery_charger",
    price: 8,
    rating: 4.1,
    review_count: 2345,
    in_stock: false,
    stock_quantity: 0,
    tags: ["tp4056", "charger", "li-ion", "lithium", "usb-c", "18650", "10-pack"],
    specs: {
      chip: "TP4056 linear charger",
      input: "USB-C 5V or 4.5V-5.5V",
      charge_current: "1A default",
      battery: "Single cell Li-ion 18650",
      protection: "DW01A + FS8205 protection",
      features: "Charge LED indicators",
      safety: "Overcharge, overdischarge, short",
      package: "10 charger modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // Other (3)
  {
    id: "iot-098",
    name: "MB102 Breadboard Power Supply Module 3.3V/5V (5-Pack)",
    brand: "Generic",
    category: "component",
    subcategory: "breadboard_supply",
    price: 10,
    rating: 4.2,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 445,
    tags: ["mb102", "breadboard", "power-supply", "3.3v", "5v", "5-pack", "prototyping"],
    specs: {
      input: "6.5V-12V DC or USB 5V",
      output: "3.3V and 5V regulated",
      current: "700mA max per rail",
      jacks: "2.1mm DC jack, USB-B",
      switch: "Voltage selector switch",
      leds: "Power indicator LEDs",
      fits: "Standard 830-tie breadboard",
      package: "5 power modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-099",
    name: "PCF8574 I2C IO Expander Module 8-bit (10-Pack)",
    brand: "HiLetgo",
    category: "component",
    subcategory: "io_expander",
    price: 12,
    rating: 4.0,
    review_count: 567,
    in_stock: true,
    stock_quantity: 234,
    tags: ["pcf8574", "i2c", "io-expander", "8-bit", "10-pack", "gpio", "more-pins"],
    specs: {
      io: "8 bidirectional I/O pins",
      interface: "I2C 100kHz",
      addresses: "8 addresses via jumpers",
      base_address: "0x20-0x27",
      interrupt: "Open-drain interrupt",
      voltage: "2.5V-6V",
      current: "25mA sink per pin",
      package: "10 expander modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-100",
    name: "SN65HVD230 CAN Bus Transceiver Module (5-Pack)",
    brand: "DAOKI",
    category: "component",
    subcategory: "can_transceiver",
    price: 14,
    rating: 3.8,
    review_count: 234,
    in_stock: true,
    stock_quantity: 78,
    tags: ["sn65hvd230", "can-bus", "transceiver", "5-pack", "automotive", "industrial"],
    specs: {
      standard: "ISO 11898-2 CAN",
      speed: "Up to 1 Mbps",
      voltage: "3.3V logic",
      protection: "Transient voltage protection",
      modes: "High-speed, slope, standby",
      termination: "120Ω optional",
      temperature: "-40°C to 125°C",
      package: "5 CAN modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },

  // ========== BONUS 5 PRODUCTS (iot-101 to iot-105) ==========

  {
    id: "iot-101",
    name: "DS3231 RTC Real Time Clock Module I2C with Battery (5-Pack)",
    brand: "KeeYees",
    category: "component",
    subcategory: "rtc_module",
    price: 11,
    rating: 4.2,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 312,
    tags: ["ds3231", "rtc", "real-time-clock", "i2c", "high-accuracy", "5-pack", "battery"],
    specs: {
      accuracy: "±2ppm (±5 seconds/month)",
      interface: "I2C 400kHz",
      address: "0x68",
      features: "Temperature compensated",
      battery: "CR2032 included",
      alarms: "2 programmable alarms",
      voltage: "3.3V-5V",
      package: "5 RTC modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-102",
    name: "RFID RC522 Reader Module 13.56MHz with Cards (5-Pack)",
    brand: "Generic",
    category: "component",
    subcategory: "rfid_reader",
    price: 16,
    rating: 4.0,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 445,
    tags: ["rc522", "rfid", "13.56mhz", "reader", "nfc", "mifare", "5-pack", "access"],
    specs: {
      frequency: "13.56MHz",
      standard: "ISO 14443A",
      cards: "MIFARE Classic 1K supported",
      interface: "SPI, I2C, UART",
      range: "0-60mm typical",
      voltage: "2.5V-3.3V",
      included: "1 card + 1 fob per module",
      package: "5 readers with cards",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-103",
    name: "MAX7219 LED Dot Matrix Display Module 8x32 (4-Pack)",
    brand: "HiLetgo",
    category: "component",
    subcategory: "led_matrix",
    price: 18,
    rating: 4.1,
    review_count: 890,
    in_stock: true,
    stock_quantity: 156,
    tags: ["max7219", "led-matrix", "8x32", "dot-matrix", "4-pack", "scrolling", "display"],
    specs: {
      configuration: "4x MAX7219 cascaded",
      resolution: "8 rows x 32 columns",
      led_color: "Red",
      interface: "SPI",
      voltage: "5V",
      current: "Variable based on LEDs",
      library: "MD_MAX72xx, LedControl",
      applications: "Scrolling text, animations",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-104",
    name: "GY-521 MPU6050 3-Axis Accelerometer Gyro Module (10-Pack)",
    brand: "DAOKI",
    category: "sensor",
    subcategory: "imu_sensor",
    price: 22,
    rating: 4.0,
    review_count: 1567,
    in_stock: false,
    stock_quantity: 0,
    tags: ["gy-521", "mpu6050", "accelerometer", "gyroscope", "6-axis", "10-pack", "imu"],
    specs: {
      accelerometer: "±2g, ±4g, ±8g, ±16g",
      gyroscope: "±250, ±500, ±1000, ±2000 °/s",
      interface: "I2C",
      address: "0x68 (default), 0x69",
      voltage: "3.3V-5V",
      dmp: "Digital Motion Processor",
      interrupt: "Motion detection interrupt",
      package: "10 GY-521 modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-105",
    name: "5V Active Buzzer Alarm Module for Arduino (20-Pack)",
    brand: "Generic",
    category: "component",
    subcategory: "buzzer",
    price: 9,
    rating: 3.9,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 567,
    tags: ["buzzer", "active", "5v", "alarm", "20-pack", "sound", "beep", "arduino"],
    specs: {
      type: "Active buzzer (built-in oscillator)",
      voltage: "3.3V-5V DC",
      current: "<25mA",
      frequency: "2.3kHz ±300Hz",
      sound_level: ">85dB at 10cm",
      control: "Digital HIGH to sound",
      mounting: "PCB mount with holes",
      package: "20 buzzer modules",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
];

// Export count for logging
export const productCount = products.length;
