/**
 * IoTMarket Products - IoT and Maker Electronics (Untrusted)
 * 
 * THIS IS A SAMPLE FILE WITH 10 PRODUCTS.
 * 
 * TO GENERATE 100+ PRODUCTS:
 * 1. Copy the generation prompt from: ./product-generation-prompt.md
 * 2. Use an LLM (Claude, GPT, etc.) to generate products
 * 3. Replace this file contents with the generated products
 */

import { Product } from "./types.js";

export const products: Product[] = [
  {
    id: "iot-001",
    name: "Raspberry Pi 5 8GB Starter Kit",
    brand: "Raspberry Pi",
    category: "microcontroller",
    subcategory: "single_board_computer",
    price: 149,
    original_price: 189,
    rating: 4.2,
    review_count: 89,
    in_stock: true,
    stock_quantity: 23,
    tags: ["raspberry-pi", "rpi5", "sbc", "8gb", "starter-kit", "diy", "python"],
    specs: {
      processor: "Broadcom BCM2712 2.4GHz quad-core",
      memory: "8GB LPDDR4X",
      storage: "MicroSD slot (card included)",
      connectivity: "Dual-band Wi-Fi, Bluetooth 5.0, Gigabit Ethernet",
      ports: "2x HDMI 4K, 2x USB 3.0, 2x USB 2.0, PCIe 2.0",
      power: "USB-C 5V 5A (27W PD supported)",
      gpio: "40-pin GPIO header",
      includes: "Case, heatsink, fan, 64GB SD, power supply",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-002",
    name: "Arduino Uno R4 WiFi",
    brand: "Arduino",
    category: "microcontroller",
    subcategory: "development_board",
    price: 27,
    rating: 4.4,
    review_count: 234,
    in_stock: true,
    stock_quantity: 67,
    tags: ["arduino", "uno", "r4", "wifi", "microcontroller", "beginner", "led-matrix"],
    specs: {
      processor: "Renesas RA4M1 32-bit Cortex-M4",
      clock: "48MHz",
      memory: "32KB SRAM, 256KB Flash",
      connectivity: "ESP32-S3 Wi-Fi and Bluetooth",
      io: "14 digital, 6 analog, 6 PWM",
      features: "12x8 LED matrix, Qwiic connector",
      voltage: "5V logic, 3.3V I/O capable",
      programming: "Arduino IDE, USB-C",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-003",
    name: "ESP32 DevKit V1 30-pin",
    brand: "Espressif",
    category: "microcontroller",
    subcategory: "wifi_module",
    price: 8,
    rating: 4.3,
    review_count: 567,
    in_stock: true,
    stock_quantity: 145,
    tags: ["esp32", "espressif", "wifi", "bluetooth", "iot", "cheap", "micropython"],
    specs: {
      processor: "ESP32-D0WDQ6 dual-core",
      clock: "Up to 240MHz",
      memory: "520KB SRAM, 4MB Flash",
      connectivity: "802.11 b/g/n Wi-Fi, Bluetooth 4.2",
      io: "30 GPIO pins, 18 ADC channels",
      interfaces: "SPI, I2C, UART, I2S, PWM, CAN",
      voltage: "3.3V logic, 5V tolerant inputs",
      programming: "Arduino, MicroPython, ESP-IDF",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-004",
    name: "DHT22 AM2302 Temperature Humidity Sensor",
    brand: "Generic",
    category: "sensor",
    subcategory: "environmental_sensor",
    price: 6,
    rating: 3.9,
    review_count: 892,
    in_stock: true,
    stock_quantity: 234,
    tags: ["dht22", "am2302", "sensor", "temperature", "humidity", "arduino", "cheap"],
    specs: {
      temperature_range: "-40°C to 80°C",
      temperature_accuracy: "±0.5°C",
      humidity_range: "0-100% RH",
      humidity_accuracy: "±2-5%",
      sampling: "0.5Hz (every 2 seconds)",
      voltage: "3.3V - 6V DC",
      current: "2.5mA max",
      output: "Digital single-bus",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-005",
    name: "HC-SR04 Ultrasonic Distance Sensor",
    brand: "Generic",
    category: "sensor",
    subcategory: "proximity_sensor",
    price: 3,
    rating: 4.0,
    review_count: 723,
    in_stock: true,
    stock_quantity: 312,
    tags: ["hc-sr04", "ultrasonic", "sensor", "distance", "robotics", "cheap", "arduino"],
    specs: {
      range: "2cm to 400cm (4 meters)",
      accuracy: "±3mm",
      angle: "15 degrees cone",
      trigger: "10us TTL pulse",
      echo: "TTL pulse proportional to distance",
      voltage: "5V DC",
      current: "15mA",
      frequency: "40kHz",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-006",
    name: "SONOFF Zigbee 3.0 USB Dongle Plus",
    brand: "SONOFF",
    category: "smart_home",
    subcategory: "zigbee_hub",
    price: 29,
    rating: 4.1,
    review_count: 445,
    in_stock: true,
    stock_quantity: 89,
    tags: ["sonoff", "zigbee", "usb", "dongle", "hub", "home-assistant", "cc2652p"],
    specs: {
      chip: "TI CC2652P",
      protocol: "Zigbee 3.0",
      antenna: "External 3dBi gain",
      range: "Up to 100m line of sight",
      compatibility: "Home Assistant, Zigbee2MQTT, ZHA",
      usb: "USB-A with CH340 chip",
      flashing: "Pre-flashed with coordinator firmware",
      features: "Supports 100+ devices, OTA updates",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-007",
    name: "Raspberry Pi Zero 2 W",
    brand: "Raspberry Pi",
    category: "microcontroller",
    subcategory: "compact_sbc",
    price: 15,
    original_price: 25,
    rating: 4.4,
    review_count: 567,
    in_stock: true,
    stock_quantity: 45,
    tags: ["raspberry-pi", "pi-zero", "compact", "wifi", "bluetooth", "low-power"],
    specs: {
      processor: "BCM2710A1 1GHz quad-core (RP3A0)",
      memory: "512MB LPDDR2",
      connectivity: "2.4GHz Wi-Fi, Bluetooth 4.2",
      ports: "1x Micro USB data, 1x Mini HDMI, 1x Micro USB power",
      storage: "MicroSD card slot",
      gpio: "40-pin HAT-compatible header",
      power: "5V 2.5A via Micro USB",
      size: "65mm x 30mm",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-008",
    name: "BME280 Temperature Pressure Humidity Sensor",
    brand: "Bosch",
    category: "sensor",
    subcategory: "environmental_sensor",
    price: 5,
    rating: 4.2,
    review_count: 334,
    in_stock: false,
    stock_quantity: 0,
    tags: ["bme280", "bosch", "sensor", "temperature", "pressure", "humidity", "i2c", "spi"],
    specs: {
      temperature: "-40°C to 85°C, ±1.0°C accuracy",
      humidity: "0-100% RH, ±3% accuracy",
      pressure: "300-1100 hPa, ±1 hPa accuracy",
      altitude: "Calculated from pressure",
      interfaces: "I2C (default) or SPI",
      voltage: "1.8V - 5V DC",
      current: "3.6uA @ 1Hz sampling",
      package: "Breakout board with level shifter",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-009",
    name: "LoRaWAN Gateway Development Kit",
    brand: "Heltec",
    category: "iot_kit",
    subcategory: "lora_gateway",
    price: 89,
    rating: 3.7,
    review_count: 67,
    in_stock: true,
    stock_quantity: 12,
    tags: ["heltec", "lora", "lorawan", "gateway", "iot", "long-range", "915mhz"],
    specs: {
      chip: "ESP32-S3 + SX1302 LoRa concentrator",
      frequency: "915MHz (US) / 868MHz (EU)",
      range: "Up to 15km line of sight",
      connectivity: "Wi-Fi, Ethernet, 4G optional",
      backhaul: "Wi-Fi, Ethernet, 4G LTE",
      software: "Compatible with TTN, ChirpStack",
      power: "5V USB-C or PoE",
      includes: "Antenna, case, USB cable",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
  {
    id: "iot-010",
    name: "ESP32-CAM WiFi Bluetooth Camera Module",
    brand: "Espressif",
    category: "smart_home",
    subcategory: "camera_module",
    price: 12,
    rating: 3.8,
    review_count: 445,
    in_stock: true,
    stock_quantity: 78,
    tags: ["esp32-cam", "camera", "wifi", "ai-thinker", "ov2640", "iot", "surveillance"],
    specs: {
      processor: "ESP32-S dual-core",
      camera: "OV2640 2MP",
      resolution: "1600x1200 max",
      connectivity: "802.11 b/g/n Wi-Fi, Bluetooth 4.2",
      storage: "MicroSD card slot up to 4GB",
      io: "9 GPIO pins, UART, SPI, I2C, PWM",
      power: "5V via GPIO or USB-TTL",
      features: "Face recognition, image streaming",
    },
    retailer: "IoTMarket",
    trust_level: "untrusted",
  },
];

// Export count for logging
export const productCount = products.length;
