/**
 * GadgetZone Products - Consumer Mobile Electronics
 * 100+ products across smartphones, tablets, audio, charging, and wearables
 */

import { Product } from "./types.js";

export const products: Product[] = [
  // ========== SMARTPHONES (35 products) ==========
  
  // iPhones (10)
  {
    id: "gz-001",
    name: "iPhone 15 Pro Max 256GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 1199,
    rating: 4.7,
    review_count: 3421,
    in_stock: true,
    stock_quantity: 67,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "oled", "premium", "pro-max"],
    specs: {
      display: "6.7-inch Super Retina XDR OLED 120Hz",
      processor: "A17 Pro chip",
      storage: "256GB",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto 5x",
      battery: "4422mAh, up to 29 hours video",
      charging: "USB-C, MagSafe, Qi2",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Dynamic Island, Action button, Titanium",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-002",
    name: "iPhone 15 Pro 128GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 999,
    rating: 4.6,
    review_count: 2890,
    in_stock: true,
    stock_quantity: 89,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "pro", "compact"],
    specs: {
      display: "6.1-inch Super Retina XDR OLED 120Hz",
      processor: "A17 Pro chip",
      storage: "128GB",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto 3x",
      battery: "3274mAh, up to 23 hours video",
      charging: "USB-C, MagSafe, Qi2",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Dynamic Island, Action button, Titanium",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-003",
    name: "iPhone 15 Plus 256GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 899,
    original_price: 999,
    rating: 4.5,
    review_count: 1456,
    in_stock: true,
    stock_quantity: 54,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "plus", "large-screen"],
    specs: {
      display: "6.7-inch Super Retina XDR OLED",
      processor: "A16 Bionic chip",
      storage: "256GB",
      camera: "48MP Main + 12MP Ultra Wide",
      battery: "4383mAh, up to 26 hours video",
      charging: "USB-C, MagSafe, Qi2",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "Dynamic Island, Ceramic Shield, Aluminum",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-004",
    name: "iPhone 15 128GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 799,
    rating: 4.5,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 76,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "standard"],
    specs: {
      display: "6.1-inch Super Retina XDR OLED",
      processor: "A16 Bionic chip",
      storage: "128GB",
      camera: "48MP Main + 12MP Ultra Wide",
      battery: "3349mAh, up to 20 hours video",
      charging: "USB-C, MagSafe, Qi2",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "Dynamic Island, Ceramic Shield, Aluminum",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-005",
    name: "iPhone 14 Pro Max 256GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 999,
    original_price: 1199,
    rating: 4.7,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 34,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "pro-max", "previous-gen"],
    specs: {
      display: "6.7-inch Super Retina XDR OLED 120Hz",
      processor: "A16 Bionic chip",
      storage: "256GB",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      battery: "4323mAh, up to 29 hours video",
      charging: "Lightning, MagSafe, Qi",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "Dynamic Island, Always-On Display",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-006",
    name: "iPhone 14 Pro 128GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 899,
    original_price: 999,
    rating: 4.6,
    review_count: 4234,
    in_stock: true,
    stock_quantity: 28,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "pro", "previous-gen"],
    specs: {
      display: "6.1-inch Super Retina XDR OLED 120Hz",
      processor: "A16 Bionic chip",
      storage: "128GB",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      battery: "3200mAh, up to 23 hours video",
      charging: "Lightning, MagSafe, Qi",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "Dynamic Island, Always-On Display",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-007",
    name: "iPhone 14 Plus 256GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 749,
    original_price: 899,
    rating: 4.4,
    review_count: 1890,
    in_stock: true,
    stock_quantity: 45,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "plus", "large-screen"],
    specs: {
      display: "6.7-inch Super Retina XDR OLED",
      processor: "A15 Bionic chip",
      storage: "256GB",
      camera: "12MP Dual Camera System",
      battery: "4325mAh, up to 26 hours video",
      charging: "Lightning, MagSafe, Qi",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "Ceramic Shield, Aluminum, Action mode",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-008",
    name: "iPhone 14 128GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 699,
    original_price: 799,
    rating: 4.5,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 67,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "standard"],
    specs: {
      display: "6.1-inch Super Retina XDR OLED",
      processor: "A15 Bionic chip",
      storage: "128GB",
      camera: "12MP Dual Camera System",
      battery: "3279mAh, up to 20 hours video",
      charging: "Lightning, MagSafe, Qi",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "Ceramic Shield, Aluminum, Action mode",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-009",
    name: "iPhone 13 128GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 599,
    original_price: 699,
    rating: 4.6,
    review_count: 8923,
    in_stock: true,
    stock_quantity: 123,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "budget-friendly"],
    specs: {
      display: "6.1-inch Super Retina XDR OLED",
      processor: "A15 Bionic chip",
      storage: "128GB",
      camera: "12MP Dual Camera System",
      battery: "3227mAh, up to 19 hours video",
      charging: "Lightning, MagSafe, Qi",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.0",
      features: "Cinematic mode, Ceramic Shield",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-010",
    name: "iPhone SE 2022 64GB",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 379,
    original_price: 429,
    rating: 4.3,
    review_count: 4567,
    in_stock: true,
    stock_quantity: 89,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "compact", "budget"],
    specs: {
      display: "4.7-inch Retina HD LCD",
      processor: "A15 Bionic chip",
      storage: "64GB",
      camera: "12MP Single Camera",
      battery: "2018mAh, up to 15 hours video",
      charging: "Lightning, Qi wireless",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.0",
      features: "Touch ID, Compact design, Classic",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Samsung (10)
  {
    id: "gz-011",
    name: "Samsung Galaxy S24 Ultra 256GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 1299,
    rating: 4.6,
    review_count: 2156,
    in_stock: true,
    stock_quantity: 54,
    tags: ["samsung", "galaxy", "s24", "smartphone", "android", "s-pen", "200mp", "ultra"],
    specs: {
      display: "6.8-inch QHD+ Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      storage: "256GB",
      camera: "200MP Main + 50MP Periscope + 12MP Ultra Wide + 10MP Telephoto",
      battery: "5000mAh",
      charging: "45W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.3",
      features: "S Pen, Galaxy AI, 7 years updates, Titanium frame",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-012",
    name: "Samsung Galaxy S24+ 256GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 999,
    rating: 4.5,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 67,
    tags: ["samsung", "galaxy", "s24", "smartphone", "android", "plus"],
    specs: {
      display: "6.7-inch QHD+ Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      storage: "256GB",
      camera: "50MP Main + 10MP Telephoto + 12MP Ultra Wide",
      battery: "4900mAh",
      charging: "45W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Galaxy AI, 7 years updates, Armor Aluminum",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-013",
    name: "Samsung Galaxy S24 128GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 799,
    rating: 4.5,
    review_count: 1456,
    in_stock: true,
    stock_quantity: 89,
    tags: ["samsung", "galaxy", "s24", "smartphone", "android", "compact"],
    specs: {
      display: "6.2-inch FHD+ Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      storage: "128GB",
      camera: "50MP Main + 10MP Telephoto + 12MP Ultra Wide",
      battery: "4000mAh",
      charging: "25W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Galaxy AI, 7 years updates, Compact flagship",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-014",
    name: "Samsung Galaxy S23 Ultra 256GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 999,
    original_price: 1199,
    rating: 4.6,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 43,
    tags: ["samsung", "galaxy", "s23", "smartphone", "android", "s-pen", "200mp"],
    specs: {
      display: "6.8-inch QHD+ Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 2 for Galaxy",
      storage: "256GB",
      camera: "200MP Main + 10MP Periscope + 12MP Ultra Wide + 10MP Telephoto",
      battery: "5000mAh",
      charging: "45W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "S Pen, Nightography, 4 years updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-015",
    name: "Samsung Galaxy S23+ 256GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 849,
    original_price: 999,
    rating: 4.5,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 56,
    tags: ["samsung", "galaxy", "s23", "smartphone", "android", "plus"],
    specs: {
      display: "6.6-inch FHD+ Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 2 for Galaxy",
      storage: "256GB",
      camera: "50MP Main + 10MP Telephoto + 12MP Ultra Wide",
      battery: "4700mAh",
      charging: "45W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Nightography, 4 years updates, Armor Aluminum",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-016",
    name: "Samsung Galaxy S23 128GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 699,
    original_price: 799,
    rating: 4.4,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 78,
    tags: ["samsung", "galaxy", "s23", "smartphone", "android", "compact"],
    specs: {
      display: "6.1-inch FHD+ Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 2 for Galaxy",
      storage: "128GB",
      camera: "50MP Main + 10MP Telephoto + 12MP Ultra Wide",
      battery: "3900mAh",
      charging: "25W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Nightography, 4 years updates, Compact",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-017",
    name: "Samsung Galaxy A55 5G 128GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 449,
    rating: 4.3,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 156,
    tags: ["samsung", "galaxy", "a-series", "smartphone", "android", "mid-range"],
    specs: {
      display: "6.6-inch FHD+ Super AMOLED 120Hz",
      processor: "Exynos 1480",
      storage: "128GB",
      camera: "50MP Main + 12MP Ultra Wide + 5MP Macro",
      battery: "5000mAh",
      charging: "25W wired",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "IP67, Knox Security, 4 years updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-018",
    name: "Samsung Galaxy A35 5G 128GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 349,
    rating: 4.2,
    review_count: 890,
    in_stock: true,
    stock_quantity: 234,
    tags: ["samsung", "galaxy", "a-series", "smartphone", "android", "budget"],
    specs: {
      display: "6.6-inch FHD+ Super AMOLED 120Hz",
      processor: "Exynos 1380",
      storage: "128GB",
      camera: "50MP Main + 8MP Ultra Wide + 5MP Macro",
      battery: "5000mAh",
      charging: "25W wired",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "IP67, Knox Security, 4 years updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-019",
    name: "Samsung Galaxy A25 5G 128GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 299,
    rating: 4.1,
    review_count: 678,
    in_stock: true,
    stock_quantity: 312,
    tags: ["samsung", "galaxy", "a-series", "smartphone", "android", "entry-level"],
    specs: {
      display: "6.5-inch FHD+ Super AMOLED 120Hz",
      processor: "Exynos 1280",
      storage: "128GB",
      camera: "50MP Main + 8MP Ultra Wide + 2MP Macro",
      battery: "5000mAh",
      charging: "25W wired",
      connectivity: "5G, Wi-Fi 5, Bluetooth 5.3",
      features: "Super AMOLED, 4 years updates, Knox",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-020",
    name: "Samsung Galaxy A15 5G 128GB",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 229,
    rating: 4.0,
    review_count: 456,
    in_stock: true,
    stock_quantity: 456,
    tags: ["samsung", "galaxy", "a-series", "smartphone", "android", "budget"],
    specs: {
      display: "6.5-inch FHD+ Super AMOLED 90Hz",
      processor: "MediaTek Dimensity 6100+",
      storage: "128GB",
      camera: "50MP Main + 5MP Ultra Wide + 2MP Macro",
      battery: "5000mAh",
      charging: "25W wired",
      connectivity: "5G, Wi-Fi 5, Bluetooth 5.3",
      features: "Super AMOLED, 4 years updates, Side fingerprint",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Google Pixel (5)
  {
    id: "gz-021",
    name: "Google Pixel 8 Pro 256GB",
    brand: "Google",
    category: "phone",
    subcategory: "smartphone",
    price: 999,
    original_price: 1059,
    rating: 4.5,
    review_count: 1876,
    in_stock: true,
    stock_quantity: 43,
    tags: ["google", "pixel", "smartphone", "android", "ai", "camera", "tensor"],
    specs: {
      display: "6.7-inch LTPO OLED 120Hz 1-120Hz",
      processor: "Google Tensor G3",
      storage: "256GB",
      camera: "50MP Main + 48MP Telephoto 5x + 48MP Ultra Wide",
      battery: "5050mAh",
      charging: "30W wired, 23W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.3",
      features: "Magic Editor, Best Take, 7 years updates, Temperature sensor",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-022",
    name: "Google Pixel 8 128GB",
    brand: "Google",
    category: "phone",
    subcategory: "smartphone",
    price: 699,
    rating: 4.4,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 67,
    tags: ["google", "pixel", "smartphone", "android", "ai", "camera", "compact"],
    specs: {
      display: "6.2-inch Actua OLED 120Hz",
      processor: "Google Tensor G3",
      storage: "128GB",
      camera: "50MP Main + 12MP Ultra Wide",
      battery: "4575mAh",
      charging: "27W wired, 18W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.3",
      features: "Magic Editor, Audio Magic Eraser, 7 years updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-023",
    name: "Google Pixel 8a 128GB",
    brand: "Google",
    category: "phone",
    subcategory: "smartphone",
    price: 499,
    rating: 4.3,
    review_count: 890,
    in_stock: true,
    stock_quantity: 123,
    tags: ["google", "pixel", "smartphone", "android", "ai", "camera", "budget"],
    specs: {
      display: "6.1-inch Actua OLED 120Hz",
      processor: "Google Tensor G3",
      storage: "128GB",
      camera: "64MP Main + 13MP Ultra Wide",
      battery: "4492mAh",
      charging: "18W wired, 7.5W wireless",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Magic Editor, Best Take, 7 years updates, A-Series",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-024",
    name: "Google Pixel 7a 128GB",
    brand: "Google",
    category: "phone",
    subcategory: "smartphone",
    price: 374,
    original_price: 499,
    rating: 4.4,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 89,
    tags: ["google", "pixel", "smartphone", "android", "ai", "camera", "value"],
    specs: {
      display: "6.1-inch OLED 90Hz",
      processor: "Google Tensor G2",
      storage: "128GB",
      camera: "64MP Main + 13MP Ultra Wide",
      battery: "4385mAh",
      charging: "18W wired, 7.5W wireless",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Photo Unblur, Magic Eraser, 5 years updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-025",
    name: "Google Pixel Fold 256GB",
    brand: "Google",
    category: "phone",
    subcategory: "smartphone",
    price: 1399,
    original_price: 1799,
    rating: 4.2,
    review_count: 567,
    in_stock: false,
    stock_quantity: 0,
    tags: ["google", "pixel", "smartphone", "android", "foldable", "premium"],
    specs: {
      display_outer: "5.8-inch OLED 120Hz",
      display_inner: "7.6-inch OLED 120Hz",
      processor: "Google Tensor G2",
      storage: "256GB",
      camera: "48MP Main + 10.8MP Telephoto + 10.8MP Ultra Wide",
      battery: "4821mAh",
      charging: "30W wired, wireless",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.2",
      features: "Foldable, Tabletop mode, Dual-screen interpreter",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // OnePlus (4)
  {
    id: "gz-026",
    name: "OnePlus 12 256GB",
    brand: "OnePlus",
    category: "phone",
    subcategory: "smartphone",
    price: 799,
    rating: 4.4,
    review_count: 892,
    in_stock: true,
    stock_quantity: 56,
    tags: ["oneplus", "smartphone", "android", "fast-charging", "snapdragon", "hasselblad"],
    specs: {
      display: "6.82-inch 2K ProXDR AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 3",
      memory: "12GB RAM",
      storage: "256GB",
      camera: "50MP Sony LYT-808 + 64MP Periscope + 48MP Ultra Wide",
      battery: "5400mAh",
      charging: "100W wired, 50W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.4",
      features: "Aqua Touch, 4 years OS updates, Hasselblad",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-027",
    name: "OnePlus 12R 256GB",
    brand: "OnePlus",
    category: "phone",
    subcategory: "smartphone",
    price: 499,
    rating: 4.3,
    review_count: 678,
    in_stock: true,
    stock_quantity: 78,
    tags: ["oneplus", "smartphone", "android", "fast-charging", "value", "r-series"],
    specs: {
      display: "6.78-inch AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 2",
      memory: "12GB RAM",
      storage: "256GB",
      camera: "50MP Main + 8MP Ultra Wide + 2MP Macro",
      battery: "5500mAh",
      charging: "100W wired",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.3",
      features: "Aqua Touch, Trinity Engine, Value flagship",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-028",
    name: "OnePlus Open 512GB",
    brand: "OnePlus",
    category: "phone",
    subcategory: "smartphone",
    price: 1399,
    original_price: 1699,
    rating: 4.5,
    review_count: 456,
    in_stock: true,
    stock_quantity: 23,
    tags: ["oneplus", "smartphone", "android", "foldable", "premium", "hasselblad"],
    specs: {
      display_outer: "6.31-inch AMOLED 120Hz",
      display_inner: "7.82-inch AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 2",
      memory: "16GB RAM",
      storage: "512GB",
      camera: "48MP Main + 64MP Periscope + 48MP Ultra Wide",
      battery: "4805mAh",
      charging: "67W wired",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.3",
      features: "Open Canvas, Hasselblad, Gapless hinge",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-029",
    name: "OnePlus Nord 4 256GB",
    brand: "OnePlus",
    category: "phone",
    subcategory: "smartphone",
    price: 429,
    rating: 4.2,
    review_count: 345,
    in_stock: true,
    stock_quantity: 123,
    tags: ["oneplus", "smartphone", "android", "mid-range", "nord", "metal-unibody"],
    specs: {
      display: "6.74-inch AMOLED 120Hz",
      processor: "Snapdragon 7+ Gen 3",
      memory: "12GB RAM",
      storage: "256GB",
      camera: "50MP Main + 8MP Ultra Wide",
      battery: "5500mAh",
      charging: "100W wired",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.4",
      features: "Metal unibody, Aqua Touch, 4 years updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Xiaomi (4)
  {
    id: "gz-030",
    name: "Xiaomi 14 Ultra 512GB",
    brand: "Xiaomi",
    category: "phone",
    subcategory: "smartphone",
    price: 1199,
    rating: 4.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 34,
    tags: ["xiaomi", "smartphone", "android", "leica", "camera", "ultra"],
    specs: {
      display: "6.73-inch LTPO AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 3",
      memory: "16GB RAM",
      storage: "512GB",
      camera: "50MP 1-inch Main + 50MP Periscope + 50MP Telephoto + 50MP Ultra Wide",
      battery: "5000mAh",
      charging: "90W wired, 80W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.4",
      features: "Leica optics, Titanium frame, Satellite comms",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-031",
    name: "Xiaomi 14 256GB",
    brand: "Xiaomi",
    category: "phone",
    subcategory: "smartphone",
    price: 749,
    rating: 4.4,
    review_count: 789,
    in_stock: true,
    stock_quantity: 67,
    tags: ["xiaomi", "smartphone", "android", "leica", "camera", "compact"],
    specs: {
      display: "6.36-inch LTPO AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 3",
      memory: "12GB RAM",
      storage: "256GB",
      camera: "50MP Light Fusion + 50MP Telephoto + 50MP Ultra Wide",
      battery: "4610mAh",
      charging: "90W wired, 50W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.4",
      features: "Leica Summilux lens, Compact flagship",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-032",
    name: "Xiaomi Redmi Note 13 Pro+ 5G 256GB",
    brand: "Xiaomi",
    category: "phone",
    subcategory: "smartphone",
    price: 369,
    rating: 4.2,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 156,
    tags: ["xiaomi", "redmi", "smartphone", "android", "mid-range", "value"],
    specs: {
      display: "6.67-inch AMOLED 120Hz 1.5K",
      processor: "MediaTek Dimensity 7200-Ultra",
      memory: "8GB RAM",
      storage: "256GB",
      camera: "200MP Main + 8MP Ultra Wide + 2MP Macro",
      battery: "5000mAh",
      charging: "120W wired",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "IP68, 200MP camera, Curved display",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-033",
    name: "Xiaomi Redmi Note 13 5G 128GB",
    brand: "Xiaomi",
    category: "phone",
    subcategory: "smartphone",
    price: 229,
    rating: 4.0,
    review_count: 890,
    in_stock: true,
    stock_quantity: 234,
    tags: ["xiaomi", "redmi", "smartphone", "android", "budget", "5g"],
    specs: {
      display: "6.67-inch AMOLED 120Hz",
      processor: "MediaTek Dimensity 6080",
      memory: "6GB RAM",
      storage: "128GB",
      camera: "108MP Main + 8MP Ultra Wide + 2MP Depth",
      battery: "5000mAh",
      charging: "33W wired",
      connectivity: "5G, Wi-Fi 5, Bluetooth 5.3",
      features: "108MP camera, AMOLED, Slim design",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Others (2)
  {
    id: "gz-034",
    name: "Nothing Phone (2) 256GB",
    brand: "Nothing",
    category: "phone",
    subcategory: "smartphone",
    price: 599,
    rating: 4.3,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 45,
    tags: ["nothing", "smartphone", "android", "glyph", "unique", "design"],
    specs: {
      display: "6.7-inch LTPO OLED 120Hz",
      processor: "Snapdragon 8+ Gen 1",
      memory: "12GB RAM",
      storage: "256GB",
      camera: "50MP Main + 50MP Ultra Wide",
      battery: "4700mAh",
      charging: "45W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      features: "Glyph Interface, Nothing OS, Transparent design",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-035",
    name: "ASUS ROG Phone 8 Pro 512GB",
    brand: "ASUS",
    category: "phone",
    subcategory: "smartphone",
    price: 1099,
    rating: 4.6,
    review_count: 678,
    in_stock: true,
    stock_quantity: 28,
    tags: ["asus", "rog", "smartphone", "android", "gaming", "performance"],
    specs: {
      display: "6.78-inch AMOLED 165Hz LTPO",
      processor: "Snapdragon 8 Gen 3",
      memory: "16GB RAM",
      storage: "512GB",
      camera: "50MP Main + 32MP Telephoto + 13MP Ultra Wide",
      battery: "5500mAh",
      charging: "65W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.3",
      features: "AirTrigger buttons, GameCool 8, Mini-LED matrix",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // ========== TABLETS (15 products) ==========
  
  // iPad (6)
  {
    id: "gz-036",
    name: "iPad Pro 12.9-inch M2 256GB WiFi",
    brand: "Apple",
    category: "tablet",
    subcategory: "tablet",
    price: 1099,
    rating: 4.8,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 45,
    tags: ["apple", "ipad", "tablet", "pro", "m2", "large-screen", "productivity"],
    specs: {
      display: "12.9-inch Liquid Retina XDR Mini-LED 120Hz",
      processor: "Apple M2 chip",
      storage: "256GB",
      camera: "12MP Wide + 10MP Ultra Wide + LiDAR",
      battery: "Up to 10 hours",
      charging: "USB-C Thunderbolt 4",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      features: "Face ID, ProMotion, Center Stage, Stage Manager",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-037",
    name: "iPad Pro 11-inch M2 128GB WiFi",
    brand: "Apple",
    category: "tablet",
    subcategory: "tablet",
    price: 799,
    rating: 4.7,
    review_count: 1876,
    in_stock: true,
    stock_quantity: 67,
    tags: ["apple", "ipad", "tablet", "pro", "m2", "compact", "portable"],
    specs: {
      display: "11-inch Liquid Retina LED 120Hz",
      processor: "Apple M2 chip",
      storage: "128GB",
      camera: "12MP Wide + 10MP Ultra Wide + LiDAR",
      battery: "Up to 10 hours",
      charging: "USB-C Thunderbolt 4",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      features: "Face ID, ProMotion, Center Stage, Stage Manager",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-038",
    name: "iPad Air M2 11-inch 128GB WiFi",
    brand: "Apple",
    category: "tablet",
    subcategory: "tablet",
    price: 599,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 89,
    tags: ["apple", "ipad", "tablet", "air", "m2", "balanced", "versatile"],
    specs: {
      display: "11-inch Liquid Retina LED",
      processor: "Apple M2 chip",
      storage: "128GB",
      camera: "12MP Wide (rear), 12MP Ultra Wide (front)",
      battery: "Up to 10 hours",
      charging: "USB-C",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      features: "Touch ID, Apple Pencil Pro support, Landscape camera",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-039",
    name: "iPad Air M2 13-inch 128GB WiFi",
    brand: "Apple",
    category: "tablet",
    subcategory: "tablet",
    price: 799,
    rating: 4.6,
    review_count: 567,
    in_stock: true,
    stock_quantity: 34,
    tags: ["apple", "ipad", "tablet", "air", "m2", "large-screen", "productivity"],
    specs: {
      display: "13-inch Liquid Retina LED",
      processor: "Apple M2 chip",
      storage: "128GB",
      camera: "12MP Wide (rear), 12MP Ultra Wide (front)",
      battery: "Up to 10 hours",
      charging: "USB-C",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      features: "Touch ID, Apple Pencil Pro support, Landscape camera",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-040",
    name: "iPad 10th Gen 64GB WiFi",
    brand: "Apple",
    category: "tablet",
    subcategory: "tablet",
    price: 349,
    original_price: 449,
    rating: 4.4,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 156,
    tags: ["apple", "ipad", "tablet", "standard", "budget-friendly", "everyday"],
    specs: {
      display: "10.9-inch Liquid Retina LED",
      processor: "A14 Bionic chip",
      storage: "64GB",
      camera: "12MP Wide (rear), 12MP Ultra Wide (front)",
      battery: "Up to 10 hours",
      charging: "USB-C",
      connectivity: "Wi-Fi 6, Bluetooth 5.2",
      features: "Touch ID, Landscape stereo speakers, 4 colors",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-041",
    name: "iPad mini 6th Gen 256GB WiFi",
    brand: "Apple",
    category: "tablet",
    subcategory: "tablet",
    price: 599,
    rating: 4.7,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 78,
    tags: ["apple", "ipad", "tablet", "mini", "compact", "portable"],
    specs: {
      display: "8.3-inch Liquid Retina LED",
      processor: "A15 Bionic chip",
      storage: "256GB",
      camera: "12MP Wide (rear), 12MP Ultra Wide (front)",
      battery: "Up to 10 hours",
      charging: "USB-C",
      connectivity: "Wi-Fi 6, Bluetooth 5.0",
      features: "Touch ID, Apple Pencil 2, Compact powerhouse",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Samsung Tablets (5)
  {
    id: "gz-042",
    name: "Samsung Galaxy Tab S9 Ultra 256GB WiFi",
    brand: "Samsung",
    category: "tablet",
    subcategory: "tablet",
    price: 1199,
    rating: 4.6,
    review_count: 890,
    in_stock: true,
    stock_quantity: 34,
    tags: ["samsung", "galaxy-tab", "tablet", "s9", "ultra", "large-screen"],
    specs: {
      display: "14.6-inch Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 2 for Galaxy",
      storage: "256GB",
      camera: "13MP Main + 8MP Ultra Wide (rear), 12MP Dual (front)",
      battery: "11200mAh",
      charging: "45W wired",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      features: "S Pen included, IP68, DeX mode, Vision Booster",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-043",
    name: "Samsung Galaxy Tab S9+ 256GB WiFi",
    brand: "Samsung",
    category: "tablet",
    subcategory: "tablet",
    price: 999,
    rating: 4.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 45,
    tags: ["samsung", "galaxy-tab", "tablet", "s9", "plus", "premium"],
    specs: {
      display: "12.4-inch Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 2 for Galaxy",
      storage: "256GB",
      camera: "13MP Main + 8MP Ultra Wide (rear), 12MP Ultra Wide (front)",
      battery: "10090mAh",
      charging: "45W wired",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      features: "S Pen included, IP68, DeX mode, Vision Booster",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-044",
    name: "Samsung Galaxy Tab S9 128GB WiFi",
    brand: "Samsung",
    category: "tablet",
    subcategory: "tablet",
    price: 719,
    rating: 4.5,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 67,
    tags: ["samsung", "galaxy-tab", "tablet", "s9", "compact", "versatile"],
    specs: {
      display: "11-inch Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 2 for Galaxy",
      storage: "128GB",
      camera: "13MP (rear), 12MP Ultra Wide (front)",
      battery: "8400mAh",
      charging: "45W wired",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      features: "S Pen included, IP68, DeX mode, Vision Booster",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-045",
    name: "Samsung Galaxy Tab S9 FE+ 128GB WiFi",
    brand: "Samsung",
    category: "tablet",
    subcategory: "tablet",
    price: 549,
    rating: 4.3,
    review_count: 456,
    in_stock: true,
    stock_quantity: 89,
    tags: ["samsung", "galaxy-tab", "tablet", "s9", "fe", "value"],
    specs: {
      display: "12.4-inch LCD 90Hz",
      processor: "Exynos 1380",
      storage: "128GB",
      camera: "8MP (rear), 12MP Ultra Wide (front)",
      battery: "10090mAh",
      charging: "45W wired",
      connectivity: "Wi-Fi 6, Bluetooth 5.3",
      features: "S Pen included, DeX mode, IP68",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-046",
    name: "Samsung Galaxy Tab S9 FE 128GB WiFi",
    brand: "Samsung",
    category: "tablet",
    subcategory: "tablet",
    price: 449,
    rating: 4.2,
    review_count: 678,
    in_stock: true,
    stock_quantity: 123,
    tags: ["samsung", "galaxy-tab", "tablet", "s9", "fe", "budget"],
    specs: {
      display: "10.9-inch LCD 90Hz",
      processor: "Exynos 1380",
      storage: "128GB",
      camera: "8MP (rear), 12MP Ultra Wide (front)",
      battery: "8000mAh",
      charging: "45W wired",
      connectivity: "Wi-Fi 6, Bluetooth 5.3",
      features: "S Pen included, DeX mode, IP68",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Other Tablets (4)
  {
    id: "gz-047",
    name: "Amazon Fire HD 10 Plus 32GB",
    brand: "Amazon",
    category: "tablet",
    subcategory: "tablet",
    price: 179,
    rating: 4.1,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 234,
    tags: ["amazon", "fire-hd", "tablet", "budget", "entertainment", "alexa"],
    specs: {
      display: "10.1-inch Full HD LCD",
      processor: "Octa-core 2.0GHz",
      storage: "32GB",
      camera: "5MP (rear), 2MP (front)",
      battery: "Up to 12 hours",
      charging: "USB-C, 9W wireless",
      connectivity: "Wi-Fi 6, Bluetooth 5.0",
      features: "Alexa hands-free, Wireless charging, Made for Amazon",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-048",
    name: "Amazon Fire Max 11 64GB",
    brand: "Amazon",
    category: "tablet",
    subcategory: "tablet",
    price: 229,
    rating: 4.2,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 156,
    tags: ["amazon", "fire", "tablet", "budget", "entertainment", "alexa"],
    specs: {
      display: "11-inch 2K LCD",
      processor: "MediaTek MT8188J Octa-core",
      storage: "64GB",
      camera: "8MP (rear), 8MP (front)",
      battery: "Up to 14 hours",
      charging: "USB-C 15W",
      connectivity: "Wi-Fi 6, Bluetooth 5.3, optional 5G",
      features: "Aluminum unibody, Alexa, Kid mode",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-049",
    name: "Lenovo Tab P12 128GB",
    brand: "Lenovo",
    category: "tablet",
    subcategory: "tablet",
    price: 349,
    rating: 4.0,
    review_count: 890,
    in_stock: true,
    stock_quantity: 78,
    tags: ["lenovo", "tab", "tablet", "mid-range", "productivity"],
    specs: {
      display: "12.7-inch LCD 3K 60Hz",
      processor: "MediaTek Dimensity 7050",
      memory: "8GB RAM",
      storage: "128GB",
      camera: "13MP (rear), 8MP (front)",
      battery: "10200mAh",
      charging: "30W wired",
      connectivity: "Wi-Fi 6, Bluetooth 5.1",
      features: "JBL quad speakers, Precision Pen 2, Lenovo Freestyle",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-050",
    name: "Lenovo Tab M10 Plus Gen 3 64GB",
    brand: "Lenovo",
    category: "tablet",
    subcategory: "tablet",
    price: 169,
    rating: 3.9,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 145,
    tags: ["lenovo", "tab", "tablet", "budget", "family", "kids"],
    specs: {
      display: "10.6-inch 2K LCD",
      processor: "MediaTek Helio G80",
      storage: "64GB",
      camera: "8MP (rear), 8MP (front)",
      battery: "7700mAh",
      charging: "USB-C 20W",
      connectivity: "Wi-Fi 5, Bluetooth 5.0",
      features: "Kids Space, TUV eye care, Dolby Atmos",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // ========== AUDIO (25 products) ==========
  
  // True Wireless Earbuds (10)
  {
    id: "gz-051",
    name: "AirPods Pro 2nd Gen USB-C",
    brand: "Apple",
    category: "audio",
    subcategory: "earbuds",
    price: 249,
    rating: 4.8,
    review_count: 7892,
    in_stock: true,
    stock_quantity: 234,
    tags: ["apple", "airpods", "earbuds", "anc", "wireless", "usb-c", "premium"],
    specs: {
      type: "True wireless earbuds",
      chip: "H2 chip",
      anc: "2x Active Noise Cancellation",
      transparency: "Adaptive Audio, Transparency mode",
      battery: "6 hours + 30 hours case",
      charging: "USB-C, MagSafe, Qi, Apple Watch charger",
      connectivity: "Bluetooth 5.3",
      features: "Precision Finding, Hearing health, Conversation Awareness",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-052",
    name: "AirPods 4 with ANC",
    brand: "Apple",
    category: "audio",
    subcategory: "earbuds",
    price: 179,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 189,
    tags: ["apple", "airpods", "earbuds", "anc", "wireless", "open-fit"],
    specs: {
      type: "True wireless earbuds (open-fit)",
      chip: "H2 chip",
      anc: "Active Noise Cancellation (open-fit)",
      transparency: "Transparency mode",
      battery: "5 hours + 30 hours case",
      charging: "USB-C, MagSafe, Qi, Apple Watch charger",
      connectivity: "Bluetooth 5.3",
      features: "Personalized Spatial Audio, Voice Isolation",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-053",
    name: "Samsung Galaxy Buds3 Pro",
    brand: "Samsung",
    category: "audio",
    subcategory: "earbuds",
    price: 229,
    rating: 4.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 123,
    tags: ["samsung", "galaxy-buds", "earbuds", "anc", "wireless", "ai"],
    specs: {
      type: "True wireless earbuds",
      drivers: "Enhanced 2-way speaker",
      anc: "Adaptive ANC with Galaxy AI",
      battery: "6 hours + 26 hours case (ANC on)",
      charging: "USB-C, wireless, 10min = 1hr",
      connectivity: "Bluetooth 5.4, Samsung Seamless Codec",
      water_resistance: "IP57",
      features: "Blade lights, Interpreter, 360 Audio",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-054",
    name: "Samsung Galaxy Buds FE",
    brand: "Samsung",
    category: "audio",
    subcategory: "earbuds",
    price: 99,
    original_price: 129,
    rating: 4.3,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 234,
    tags: ["samsung", "galaxy-buds", "earbuds", "anc", "wireless", "budget"],
    specs: {
      type: "True wireless earbuds",
      drivers: "One 1-way speaker",
      anc: "Active Noise Cancellation",
      battery: "6 hours + 21 hours case (ANC on)",
      charging: "USB-C, wireless",
      connectivity: "Bluetooth 5.2",
      water_resistance: "IPX2",
      features: "360 Audio, Auto Switch, Bixby voice",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-055",
    name: "Sony WF-1000XM5",
    brand: "Sony",
    category: "audio",
    subcategory: "earbuds",
    price: 299,
    original_price: 349,
    rating: 4.7,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 89,
    tags: ["sony", "wf-1000xm5", "earbuds", "anc", "wireless", "audiophile"],
    specs: {
      type: "True wireless earbuds",
      drivers: "8.4mm Dynamic Driver X",
      anc: "Industry-leading ANC with AI",
      battery: "8 hours + 24 hours case",
      charging: "USB-C, wireless, 3min = 1hr",
      connectivity: "Bluetooth 5.3, LDAC, LE Audio",
      water_resistance: "IPX4",
      features: "Speak-to-Chat, 360 Reality Audio, DSEE Extreme",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-056",
    name: "Sony WF-C700N",
    brand: "Sony",
    category: "audio",
    subcategory: "earbuds",
    price: 119,
    rating: 4.4,
    review_count: 1890,
    in_stock: true,
    stock_quantity: 156,
    tags: ["sony", "earbuds", "anc", "wireless", "budget", "comfort"],
    specs: {
      type: "True wireless earbuds",
      drivers: "5mm drivers",
      anc: "Digital Noise Cancelling",
      battery: "7.5 hours + 15 hours case",
      charging: "USB-C, 10min = 1hr",
      connectivity: "Bluetooth 5.2",
      water_resistance: "IPX4",
      features: "360 Reality Audio, Multipoint, Ambient Sound",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-057",
    name: "Google Pixel Buds Pro 2",
    brand: "Google",
    category: "audio",
    subcategory: "earbuds",
    price: 229,
    rating: 4.4,
    review_count: 678,
    in_stock: true,
    stock_quantity: 112,
    tags: ["google", "pixel-buds", "earbuds", "anc", "wireless", "tensor"],
    specs: {
      type: "True wireless earbuds",
      chip: "Google Tensor A1",
      anc: "Active Noise Cancellation with Silent Seal 2.0",
      battery: "8 hours + 30 hours case",
      charging: "USB-C, wireless, 15min = 3hr",
      connectivity: "Bluetooth 5.4, multipoint",
      water_resistance: "IP54",
      features: "Gemini, Clear Calling, Volume EQ, Find My Device",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-058",
    name: "Nothing Ear (2)",
    brand: "Nothing",
    category: "audio",
    subcategory: "earbuds",
    price: 149,
    rating: 4.3,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 89,
    tags: ["nothing", "earbuds", "anc", "wireless", "transparent", "design"],
    specs: {
      type: "True wireless earbuds",
      drivers: "11.6mm custom drivers",
      anc: "Active Noise Cancellation up to 40dB",
      battery: "6.3 hours + 29 hours case",
      charging: "USB-C, wireless, 10min = 8hr",
      connectivity: "Bluetooth 5.3, LHDC 5.0",
      water_resistance: "IP54",
      features: "Clear Voice Technology, Dual Connection, Transparent design",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-059",
    name: "Jabra Elite 10 Gen 2",
    brand: "Jabra",
    category: "audio",
    subcategory: "earbuds",
    price: 279,
    rating: 4.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 67,
    tags: ["jabra", "elite", "earbuds", "anc", "wireless", "dolby-atmos"],
    specs: {
      type: "True wireless earbuds",
      drivers: "10mm speakers",
      anc: "Advanced ANC with Dolby Atmos",
      battery: "6 hours + 27 hours case",
      charging: "USB-C, wireless",
      connectivity: "Bluetooth 5.3, LE Audio ready",
      water_resistance: "IP57",
      features: "Dolby Head Tracking, 6-mic call tech, ComfortFit",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-060",
    name: "Jabra Elite 8 Active Gen 2",
    brand: "Jabra",
    category: "audio",
    subcategory: "earbuds",
    price: 199,
    rating: 4.4,
    review_count: 890,
    in_stock: true,
    stock_quantity: 134,
    tags: ["jabra", "elite", "earbuds", "anc", "sports", "durable"],
    specs: {
      type: "True wireless earbuds",
      drivers: "6mm speakers",
      anc: "Adaptive Hybrid ANC",
      battery: "8 hours + 32 hours case",
      charging: "USB-C, wireless",
      connectivity: "Bluetooth 5.3",
      water_resistance: "IP68 (military-grade)",
      features: "ShakeGrip coating, Dolby Audio, SmartCase",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Over-ear Headphones (8)
  {
    id: "gz-061",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "audio",
    subcategory: "headphones",
    price: 399,
    original_price: 449,
    rating: 4.7,
    review_count: 6789,
    in_stock: true,
    stock_quantity: 78,
    tags: ["sony", "wh-1000xm5", "headphones", "anc", "over-ear", "premium"],
    specs: {
      type: "Over-ear wireless headphones",
      drivers: "30mm drivers",
      anc: "Industry-leading ANC with 8 mics",
      battery: "30 hours + 3min quick charge = 3hr",
      charging: "USB-C",
      connectivity: "Bluetooth 5.2, LDAC, multipoint",
      features: "Speak-to-Chat, 360 Reality Audio, DSEE Extreme",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-062",
    name: "Sony WH-CH720N",
    brand: "Sony",
    category: "audio",
    subcategory: "headphones",
    price: 149,
    rating: 4.3,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 145,
    tags: ["sony", "headphones", "anc", "over-ear", "lightweight", "value"],
    specs: {
      type: "Over-ear wireless headphones",
      drivers: "30mm drivers",
      anc: "Digital Noise Cancelling",
      battery: "35 hours",
      charging: "USB-C, 3min = 1hr",
      connectivity: "Bluetooth 5.2, multipoint",
      weight: "192g (lightest ANC headphones)",
      features: "DSEE, Ambient Sound, Voice assistant",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-063",
    name: "Bose QuietComfort Ultra Headphones",
    brand: "Bose",
    category: "audio",
    subcategory: "headphones",
    price: 429,
    rating: 4.6,
    review_count: 1890,
    in_stock: true,
    stock_quantity: 56,
    tags: ["bose", "quietcomfort", "headphones", "anc", "over-ear", "immersive"],
    specs: {
      type: "Over-ear wireless headphones",
      audio: "CustomTune audio calibration",
      anc: "World-class quiet + Immersive Audio",
      battery: "24 hours (18 with Immersive Audio)",
      charging: "USB-C, 15min = 2.5hr",
      connectivity: "Bluetooth 5.3, aptX Adaptive",
      features: "Immersive Audio, Customizable EQ, SimpleSync",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-064",
    name: "Bose QuietComfort Headphones",
    brand: "Bose",
    category: "audio",
    subcategory: "headphones",
    price: 349,
    rating: 4.5,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 89,
    tags: ["bose", "quietcomfort", "headphones", "anc", "over-ear", "classic"],
    specs: {
      type: "Over-ear wireless headphones",
      audio: "High-fidelity audio",
      anc: "Legendary noise cancellation",
      battery: "24 hours",
      charging: "USB-C",
      connectivity: "Bluetooth 5.1, multipoint",
      features: "Adjustable EQ, Audio cable with mic",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-065",
    name: "Apple AirPods Max",
    brand: "Apple",
    category: "audio",
    subcategory: "headphones",
    price: 549,
    rating: 4.6,
    review_count: 4567,
    in_stock: true,
    stock_quantity: 45,
    tags: ["apple", "airpods-max", "headphones", "anc", "over-ear", "spatial"],
    specs: {
      type: "Over-ear wireless headphones",
      drivers: "Apple-designed dynamic driver",
      chip: "Apple H1 chip in each cup",
      anc: "Active Noise Cancellation",
      battery: "20 hours with ANC",
      charging: "Lightning, Smart Case for ultra-low power",
      connectivity: "Bluetooth 5.0, Apple ecosystem",
      features: "Spatial Audio, Digital Crown, Computational audio",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-066",
    name: "Sennheiser Momentum 4 Wireless",
    brand: "Sennheiser",
    category: "audio",
    subcategory: "headphones",
    price: 379,
    original_price: 429,
    rating: 4.5,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 67,
    tags: ["sennheiser", "momentum", "headphones", "anc", "over-ear", "audiophile"],
    specs: {
      type: "Over-ear wireless headphones",
      drivers: "42mm transducers",
      anc: "Adaptive Noise Cancellation",
      battery: "60 hours (record-breaking)",
      charging: "USB-C, 5min = 4hr",
      connectivity: "Bluetooth 5.2, aptX Adaptive, AAC",
      features: "Smart Control app, Customizable sound, Tile finding",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-067",
    name: "JBL Tour One M2",
    brand: "JBL",
    category: "audio",
    subcategory: "headphones",
    price: 299,
    rating: 4.3,
    review_count: 890,
    in_stock: true,
    stock_quantity: 112,
    tags: ["jbl", "tour-one", "headphones", "anc", "over-ear", "spatial"],
    specs: {
      type: "Over-ear wireless headphones",
      drivers: "40mm drivers",
      anc: "True Adaptive ANC",
      battery: "30 hours + 5min = 5hr",
      charging: "USB-C",
      connectivity: "Bluetooth 5.3, LE Audio ready",
      features: "JBL Spatial Sound, Personi-Fi 2.0, 4-mic crystal call",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-068",
    name: "Anker Soundcore Space One",
    brand: "Anker",
    category: "audio",
    subcategory: "headphones",
    price: 99,
    rating: 4.2,
    review_count: 1567,
    in_stock: true,
    stock_quantity: 234,
    tags: ["anker", "soundcore", "headphones", "anc", "over-ear", "budget"],
    specs: {
      type: "Over-ear wireless headphones",
      drivers: "40mm dynamic drivers",
      anc: "Adaptive ANC 2.0, up to 98% noise reduction",
      battery: "40 hours (ANC on), 55 hours (off)",
      charging: "USB-C, 5min = 4hr",
      connectivity: "Bluetooth 5.3, LDAC, multipoint",
      features: "Hi-Res Wireless, Soundcore app, Comfortable fit",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Speakers (7)
  {
    id: "gz-069",
    name: "JBL Flip 6",
    brand: "JBL",
    category: "audio",
    subcategory: "speaker",
    price: 129,
    rating: 4.5,
    review_count: 8901,
    in_stock: true,
    stock_quantity: 189,
    tags: ["jbl", "flip", "speaker", "portable", "waterproof", "party"],
    specs: {
      type: "Portable Bluetooth speaker",
      drivers: "2-way speaker system, racetrack-shaped woofer",
      output: "30W RMS",
      battery: "12 hours",
      charging: "USB-C",
      water_resistance: "IP67",
      connectivity: "Bluetooth 5.1, PartyBoost",
      features: "Bold JBL sound, Multiple colors, Rugged design",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-070",
    name: "JBL Charge 5 Wi-Fi",
    brand: "JBL",
    category: "audio",
    subcategory: "speaker",
    price: 199,
    rating: 4.4,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 123,
    tags: ["jbl", "charge", "speaker", "portable", "waterproof", "powerbank"],
    specs: {
      type: "Portable Bluetooth speaker with Wi-Fi",
      drivers: "Optimized long-excursion driver",
      output: "40W RMS",
      battery: "20 hours + USB powerbank",
      charging: "USB-C, charges devices via USB-A",
      water_resistance: "IP67",
      connectivity: "Bluetooth 5.3, Wi-Fi, AirPlay, Chromecast",
      features: "Self-tuning, Auracast, Multi-room audio",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-071",
    name: "JBL Xtreme 4",
    brand: "JBL",
    category: "audio",
    subcategory: "speaker",
    price: 379,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 67,
    tags: ["jbl", "xtreme", "speaker", "portable", "waterproof", "powerful"],
    specs: {
      type: "Portable Bluetooth speaker",
      drivers: "2 x 70mm woofers + 2 x 20mm tweeters",
      output: "100W RMS",
      battery: "24 hours + replaceable battery pack",
      charging: "USB-C, charges devices",
      water_resistance: "IP67",
      connectivity: "Bluetooth 5.3, Auracast",
      features: "AI Sound Boost, Replaceable battery, Carry strap",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-072",
    name: "Bose SoundLink Flex Gen 2",
    brand: "Bose",
    category: "audio",
    subcategory: "speaker",
    price: 149,
    rating: 4.5,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 156,
    tags: ["bose", "soundlink", "speaker", "portable", "waterproof", "compact"],
    specs: {
      type: "Portable Bluetooth speaker",
      audio: "Bose proprietary transducer",
      features: "PositionIQ, Stereo mode, Party mode",
      battery: "12 hours",
      charging: "USB-C",
      water_resistance: "IP67",
      connectivity: "Bluetooth 5.3, SimpleSync",
      design: "Dustproof, waterproof, floats",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-073",
    name: "Bose SoundLink Max",
    brand: "Bose",
    category: "audio",
    subcategory: "speaker",
    price: 399,
    rating: 4.6,
    review_count: 678,
    in_stock: true,
    stock_quantity: 45,
    tags: ["bose", "soundlink", "speaker", "portable", "premium", "loud"],
    specs: {
      type: "Large portable Bluetooth speaker",
      drivers: "2 transducers + 1 passive radiator",
      battery: "20 hours + USB-C charging for devices",
      charging: "USB-C",
      water_resistance: "IP67",
      connectivity: "Bluetooth 5.4, SimpleSync",
      features: "Bose app, Detachable rope handle, Powder-coated",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-074",
    name: "Sonos Roam 2",
    brand: "Sonos",
    category: "audio",
    subcategory: "speaker",
    price: 179,
    rating: 4.4,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 89,
    tags: ["sonos", "roam", "speaker", "portable", "smart", "multiroom"],
    specs: {
      type: "Portable smart speaker",
      audio: "Two Class-H amplifiers, one tweeter, one mid-woofer",
      battery: "10 hours",
      charging: "USB-C, wireless charging compatible",
      water_resistance: "IP67",
      connectivity: "Wi-Fi, Bluetooth 5.0, AirPlay 2",
      features: "Sonos app, Voice control, Automatic Trueplay",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-075",
    name: "Sonos Move 2",
    brand: "Sonos",
    category: "audio",
    subcategory: "speaker",
    price: 449,
    rating: 4.5,
    review_count: 890,
    in_stock: true,
    stock_quantity: 34,
    tags: ["sonos", "move", "speaker", "portable", "smart", "powerful"],
    specs: {
      type: "Large portable smart speaker",
      audio: "Stereo sound with two angled tweeters + woofer",
      battery: "24 hours",
      charging: "USB-C, wireless charging base included",
      water_resistance: "IP56",
      connectivity: "Wi-Fi, Bluetooth 5.0, AirPlay 2, line-in",
      features: "Sonos app, Voice control, Automatic Trueplay",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // ========== CHARGING (15 products) ==========
  
  // Power Banks (6)
  {
    id: "gz-076",
    name: "Anker Prime 20000mAh 200W",
    brand: "Anker",
    category: "charging",
    subcategory: "power_bank",
    price: 129,
    rating: 4.7,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 89,
    tags: ["anker", "prime", "power-bank", "20000mah", "200w", "laptop", "premium"],
    specs: {
      capacity: "20000mAh / 72Wh",
      output: "200W total (2x USB-C 100W + 1x USB-A)",
      display: "TFT smart display with app control",
      charging: "Recharges in 1hr 15min",
      compatibility: "MacBook Pro, Dell XPS, iPad, iPhone, Galaxy",
      safety: "ActiveShield 3.0, temperature monitoring",
      airline: "TSA approved for carry-on",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-077",
    name: "Anker 737 Power Bank 24000mAh 140W",
    brand: "Anker",
    category: "charging",
    subcategory: "power_bank",
    price: 109,
    rating: 4.7,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 112,
    tags: ["anker", "737", "power-bank", "24000mah", "140w", "laptop", "ganprime"],
    specs: {
      capacity: "24000mAh / 86.4Wh",
      output: "140W total (2x USB-C, 1x USB-A)",
      display: "Smart digital display",
      charging: "Recharges in 52 minutes",
      compatibility: "Laptops, tablets, phones, Nintendo Switch",
      safety: "ActiveShield 2.0 temperature monitoring",
      airline: "TSA approved for carry-on",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-078",
    name: "Anker 733 Power Bank 10000mAh 65W",
    brand: "Anker",
    category: "charging",
    subcategory: "power_bank",
    price: 79,
    rating: 4.5,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 156,
    tags: ["anker", "733", "power-bank", "10000mah", "65w", "hybrid", "charger"],
    specs: {
      capacity: "10000mAh / 36Wh",
      output: "65W total (2-in-1 wall charger + power bank)",
      ports: "2x USB-C, 1x USB-A",
      charging: "Recharges via wall outlet",
      compatibility: "MacBook Air, iPad Pro, iPhone, Galaxy",
      features: "GaN technology, Foldable plug, Compact",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-079",
    name: "Baseus Blade 100W 20000mAh",
    brand: "Baseus",
    category: "charging",
    subcategory: "power_bank",
    price: 89,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 78,
    tags: ["baseus", "blade", "power-bank", "20000mah", "100w", "slim", "laptop"],
    specs: {
      capacity: "20000mAh / 74Wh",
      output: "100W max (2x USB-C + 2x USB-A)",
      display: "LED digital display",
      design: "Ultra-slim 0.7 inch profile",
      charging: "USB-C input 65W, recharges in 1.5hr",
      compatibility: "MacBook, Dell, HP, iPad, iPhone, Steam Deck",
      airline: "TSA approved for carry-on",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-080",
    name: "Baseus 30000mAh 65W",
    brand: "Baseus",
    category: "charging",
    subcategory: "power_bank",
    price: 59,
    rating: 4.4,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 234,
    tags: ["baseus", "power-bank", "30000mah", "65w", "high-capacity", "value"],
    specs: {
      capacity: "30000mAh / 111Wh",
      output: "65W max (2x USB-C + 2x USB-A)",
      display: "LED digital display",
      charging: "USB-C input 60W",
      compatibility: "Laptops, tablets, phones, multiple devices",
      features: "Simultaneous 4-device charging, Smart protection",
      note: "Check airline regulations for 111Wh",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-081",
    name: "Shargeek Storm 2 100W 25600mAh",
    brand: "Shargeek",
    category: "charging",
    subcategory: "power_bank",
    price: 199,
    rating: 4.6,
    review_count: 567,
    in_stock: true,
    stock_quantity: 34,
    tags: ["shargeek", "storm", "power-bank", "25600mah", "100w", "transparent", "cyberpunk"],
    specs: {
      capacity: "25600mAh / 93.5Wh",
      output: "100W max (1x USB-C 100W + 1x USB-C 30W + 1x USB-A)",
      display: "IPS color screen with real-time data",
      design: "Transparent see-through design",
      charging: "USB-C input 100W, recharges in 90min",
      compatibility: "Laptops, tablets, phones, unique design",
      features: "Cyberpunk aesthetic, DC output, Adjustable voltage",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Wireless Chargers (5)
  {
    id: "gz-082",
    name: "Belkin MagSafe 3-in-1 Charger",
    brand: "Belkin",
    category: "charging",
    subcategory: "wireless_charger",
    price: 149,
    rating: 4.5,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 89,
    tags: ["belkin", "magsafe", "wireless-charger", "3-in-1", "iphone", "apple-watch", "airpods"],
    specs: {
      charging: "15W iPhone MagSafe, 5W Apple Watch, 5W AirPods",
      design: "Official MagSafe compatible",
      adjustability: "iPhone charges in portrait or landscape",
      led: "Ambient light indicates charging status",
      power: "40W adapter included",
      compatibility: "iPhone 12-16, Apple Watch, AirPods Pro/3",
      features: "Nightstand mode support for Apple Watch",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-083",
    name: "Anker MagGo 3-in-1 Charging Station",
    brand: "Anker",
    category: "charging",
    subcategory: "wireless_charger",
    price: 109,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 134,
    tags: ["anker", "maggo", "wireless-charger", "3-in-1", "qi2", "magsafe", "foldable"],
    specs: {
      charging: "15W Qi2 iPhone, 5W Apple Watch, 5W AirPods",
      design: "Foldable and portable",
      adjustability: "iPhone stand with 60-degree tilt",
      certification: "Qi2 certified",
      power: "40W adapter included",
      compatibility: "iPhone 12-16, Apple Watch, AirPods with wireless case",
      features: "Compact foldable design, Travel-friendly",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-084",
    name: "Anker MagGo Qi2 15W Magnetic Wireless Charger",
    brand: "Anker",
    category: "charging",
    subcategory: "wireless_charger",
    price: 49,
    rating: 4.5,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 189,
    tags: ["anker", "maggo", "wireless-charger", "qi2", "15w", "magsafe", "compact"],
    specs: {
      charging: "15W Qi2 / MagSafe for iPhone",
      design: "Slim magnetic pad",
      cable: "5ft USB-C cable included",
      certification: "Qi2 certified",
      compatibility: "iPhone 12-16, AirPods Pro 2",
      features: "ActiveShield safety, Strong magnets",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-085",
    name: "Samsung Wireless Charger Duo",
    brand: "Samsung",
    category: "charging",
    subcategory: "wireless_charger",
    price: 59,
    rating: 4.3,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 156,
    tags: ["samsung", "wireless-charger", "duo", "fast-charge", "galaxy", "buds"],
    specs: {
      charging: "Up to 15W phone + 3.5W Galaxy Buds",
      design: "Slim, compact with LED indicator",
      fan: "Built-in cooling fan",
      compatibility: "Galaxy S/Note series, Galaxy Buds, iPhone, AirPods",
      features: "Fast Wireless Charging 2.0, Foreign object detection",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-086",
    name: "Mophie 3-in-1 Travel Charger MagSafe",
    brand: "Mophie",
    category: "charging",
    subcategory: "wireless_charger",
    price: 149,
    rating: 4.4,
    review_count: 890,
    in_stock: true,
    stock_quantity: 67,
    tags: ["mophie", "wireless-charger", "3-in-1", "magsafe", "travel", "compact"],
    specs: {
      charging: "15W MagSafe iPhone, Apple Watch, AirPods",
      design: "Tri-fold travel design with carrying case",
      adjustability: "Multiple viewing angles",
      power: "30W adapter included",
      compatibility: "iPhone 12-16, all Apple Watch, AirPods with wireless case",
      features: "Snap wireless charging, Zens design, Portable",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Wall Chargers (4)
  {
    id: "gz-087",
    name: "Anker 737 GaNPrime 120W Charger",
    brand: "Anker",
    category: "charging",
    subcategory: "charger",
    price: 89,
    rating: 4.7,
    review_count: 4567,
    in_stock: true,
    stock_quantity: 123,
    tags: ["anker", "737", "ganprime", "120w", "charger", "3-port", "compact"],
    specs: {
      output: "120W total (2x USB-C + 1x USB-A)",
      ports: "2x USB-C PD 3.1, 1x USB-A",
      technology: "GaNPrime with PowerIQ 4.0",
      size: "43% smaller than original 96W MacBook charger",
      compatibility: "MacBook Pro, iPad Pro, iPhone, Galaxy, Steam Deck",
      features: "ActiveShield 2.0, Dynamic power distribution",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-088",
    name: "Anker Nano 3 30W Charger",
    brand: "Anker",
    category: "charging",
    subcategory: "charger",
    price: 19,
    rating: 4.6,
    review_count: 6789,
    in_stock: true,
    stock_quantity: 312,
    tags: ["anker", "nano", "30w", "charger", "compact", "iphone"],
    specs: {
      output: "30W USB-C PD",
      size: "70% smaller than standard 30W charger",
      technology: "GaN technology",
      compatibility: "iPhone 15 Pro Max, iPad, MacBook Air, Galaxy",
      features: "Foldable plug, ActiveShield, Temperature control",
      colors: "Multiple colors available",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-089",
    name: "Baseus 65W GaN 3-Port Charger",
    brand: "Baseus",
    category: "charging",
    subcategory: "charger",
    price: 39,
    rating: 4.5,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 234,
    tags: ["baseus", "gan", "65w", "charger", "3-port", "value"],
    specs: {
      output: "65W total (2x USB-C + 1x USB-A)",
      ports: "USB-C1 65W, USB-C2 30W, USB-A 30W",
      technology: "GaN 3 technology",
      size: "Compact with foldable plug",
      compatibility: "MacBook, iPad, iPhone, Galaxy, Switch, Steam Deck",
      features: "BPS II charging, Temperature protection",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-090",
    name: "Apple 70W USB-C Power Adapter",
    brand: "Apple",
    category: "charging",
    subcategory: "charger",
    price: 59,
    rating: 4.5,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 189,
    tags: ["apple", "70w", "charger", "usb-c", "official", "macbook"],
    specs: {
      output: "70W USB-C PD",
      compatibility: "MacBook Air/Pro 13/14, iPad Pro, iPhone 15/16 series",
      features: "Fast charging for iPhone (50% in 30 min)",
      design: "Apple official, Compact",
      note: "Cable sold separately",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // ========== WEARABLES (10 products) ==========
  
  // Smartwatches (6)
  {
    id: "gz-091",
    name: "Apple Watch Ultra 2",
    brand: "Apple",
    category: "wearable",
    subcategory: "smartwatch",
    price: 799,
    rating: 4.7,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 45,
    tags: ["apple", "watch", "ultra", "smartwatch", "rugged", "outdoor", "gps"],
    specs: {
      display: "49mm Always-On Retina 3000 nits",
      case: "Titanium case with sapphire crystal",
      chip: "S9 SiP with 64-bit dual-core",
      battery: "36 hours normal, 72 hours Low Power Mode",
      sensors: "Blood Oxygen, ECG, Temperature, Depth gauge",
      connectivity: "GPS, Cellular, Wi-Fi, Bluetooth 5.3, UWB",
      water_resistance: "100m WR100, EN13319 dive computer",
      features: "Double tap gesture, Precision Finding, Oceanic+ app",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-092",
    name: "Apple Watch Series 10 46mm",
    brand: "Apple",
    category: "wearable",
    subcategory: "smartwatch",
    price: 429,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 89,
    tags: ["apple", "watch", "series-10", "smartwatch", "slim", "health"],
    specs: {
      display: "46mm Always-On OLED 2000 nits, widest ever",
      case: "Aluminum or Titanium, 9.7mm thin",
      chip: "S10 SiP with 64-bit dual-core",
      battery: "18 hours, faster charging",
      sensors: "Sleep apnea detection, ECG, Temperature, Blood Oxygen",
      connectivity: "GPS, Optional Cellular, Wi-Fi, Bluetooth 5.3",
      water_resistance: "50m, depth and water temperature sensors",
      features: "Double tap, Vitals app, Tides app, Translate",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-093",
    name: "Apple Watch Series 9 45mm",
    brand: "Apple",
    category: "wearable",
    subcategory: "smartwatch",
    price: 329,
    original_price: 429,
    rating: 4.6,
    review_count: 4567,
    in_stock: true,
    stock_quantity: 123,
    tags: ["apple", "watch", "series-9", "smartwatch", "health", "previous-gen"],
    specs: {
      display: "45mm Always-On Retina 2000 nits",
      case: "Aluminum or Stainless Steel",
      chip: "S9 SiP with 64-bit dual-core",
      battery: "18 hours, 36 hours Low Power Mode",
      sensors: "Blood Oxygen, ECG, Temperature, Optical heart",
      connectivity: "GPS, Optional Cellular, Wi-Fi, Bluetooth 5.3, UWB",
      water_resistance: "50m WR50, swimproof",
      features: "Double tap gesture, Precision Finding, On-device Siri",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-094",
    name: "Samsung Galaxy Watch Ultra 47mm",
    brand: "Samsung",
    category: "wearable",
    subcategory: "smartwatch",
    price: 649,
    rating: 4.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 34,
    tags: ["samsung", "galaxy-watch", "ultra", "smartwatch", "rugged", "galaxy-ai"],
    specs: {
      display: "47mm Super AMOLED 3000 nits always-on",
      case: "Titanium case with 10ATM + IP68",
      battery: "590mAh, up to 100 hours in Power Saving",
      sensors: "BioActive (BIA, ECG, Heart rate), Temperature",
      connectivity: "LTE, Bluetooth 5.3, Wi-Fi, GPS, NFC",
      water_resistance: "10ATM + IP68, EN13319 dive grade",
      features: "Galaxy AI, Energy Score, Wellness Tips, GPX routes",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-095",
    name: "Samsung Galaxy Watch 7 44mm",
    brand: "Samsung",
    category: "wearable",
    subcategory: "smartwatch",
    price: 329,
    rating: 4.4,
    review_count: 890,
    in_stock: true,
    stock_quantity: 78,
    tags: ["samsung", "galaxy-watch", "smartwatch", "health", "galaxy-ai"],
    specs: {
      display: "44mm Super AMOLED always-on",
      case: "Aluminum case with Sapphire crystal",
      chip: "Exynos W1000 (3nm)",
      battery: "425mAh, up to 40 hours",
      sensors: "BioActive (BIA, ECG, Heart rate), Temperature",
      connectivity: "Bluetooth 5.3, Wi-Fi, GPS, NFC, optional LTE",
      water_resistance: "IP68 + 5ATM",
      features: "Galaxy AI, Sleep apnea detection, AGEs index",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-096",
    name: "Samsung Galaxy Watch 6 Classic 47mm",
    brand: "Samsung",
    category: "wearable",
    subcategory: "smartwatch",
    price: 279,
    original_price: 429,
    rating: 4.5,
    review_count: 2345,
    in_stock: true,
    stock_quantity: 112,
    tags: ["samsung", "galaxy-watch", "classic", "smartwatch", "rotating-bezel", "previous-gen"],
    specs: {
      display: "47mm Super AMOLED always-on",
      case: "Stainless steel case with rotating bezel",
      battery: "425mAh, up to 40 hours",
      sensors: "BioActive (BIA, ECG, Heart rate), Temperature",
      connectivity: "Bluetooth 5.3, Wi-Fi, GPS, NFC, optional LTE",
      water_resistance: "IP68 + 5ATM",
      features: "Physical rotating bezel, Sleep coaching, Fall detection",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // Fitness Trackers (4)
  {
    id: "gz-097",
    name: "Fitbit Charge 6",
    brand: "Fitbit",
    category: "wearable",
    subcategory: "fitness_tracker",
    price: 159,
    rating: 4.3,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 189,
    tags: ["fitbit", "charge", "fitness-tracker", "health", "google", "exercise"],
    specs: {
      display: "0.76-inch AMOLED always-on color touchscreen",
      sensors: "Heart rate, SpO2, EDA stress, Skin temperature",
      battery: "7 days",
      gps: "Built-in GPS + GLONASS",
      water_resistance: "50m swimproof",
      compatibility: "iOS 15+ and Android 9+",
      features: "40+ exercise modes, YouTube Music, Google apps",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-098",
    name: "Fitbit Inspire 3",
    brand: "Fitbit",
    category: "wearable",
    subcategory: "fitness_tracker",
    price: 99,
    rating: 4.2,
    review_count: 4567,
    in_stock: true,
    stock_quantity: 234,
    tags: ["fitbit", "inspire", "fitness-tracker", "health", "slim", "budget"],
    specs: {
      display: "0.74-inch AMOLED color touchscreen",
      sensors: "Heart rate, SpO2, Skin temperature",
      battery: "10 days",
      gps: "Connected GPS via phone",
      water_resistance: "50m swimproof",
      compatibility: "iOS 15+ and Android 9+",
      features: "Stress management, Sleep tracking, 20+ exercise modes",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-099",
    name: "Garmin Venu 3",
    brand: "Garmin",
    category: "wearable",
    subcategory: "fitness_tracker",
    price: 449,
    rating: 4.6,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 67,
    tags: ["garmin", "venu", "fitness-tracker", "smartwatch", "health", "sports"],
    specs: {
      display: "1.4-inch AMOLED always-on touchscreen",
      case: "Stainless steel bezel, fiber-reinforced polymer",
      sensors: "Elevate Gen 5 heart rate, SpO2, ECG, HRV",
      battery: "14 days smartwatch, 26 hours GPS",
      gps: "Multi-band GPS, GLONASS, GALILEO",
      water_resistance: "5ATM swimproof",
      features: "Sleep coach, Body Battery, Wheelchair mode, Voice calls",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-100",
    name: "Garmin Forerunner 165 Music",
    brand: "Garmin",
    category: "wearable",
    subcategory: "fitness_tracker",
    price: 299,
    rating: 4.5,
    review_count: 890,
    in_stock: true,
    stock_quantity: 112,
    tags: ["garmin", "forerunner", "fitness-tracker", "running", "music", "gps"],
    specs: {
      display: "1.2-inch AMOLED touchscreen",
      sensors: "Elevate Gen 4 heart rate, SpO2, HRV",
      battery: "11 days smartwatch, 19 hours GPS",
      gps: "GPS, GLONASS, GALILEO",
      storage: "4GB for music (Spotify, Amazon Music)",
      water_resistance: "5ATM swimproof",
      features: "Training plans, Race predictor, Morning report",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },

  // ========== BONUS PRODUCTS (varying the prompt) ==========
  {
    id: "gz-101",
    name: "Samsung Galaxy Ring",
    brand: "Samsung",
    category: "wearable",
    subcategory: "smart_ring",
    price: 399,
    rating: 4.2,
    review_count: 345,
    in_stock: true,
    stock_quantity: 56,
    tags: ["samsung", "galaxy-ring", "smart-ring", "health", "sleep", "minimalist"],
    specs: {
      material: "Titanium grade 5",
      sensors: "Heart rate, SpO2, Skin temperature, Accelerometer",
      battery: "7 days, charging case included",
      water_resistance: "10ATM, IP68",
      compatibility: "Android 11+ with Samsung Health",
      sizes: "9 sizes (5-13)",
      features: "Sleep tracking, Energy Score, Cycle tracking",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-102",
    name: "Oura Ring Gen 3",
    brand: "Oura",
    category: "wearable",
    subcategory: "smart_ring",
    price: 349,
    rating: 4.3,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 78,
    tags: ["oura", "ring", "smart-ring", "health", "sleep", "wellness"],
    specs: {
      material: "Titanium with PVD coating",
      sensors: "Infrared LEDs, NTC temperature, 3D accelerometer, Photodiodes",
      battery: "4-7 days, charging dock",
      water_resistance: "100m (328ft)",
      compatibility: "iOS 15+ and Android 8+",
      sizes: "8 sizes (6-13)",
      features: "Readiness score, Sleep stages, Activity tracking, Period prediction",
      subscription: "Membership required for full features",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-103",
    name: "Steam Deck OLED 512GB",
    brand: "Valve",
    category: "gaming",
    subcategory: "handheld",
    price: 549,
    rating: 4.8,
    review_count: 2345,
    in_stock: false,
    stock_quantity: 0,
    tags: ["valve", "steam-deck", "handheld", "gaming", "pc", "portable"],
    specs: {
      display: "7.4-inch HDR OLED 1280x800 90Hz",
      processor: "AMD APU (Zen 2 + RDNA 2)",
      memory: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      battery: "3-12 hours depending on game",
      charging: "45W USB-C PD",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3, microSD slot",
      features: "HDR OLED, 50Wh battery, Faster Wi-Fi",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-104",
    name: "ASUS ROG Ally X 1TB",
    brand: "ASUS",
    category: "gaming",
    subcategory: "handheld",
    price: 799,
    rating: 4.5,
    review_count: 567,
    in_stock: true,
    stock_quantity: 23,
    tags: ["asus", "rog", "ally", "handheld", "gaming", "windows", "powerful"],
    specs: {
      display: "7-inch FHD 120Hz IPS touchscreen",
      processor: "AMD Ryzen Z1 Extreme",
      memory: "24GB LPDDR5X",
      storage: "1TB M.2 2280 SSD",
      battery: "80Wh, up to 11.5 hours video",
      charging: "65W USB-C PD",
      connectivity: "Wi-Fi 6E, Bluetooth 5.2, microSD slot, USB4",
      features: "Windows 11, Armoury Crate, Hall effect joysticks",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-105",
    name: "Nintendo Switch OLED Model",
    brand: "Nintendo",
    category: "gaming",
    subcategory: "handheld",
    price: 349,
    rating: 4.7,
    review_count: 8901,
    in_stock: true,
    stock_quantity: 145,
    tags: ["nintendo", "switch", "oled", "handheld", "gaming", "console"],
    specs: {
      display: "7-inch OLED 1280x720",
      docked_output: "1080p via HDMI",
      storage: "64GB internal + microSD expandable",
      battery: "4.5-9 hours depending on game",
      charging: "USB-C",
      connectivity: "Wi-Fi, Bluetooth 4.1, 3.5mm audio",
      features: "Tabletop mode, TV mode, Enhanced audio, Wide adjustable stand",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
];

// Export count for logging
export const productCount = products.length;
