/**
 * GadgetZone Products - Consumer Mobile Electronics
 * 
 * THIS IS A SAMPLE FILE WITH 10 PRODUCTS.
 * 
 * TO GENERATE 100+ PRODUCTS:
 * 1. Copy the generation prompt from: ./product-generation-prompt.md
 * 2. Use an LLM (Claude, GPT, etc.) to generate products
 * 3. Replace this file contents with the generated products
 */

import { Product } from "./types.js";

export const products: Product[] = [
  {
    id: "gz-001",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "phone",
    subcategory: "smartphone",
    price: 1199,
    rating: 4.7,
    review_count: 3421,
    in_stock: true,
    stock_quantity: 67,
    tags: ["apple", "iphone", "smartphone", "ios", "5g", "oled", "premium"],
    specs: {
      display: "6.7-inch Super Retina XDR OLED",
      processor: "A17 Pro chip",
      storage: "256GB",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      battery: "Up to 29 hours video playback",
      charging: "USB-C, MagSafe, Qi2",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.3",
      features: "Dynamic Island, Action button, Titanium design",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-002",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "phone",
    subcategory: "smartphone",
    price: 1299,
    rating: 4.6,
    review_count: 2156,
    in_stock: true,
    stock_quantity: 54,
    tags: ["samsung", "galaxy", "s24", "smartphone", "android", "s-pen", "200mp"],
    specs: {
      display: "6.8-inch QHD+ Dynamic AMOLED 2X",
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      storage: "256GB",
      camera: "200MP Main + 50MP Telephoto + 12MP Ultra Wide",
      battery: "5000mAh",
      charging: "45W wired, 15W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.3",
      features: "S Pen, Galaxy AI, 7 years updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-003",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    category: "phone",
    subcategory: "smartphone",
    price: 999,
    original_price: 1099,
    rating: 4.5,
    review_count: 1876,
    in_stock: true,
    stock_quantity: 43,
    tags: ["google", "pixel", "smartphone", "android", "ai", "camera", "pure-android"],
    specs: {
      display: "6.7-inch LTPO OLED 120Hz",
      processor: "Google Tensor G3",
      storage: "128GB",
      camera: "50MP Main + 48MP Telephoto + 48MP Ultra Wide",
      battery: "5050mAh",
      charging: "30W wired, 23W wireless",
      connectivity: "5G, Wi-Fi 7, Bluetooth 5.3",
      features: "Magic Editor, Best Take, 7 years updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-004",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "phone",
    subcategory: "smartphone",
    price: 799,
    rating: 4.4,
    review_count: 892,
    in_stock: true,
    stock_quantity: 38,
    tags: ["oneplus", "smartphone", "android", "fast-charging", "snapdragon", "value"],
    specs: {
      display: "6.82-inch 2K ProXDR AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 3",
      memory: "12GB RAM",
      storage: "256GB",
      camera: "50MP Sony LYT-808 + 64MP Telephoto + 48MP Ultra Wide",
      battery: "5400mAh",
      charging: "100W wired, 50W wireless",
      features: "Aqua Touch, 4 years OS updates",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-005",
    name: "AirPods Pro 2nd Gen (USB-C)",
    brand: "Apple",
    category: "audio",
    subcategory: "earbuds",
    price: 249,
    rating: 4.8,
    review_count: 7892,
    in_stock: true,
    stock_quantity: 234,
    tags: ["apple", "airpods", "earbuds", "noise-cancelling", "wireless", "usb-c"],
    specs: {
      type: "True wireless earbuds",
      chip: "H2 chip",
      anc: "2x Active Noise Cancellation",
      transparency: "Adaptive Audio",
      battery: "6 hours + 30 hours case",
      charging: "USB-C, MagSafe, Qi, Apple Watch charger",
      connectivity: "Bluetooth 5.3",
      features: "Precision Finding, Hearing health, Conversation Awareness",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-006",
    name: "Samsung Galaxy Buds FE",
    brand: "Samsung",
    category: "audio",
    subcategory: "earbuds",
    price: 99,
    original_price: 129,
    rating: 4.3,
    review_count: 1234,
    in_stock: true,
    stock_quantity: 156,
    tags: ["samsung", "galaxy-buds", "earbuds", "noise-cancelling", "wireless", "budget"],
    specs: {
      type: "True wireless earbuds",
      drivers: "One 1-way speaker",
      anc: "Active Noise Cancellation",
      battery: "6 hours + 21 hours case (ANC on)",
      charging: "USB-C, wireless",
      connectivity: "Bluetooth 5.2",
      features: "360 Audio, Auto Switch, Bixby voice",
      water_resistance: "IPX2",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-007",
    name: "Anker 737 Power Bank 24000mAh",
    brand: "Anker",
    category: "charging",
    subcategory: "power_bank",
    price: 109,
    rating: 4.7,
    review_count: 3456,
    in_stock: true,
    stock_quantity: 89,
    tags: ["anker", "power-bank", "portable-charger", "24000mah", "140w", "laptop-charger"],
    specs: {
      capacity: "24000mAh / 86.4Wh",
      output: "140W total (2x USB-C, 1x USB-A)",
      display: "Smart digital display",
      charging: "Recharges in 52 minutes",
      compatibility: "Laptops, tablets, phones, Nintendo Switch",
      safety: "ActiveShield 2.0 temperature monitoring",
      airline: "TSA approved for carry-on",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-008",
    name: "Belkin MagSafe 3-in-1 Charger",
    brand: "Belkin",
    category: "charging",
    subcategory: "wireless_charger",
    price: 149,
    rating: 4.5,
    review_count: 2134,
    in_stock: true,
    stock_quantity: 67,
    tags: ["belkin", "magsafe", "wireless-charger", "3-in-1", "iphone", "apple-watch", "airpods"],
    specs: {
      charging: "15W iPhone MagSafe, 5W Apple Watch, 5W AirPods",
      design: "Official MagSafe compatible",
      adjustability: "iPhone charges in portrait or landscape",
      led: "Ambient light indicates charging status",
      power: "40W adapter included",
      compatibility: "iPhone 12-15, Apple Watch, AirPods Pro/3",
      features: "Nightstand mode support for Apple Watch",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-009",
    name: "Anker USB-C to Lightning Cable 6ft",
    brand: "Anker",
    category: "cable",
    subcategory: "charging_cable",
    price: 19,
    rating: 4.6,
    review_count: 5678,
    in_stock: true,
    stock_quantity: 312,
    tags: ["anker", "cable", "usb-c", "lightning", "mfi", "fast-charging", "durable"],
    specs: {
      length: "6 feet / 1.8m",
      connectors: "USB-C to Lightning",
      certification: "MFi certified",
      charging: "Supports fast charging for iPhone",
      durability: "12,000+ bend lifespan",
      compatibility: "iPhone 5 and later, iPad, AirPods",
      color: "White",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
  {
    id: "gz-010",
    name: "UGREEN HDMI 2.1 Cable 6ft",
    brand: "UGREEN",
    category: "cable",
    subcategory: "video_cable",
    price: 15,
    rating: 4.5,
    review_count: 4234,
    in_stock: true,
    stock_quantity: 278,
    tags: ["ugreen", "hdmi", "hdmi-2.1", "8k", "4k", "gaming", "ps5", "xbox"],
    specs: {
      version: "HDMI 2.1",
      bandwidth: "48Gbps",
      resolution: "8K@60Hz, 4K@120Hz",
      features: "eARC, VRR, ALLM, Dolby Vision, HDR10+",
      length: "6.6 feet / 2m",
      build: "Braided nylon, gold-plated connectors",
      compatibility: "PS5, Xbox Series X, RTX 30/40 series, TVs",
    },
    retailer: "GadgetZone",
    trust_level: "trusted",
  },
];

// Export count for logging
export const productCount = products.length;
